feature(article): Article 조회 구현
dev-floor/untitled-server pull request #12
Opened 2021-04-15 02:15 UTC by hungry-jay

* 추가적으로 ArticleHashtag, Hashtag, Favorite 개발
    * author 넘겨주는 부분 dto 구현해야함(여기 준영부분 맞음?)

2021-04-15 03:25 UTC, lxxjn0 requested changes
일단 리뷰를 달다보니 좀 많아지긴 했는데 한번 전체적으로 확인해보면 좋을 것 같아!!
형꺼 리뷰하면서 내 꺼도 고칠게 좀 있을 거 같아서 수정하고 다시 리뷰 요청할께!! 😄 

이번에 이슈가 생각보다 엔티티도 구현할 게 많고 복잡했는데 전체적으로 다 잘 되어 있는 것 같아!! 굿굿 👍🏼

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    classNumber: Option
이것도 내 개인적인 스타일이긴 하지만 아래 프로퍼티를 배열한 순서대로 매개변수를 지정해주는게 다른 사람이 보기에 더 보기 좋고 프로퍼티를 찾기도 편한거 같아

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
해당 필드가 저장되는 방식이 author의 id로 저장되기 때문에 Column name을 author_id로 맞추는 게 좋을 것 같아.

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
우선 이 부분은 저번에 말한 것처럼 option이 여러 개가 추가될 수 있어서 List 로 받는 게 맞을 것 같아.

![image](https://user-images.githubusercontent.com/48052622/114808024-71105e80-9de2-11eb-86d2-a6cbae44ad14.png)

우리가 작성한 클래스 다이어그램도 참고하면 좋을 것 같어!!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
아 저기 Option의 내부에 CLASS_DIVIDED로 OptionTag라 되어있는데 저건 무시해도 될 것 같아. 내가 수정해둘게

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
`@CreatedDate` 어노테이션은 생성 시점의 시간을 설정해주는 값이지 수정 시점에 값을 설정해주진 않아. 이건 `@LastModifiedDate` 라는 어노테이션을 써야할거야.
그런데 내가 이번에 작업한 PR에서 BaseEntity를 구현해둬서 이 프로퍼티랑 createdDate 프로퍼티는 지우고 BaseEntity를 상속하도록 바꾸면 될 거 같아!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Option.kt
> +}
이것도 저번에 말했던 것 처럼 분만만 할 게 아니고 직군, 카테고리 등등 다 포함할 계획이라 이 부분 참고해두면 좋을 것 같아!

그런데 적으면서 생각해보니깐 이 부분에서는 변화될 점이 잦을 것 같아서 일단 이렇게 가고 나중에 좀 더 비즈니스 모델이 제대로 갖춰지면 수정해도 될 것 같아!!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +}
예외처리를 이렇게 메서드마다 하면 컨트롤러에 모든 메서드가 동일한 예외처리 로직을 가지게 될 것 같아. 이 부분은 예전에 한번 말했었던 AdviceController를 하나둬서 처리하는게 더 좋을 것 같아!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleHashtag/domain/ArticleHashtag.kt
> +    val article: Article = article
`@ManyToOne` 어노테이션의 기본 패치 전략이 LAZY로 알고있어서 굳이 LAZY를 명시 안해줘도 되는 걸로 알고 있어!!!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
아 그리고 우리 gradle에 plugin으로 allopen이라는 의존성을 추가해줘서 엔티티마다 open 안 붙여줘도 돼!!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun getArticle(articleId: Long): GetArticleResponse =
다시 보니까 Facade나 Service에 전체적으로 `@Transactional` 어노테이션이 빠져있는거 같아. 만약 조회만 하는 작업이라면 readOnly 옵션도 지정해주면 좋을 것 같아!!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/Favorite.kt
> +    val type: FavoriteType = type
이거 다시보니까 favoriteType으로 프로퍼티 이름을 설정하고 Column도 favorite_type으로 하는게 좋을 것 같아. User 엔티티 보니까 나도 type이라고 했는데 이거 userType으로 바꿀게!!
나중에 테이블 조인하거나 할 때 컬럼 명이 동일하면 헛갈릴 것 같아서 구체적으로 컬럼 명을 가져가는게 더 좋을 것 같아!

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
![image](https://user-images.githubusercontent.com/48052622/114809201-b59cf980-9de4-11eb-93af-b9aab9f8f1e9.png)

지금 다시 보니까 Favorite 객체를 조회해서 내부에서 필터링으로 구분하던데 그냥 `countByArticleAndFavoriteType` 이런 식으로 바꾸는건 어때?

어차피 파사드에서 한 트랜잭션 내부에서 쿼리는 한번에 날라가서 네트워크 비용은 차이없고 쿼리 개수의 차이일 건데 내가 저번에 직접 테스트 해봤을 때 직접 메모리에서 돌리는 것보다 디비에서 실행시키는게 성능적으로 더 좋았던 거 같아!
아니면 실제로 디비에 dummy 데이터 넣고 테스트해보는 것도 좋을 것 같고.

2021-04-15 03:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteType.kt
> +    WONDER("나도궁금해요"),
여기 띄워쓰기 하면 좋을 듯? ㅋㅋㅋㅋ

2021-04-15 03:52 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
굿굿 저게 더 좋겠다

2021-04-15 03:56 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun getArticle(articleId: Long): GetArticleResponse =
이건 개인적인 생각으로 구현부랑 딱 붙어있으면 뭔가 답답하고 가독성 떨어지는 느낌이라
그런 생각 들때마다 이렇게 하긴 했는데 지금 보니까 내 코드 내에서도 저런부분이 있고 아닌 부분이 있네.. .
붙이는거로 통일하는거로 할게 !

2021-04-15 04:00 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/GetArticleResponse.kt
> +data class GetArticleResponse(
아 그렇네.! 요청마다 dto가 다를거라고 생각했는데 그럴 일이 없겠구나 반영완료!

근데 그거랑 별개로 PUT 요청에서는 변경에 대한거니까 변경이 된 article 상세를 보여주기 위해 ArticleResponse가 필요한거 아니야?

2021-04-15 04:01 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/GetArticleResponse.kt
> +        val author: Any,
오키 !!

2021-04-15 04:01 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    classNumber: Option
반영했음 !

2021-04-15 04:05 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
author라는 entity는 없는거 아니야 ?

아 그런데 생각해보니까 article : user = N : 1이니까 저기에 ManyToOne이랑 JoinColumn으로 맵핑하는게 필요한거지!?!?

2021-04-15 04:06 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
아 맞네 분반만 생각하고 다른 option이 올걸 생각 못했다 ! 반영했

2021-04-15 04:08 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
property 네임 option -> options 로 바꾸는거 어때?

2021-04-15 04:13 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
BaseEntity 구현한거 보긴 했어 ! 이거는 그러면 일단 냅두고 너꺼 merge 한 시점에서 그거로 변경하도록 할게 !

2021-04-15 04:19 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Option.kt
> +}
오키 !

2021-04-15 04:20 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteType.kt
> +    WONDER("나도궁금해요"),
이렇게지? 반영했음 !
```suggestion
    WONDER("나도 궁금해요"),
```

2021-04-15 04:28 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
> 지금 다시 보니까 Favorite 객체를 조회해서 내부에서 필터링으로 구분하던데 그냥 countByArticleAndFavoriteType 이런 식으로 바꾸는건 어때?

이부분을 생각 안해본건 아닌데 ! 내가 저게 나을거같다 생각한 이유가 밑의 상황인데, 이론상은 맞다고 생각했는데 실제로 저게 맞는 아이디어인지는 내가 디비를 잘 안다뤄봐서 모르겠어 한번 보고 말좀해줘 !

DB에 100000개의 favorite가 있고, 이 중 100개의 favorite만 해당 게시글의 favorite에 해당한다고 가정.
1. DB에 쿼리를 각각 날리는 방식 :
`FavoriteType == FAVORITE` / `FavoriteType == WONDER` / `FavoriteType == CLIP` 인 것들을  찾으려고 각각 10만번씩 DB에서 조회를 하면서 필터링 할것이기 때문에 총 30만개의 연산

2. 일단 게시글에 해당하는걸 가져온 다음 필터링하는 방식:
Article에 해당하는 favorite(100개) 불러오는 연산 10만개 + 각각 돌면서 favoriteType 필터링하기 : 100 + 100 + 100개의 연산
= 10만 300개

2021-04-15 04:35 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/Favorite.kt
> +    val type: FavoriteType = type
> 컬럼 명이 동일하면 헛갈릴 것 같아서

이부분은 나도 구현하다가 favorite 클래스의 type이니까 굳이 favoriteType 으로 명시하지 않아도 되겠구나 싶었는데 ! 디비 관점에서 보니까 명확하게 해주는게 좋을거같네,, 변경했음!

2021-04-15 04:37 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/Favorite.kt
> +    val type: FavoriteType = type
아 근데 다시 생각해보니까 property 관점에서는 favorite 한정의 type이니까 그냥 type으로 두고 컬럼명만 favorite_type으로 바꾸는건 어때?
우리가 엔티티들 id를 그냥 id로 쓰고 컬럼명에 article_id 이렇게 쓰는것 처럼

2021-04-15 04:43 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
나도 상속부분 찾아보다가 allopen plugin 보긴 봤는데 우리꺼에 들어가있는줄은 몰랐네 !.

그런데 그 플러그인 빼는게 어때?
모든 부분을 open으로 열어두는건 코틀린스럽지 않다고 생각해. 코틀린은 자바랑은 다르게 class 디폴트가 final 인거로 아는데 그만큼 안정성을 추구하는 언어라고 생각해.
근데 allopen을 사용하는건 개발할때 편리하긴 하겠지만 상속이 필요하지 않은 부분까지 허용함으로써 오히려 안정성을 버리는게 아닌가 생각들어서 !

2021-04-15 04:44 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleHashtag/domain/ArticleHashtag.kt
> +    val article: Article = article
찾아보니 그렇네 ! 그부분 제거할게!

2021-04-15 05:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun getArticle(articleId: Long): GetArticleResponse =
뭔지 공부해보고 반영할게 !!

2021-04-15 07:00 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun getArticle(articleId: Long): GetArticleResponse =
이 부분 반영 완료 !

2021-04-15 09:22 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun getArticle(articleId: Long): GetArticleResponse =
아 이건 맞춰도 되긴 하는데 ㅋㅋ 나중에 같이 한번 비교해보는걸로 ㅎㅅㅎ

2021-04-15 09:22 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/GetArticleResponse.kt
> +data class GetArticleResponse(
내가 알기로 get말고 나머지 post, put, delete는 다 수정한 데이터의 아이디를 url에 담아서 보내주는걸로 알고 있었는데 혹시 아니면 다시 말해줘 ㅎㅅㅎ

2021-04-15 09:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
author가 User 객체에 프로퍼티 이름만 author인 걸로 이해하면 좋을 듯? 이것도 아마 클래스 다이어그램에 적어뒀을거야
밑에 리뷰에 클래스 다이어그램 보면 될 듯?
클래스 다이어그램이 대충 이런 명세들을 미리 정해두는 역할을 하니까 클래스 다이어그램 기반으로 코드 작성하되 이상한 부분이 있으면 그걸 같이 이야기하는 식으로 가져가자

2021-04-15 09:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
ManyToOne도 달아야겠다!

2021-04-15 09:26 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
저기 클래스 다이어그램보면 options라고 되어있는데? 아 형이 option으로 구현했네 ㅋㅋ

2021-04-15 09:28 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
내가 알기로 allopen이 무조건 모든 클래스를 open으로 하는게 아니고 특정 주석(어노테이션)이 달린 클래스, 스프링을 동작시킬 때 필요한 부분에 대해서만 open을 하는 걸로 아는데 아닌가?

2021-04-15 09:28 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/Favorite.kt
> +    val type: FavoriteType = type
아 그것도 괜찮을 듯? 컬럼만 favorite_type으로 하는걸로!

2021-04-15 09:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
1. 우선 이게 100% 10만번씩 조회하는게 아닐 수 있는게 index를 어떻게 두냐, where 조건을 어떻게 거냐에 따라서 이건 다 다르게 나와. 이건 실행 계획을 돌려봐야지 확실하게 알 수 있을거야.
2. 두 번째는 횟수는 맞을 수 있어. 근데 내가 위에서 말했던 거처럼 jar 파일이 돌아가는 환경보다 DB 엔진이 훨씬 더 성능이 좋아, 그래서 실질적으로 쿼리를 2번 날리는게 오히려 가져와서 반복문을 한번 돌리는 거 보다 더 빠를 수 있어.

위 두 가지 이유 때문에 내가 저기서 직접 테스트를 해보고 결정하는 것도 좋을 것 같다라고 말한거였어. DB 엔진과 실제 어플리케이션이 돌아가는 환경에서의 성능 차이도 분명히 있고 쿼리도 어떻게 구성하느냐에 따라서 성능 차이가 있어서 이건 테스트를 해보고 결정하면 좋을 것 같아. 그리고 테스트한 결과를 정리해두면 나중에 분명 말할거리도 될 수 있고!

2021-04-15 09:36 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
이슈 - https://github.com/woowacourse-teams/2020-seller-lee-company/issues/403
PR - https://github.com/woowacourse-teams/2020-seller-lee-company/pull/406/files

이거 보면 내가 예전에 프로젝트 할 때 전체 테이블을 긁어와서 반복문을 돌린거랑 그냥 DB에서 처리한 거랑 어떻게 실행시간의 차이가 있는지 볼 수 있어. 한 번 참고해보면 좋을 듯!

2021-04-15 12:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
아 List로 안하고 분반만 생각했어서 내가 option으로 바꿨구나.. ㅋㅋㅋㅋ 하,, ㅋㅋㅋ

2021-04-15 12:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
allopen plugin 확장해서 Entity만 allopen 하도록 하는 좋은방법이 있었어 !<br><br>
![image](https://user-images.githubusercontent.com/49271821/114867359-abecb380-9e2f-11eb-901d-290a7f2b5c8d.png)

2021-04-15 12:36 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/GetArticleResponse.kt
> +data class GetArticleResponse(
아마 구현하기에 따라 다른거같아 ! 너말대로 id만 보내줘도 될 것 같고, `post`방식을 통해 어떠한 객체가 생성이 되면 201 코드와 함께 객체를 보내줄수도 있고 id만 보내줄 수도 있을거같아 ! 물론 결과가 없는 경우 204 코드만 보내줄 수도 있을거같고 !

https://developer.mozilla.org/ko/docs/Web/HTTP/Methods

2021-04-15 12:43 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
음 내가 궁금한게 ! `@JoinToColumn(name = "author_id")` 이렇게 하면 author_id 라는 컬럼에 맵핑될텐데
`@JoinToColumn(name = "user_id")` 요렇게 되어야 디비에서 맵핑이 잘 되는거 아닌가 해서 !

2021-04-15 13:42 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
확실히 Index를 최대한 효율적으로 건다면 DB에서 돌리는 방향의 성능이 좋을수 있을거같네

> 두 번째는 횟수는 맞을 수 있어. 근데 내가 위에서 말했던 거처럼 jar 파일이 돌아가는 환경보다 DB 엔진이 훨씬 더 성능이 좋아, 그래서 실질적으로 쿼리를 2번 날리는게 오히려 가져와서 반복문을 한번 돌리는 거 보다 더 빠를 수 있어.

그런데 이 부분에 대한건 왜 그런지 알수있을까??? 잘 찾아봐도 속도 관련 내용이 잘 안나오는거같아서 !

2021-04-15 13:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
그리고 너꺼 코드보다가 궁금한 점이 생겼는데, 개선 전 후 로직 차이를 보자면

1. 기존에 `findAll()` 후 Stream에서 검증
2. 그냥 DB에서 `existByName()`로 찾아내기

두개를 비교한거같은데 `findAll()`은 디비 전체를 조회하는거고, existBy같은 경우 발견 시점에 return 되니까 이거는 "반복문을 돌린거랑 그냥 DB에서 처리한 거" 의 차이라기 보단 두 쿼리의 차이에서 속도가 달라진거 아니야!?!?

2021-04-15 13:51 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
근데 이건 확실히 테스트를 해봐야 차이를 알수있을거같긴하네 !.!

2021-04-16 00:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
> 확실히 Index를 최대한 효율적으로 건다면 DB에서 돌리는 방향의 성능이 좋을수 있을거같네
> 
> > 두 번째는 횟수는 맞을 수 있어. 근데 내가 위에서 말했던 거처럼 jar 파일이 돌아가는 환경보다 DB 엔진이 훨씬 더 성능이 좋아, 그래서 실질적으로 쿼리를 2번 날리는게 오히려 가져와서 반복문을 한번 돌리는 거 보다 더 빠를 수 있어.
> 
> 그런데 이 부분에 대한건 왜 그런지 알수있을까??? 잘 찾아봐도 속도 관련 내용이 잘 안나오는거같아서 !

이건 내가 알기로 그냥 어플리케이션이 뜨는 환경은 단순히 for 문만 돌리는게 아니잖아. 스프링도 떠있고 어플리케이션이 돌기 위해 다양한 작업들이 일어나고 jvm 위에서 또 돌고있고 그런데 DB는 순전히 데이터만 처리하는 엔진이라서? 그래서 연산 속도는 DB가 훨씬 더 빠르다고 하긴 했어.
그냥 데이터만 처리하는게 주 목적인 서버와 어플리케이션이 운용되는 게 목적인 엔진의 차이라고 생각하면 될 듯? 내가 다른 분들께 여쭤봤을땐 이렇게 답을 받았었어!

2021-04-16 00:37 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
> 그리고 너꺼 코드보다가 궁금한 점이 생겼는데, 개선 전 후 로직 차이를 보자면
> 
> 1. 기존에 `findAll()` 후 Stream에서 검증
> 2. 그냥 DB에서 `existByName()`로 찾아내기
> 
> 두개를 비교한거같은데 `findAll()`은 디비 전체를 조회하는거고, existBy같은 경우 발견 시점에 return 되니까 이거는 "반복문을 돌린거랑 그냥 DB에서 처리한 거" 의 차이라기 보단 두 쿼리의 차이에서 속도가 달라진거 아니야!?!?

아 근데 이건 형 말을 들어보니 비교군이 조금 잘못 되긴 했다. 그런데 내가 말하고자 한 부분은 DB 엔진 환경에서 도는게 훨씬 더 나은 성능을 보일 수 있다는 말이었어.

인덱스를 태우지 않은 상태에서 existBy를 하면 이것도 풀테이블 스캔을 하는건 findAll이랑 마찬가지야. 만약 존재하는 데이터가 맨 앞에 있으면 훨씬 더 빠르겠지만 맨 뒤에 있으면 findAll 하는 만큼 느리겠지. DB에서 실행 속도를 볼 때는 주로 실행계획으로 판단하고 인덱스를 걸지 않았을 때는 findAll도 풀테이블 스캔, existsBy도 풀테이블 스캔이니까 둘 속도는 거의 동일할 거라고 가정했던 것 같아. 물론 데이터의 분포에 따라 분명 차이는 나겠지만 그게 드라마틱한 차이는 아니란게 내 생각이야.

뭐 요점은 실제 저 쿼리를 저렇게 바꾼 이유가 가져와서 for문을 따로 돌리는 거 보다는 DB에서 돌리게 하는게 더 빠를거라는 가정. 그리고 그렇게 실행했을 때 저 정도의 성능 차이를 얻을 수 있었다는 정도로 이해하면 좋을 것 같아. 그냥 단순히 반복문의 횟수가 적은게 더 성능이 좋다고 한다면 DB의 활용도는 현저히 떨어졌을 것이라고 생각해. 그냥 어플리케이션이 데이터를 DB에서 한 번에 다 긁어와서 저장해두고 사용하면 되니까? 그런데 우리가 조회와 관련된 실행 작업을 DB가 하도록 넘겨주고 어플리케이션은 동작에만 집중시키는 이유는 각자가 낼 수 있는 성능의 목적이 다르고 그 결과가 달라서 그런게 아닐까? 하는게 내 생각이야.

근데 이건 진짜 말한 대로 직접 테스트를 해봐야 알 수 있을거 같아. 리뷰를 남겼던 건 혹시나 성능의 개선에 여지가 있는데 단순히 추측만으로 반복문이 더 적으니까 성능이 좋을거야! 라고 생각하고 넘어가는 것보다는
'이런 방법의 성능 개선을 해본 경험이 있으니 여기서 혹시 이런 방법으로 성능 개선이 가능할까? 그런데 테스트를 해봤는데 생각보다 성능 개선이 되진 않았네, 그럼 이런 상황에서는 DB에 매번 쿼리를 찌르는거보다는 반복문을 돌리는게 더 효율적이구나!' 까지 결론을 얻어내는게 더 유의미할거 같다는 이유에서 달아둔거였어.

이걸 순전히 그럴꺼야 하고 넘어가는거랑 직접 확인해보고 나중에 누군가가 이런 로직에 대해 의문을 가졌을 때 확신을 가지고 답을 할 수 있는 거랑은 다르니까?

2021-04-16 00:39 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
아 이건 그 한 번 찾아봐바. `@JoinColumn` 에 name으로 명시하는게 어떤 의미가 있었는데 기억이 잘 안난다..ㅋㅋㅋ

2021-04-16 00:43 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/GetArticleResponse.kt
> +data class GetArticleResponse(
아 보니까 PUT도 200이나 204로 보내줄 수 있네, 200이면 response를 보내주겠다!! 이건 내가 좀 더 공부를 하긴 해야겠다 ㅋㅋㅋ 땡큐!!

2021-04-16 00:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
이걸 아까 말한 것처럼 open을 entity에만 하면 되는지 service와 같은 어노테이션에도 적용이 되어야 하는지 그걸 잘 몰라서 우선 사용하면서 이런 걸 알아갔을 때 수정해 나가는건 어떨까? 아직 정확하게 찾아본게 없어서 잘 모르겠네

2021-04-16 00:52 UTC, lxxjn0 requested changes
이건 추가적인 코멘트가 생각나서 달아뒀어!!

2021-04-16 00:52 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteType.kt
> +}
```suggestion
enum class FavoriteType(val text: String) {
    FAVORITE("좋아요"),
    WONDER("나도 궁금해요"),
    CLIP("스크랩"),
}
```

이거 이렇게 고치면 어떨까? 내꺼는 이렇게 바꿔놨는데 enum 에서 한글 설명? 한글 이름? 이라고 보이는 프로퍼티들을 공통적으로 text로 가져가면 좋을 것 같아. 이렇게 갑자기 생각이 든 게 나중에 favorite에서 따라서 조회해보면 기존에는 favorite.type.type 인데 이렇게 바꾸면 favorite.type.text여서 조금 더 가독성이 좋을 것 같다는 생각이 들었어!! ㅋㅋㅋ

2021-04-16 02:22 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
service같은 어노테이션은 그 어노테이션 자체에서 open을 지원해주는거로 알고있어 ! 저거 말고도 자동으로 open이 되는 것들이 공식문서에 몇가지 나와있긴 하던데 Component(따라서 service도), Configuration 등등 몇가지가 있더라구

저런 것 말고 상속을 사용하고자 하는 클래스가 있다면 `allOpen { }` 이부분에 적어주면 해당 어노테이션을 갖는 클래스만 open이 되는거 같더라구? 아마 `allOpen { }` 이걸 사용하지 않으면 Entity 어노테이션을 붙여도 open이 되지 않는거같아 저거 넣었을 때 경고문구 없어지는거 보니까

allOpen extension 내부 구현체를 봤는데 이렇게 되어있더라. 참고해보면 좋을듯
![image](https://user-images.githubusercontent.com/49271821/114961578-12131e00-9ea4-11eb-9a48-07fc1ab7a9d7.png)

2021-04-16 05:12 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
> 아마 allOpen { } 이걸 사용하지 않으면 Entity 어노테이션을 붙여도 open이 되지 않는거 같아

이건 아닌거 같은게 내가 우리 팀에서 코틀린으로 진행하는 프로젝트 참고하면서 초기 설정을 했는데 따로 저렇게 지정 안해도 엔티티도 다 오픈은 되는 것 같아. 그냥 allopen 플러그인만 명시하고 사용하더라고.
그래도 따로 지정해주면 더 명확하긴 하니까 추가하는걸로 하자!

2021-04-16 05:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
흠.. 이거 무슨 키워드로 찾아보면될까,, 찾는데 잘 안나오

2021-04-16 05:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
흠 이거 맞아?? 근데 나도 실제로 상속받는 코드 작성해서 테스트하는데 아예 컴파일에러가나는디??

allOpen { } 선언 전

![image](https://user-images.githubusercontent.com/49271821/114977136-29610400-9ec2-11eb-9d06-3734886906f5.png)

![image](https://user-images.githubusercontent.com/49271821/114977244-51e8fe00-9ec2-11eb-901e-570a9605e657.png)

allOpen { } 선언 후

![image](https://user-images.githubusercontent.com/49271821/114977338-7d6be880-9ec2-11eb-8dbe-07afac93b503.png)

![image](https://user-images.githubusercontent.com/49271821/114977400-907eb880-9ec2-11eb-9ce5-a1919e8c04e9.png)

참고로 Article은 Entity class고 Foo는 일반 클래스. allOpen에 Entity를 명시 안하고 명시 하고의 차이가 아래 위야 !

2021-04-16 06:11 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteType.kt
> +}
> favorite.type.type 인데 이렇게 바꾸면 favorite.type.text여서 조금 더 가독성이 좋을 것 같다는 생각이 들었어!! ㅋㅋㅋ

오키 option부분도 classNumber -> text 로 해서 아예 enum에서는 text로 일관하는거로!

> 아 그리고 테스트 코드가 하나도 없는데 이번주 남은 시간동안 테스트 코드도 추가해주면 좋을 것 같아!!

테스트.. 가능할까 ㅋㅋㅋ 일단 구현부분이 전부 완성되면 테스트를 짜야할거가튼디

2021-04-16 06:41 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        protected set
여기,, option을 list로 만들려면 enum이 하나의 테이블이 되어야할거같네

https://www.inflearn.com/questions/21303

2021-04-16 08:18 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +}
여기 구현했음 ! ControllerAdvice추가하고, 기존에 IllegalArgumaneException 썼었는데 저거는 다른 부분에서 쓰일거같아서 조금 더 예외를 특정하면 좋을거같아서 NotFoundException 하나 추가했는데 여기 확인한번해줘 !!

2021-04-16 08:22 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +}
아맞다 exception을 common에 둘까 말까하다가,, exception 도메인도 조금 커질수있을거같아서 따로 빼놨는ㄷ ㅔ이건 어떻게생각해??

2021-04-16 08:22 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
![image](https://user-images.githubusercontent.com/48052622/114995026-5c15f700-9ed8-11eb-9b96-1dd6cc46cc72.png)

어 머지?? 난 그냥 잘 되는데??? 뭔가 설정이 다른가

2021-04-16 08:23 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteType.kt
> +}
굿굿!! 테스트는 우리 다 짜는걸로 하자! 이거 기능 개발도 중요하지만 테스트 코드 빨리 짜는 연습도 한다고 생각하고 ㅋㅋ

2021-04-16 08:25 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
뭐지... 이건 일단 그대로 둘게 만나서 함 보자 ! 아 글고 저기 `columnNames= ` 부분에 class_of 로 되어야하는거지 !?
내꺼에서 돌리다가 에러나서 바꿔놓긴했음 !

2021-04-16 08:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
아 맞네 뭐야 저거 내가 안바꾸고 머지했네;; 쏘리쏘리 이거 각자 코드에서 바꾸는걸로 하자 ㅎㅅㅎ

2021-04-16 08:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +open class Article(
아 아니다 develop에 머지한 커밋에는 class_of로 바꿔뒀어!!

2021-04-19 11:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    @Column(name = "author")
여기 반영완료!

2021-04-19 11:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +}
여기도 반영완료

2021-04-19 11:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/FavoriteRepository.kt
> +    fun findByArticle(article: Article): List<Favorite>?
추후 직접 테스트해보기로 !

2021-04-19 13:14 UTC, lxxjn0 requested changes
리뷰 별거 없는데 또 달다보니 넘 많아졌네...ㅋㅋㅋㅋ
이번 거는 크게 중요하기보단 사사로운 부분들이라 그냥 확인하고 슥슥 고치면 될 듯?

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
이거 pathVariable 변수명이랑 매핑된 url의 변수명이랑 달라. `/articles/{id}`로 바꿔야 할 듯?
아 그리고 어노테이션으로 HttpStatus를 설정할 수 있을 건데 상태 코드는 어노테이션으로 관리하고 컨트롤러에서의 반환 타입은 그냥 Response를 반환하는건 어떨까? ResponseEntity말고 그냥 우리가 생성한 Response! 여기선 ArticleResponse

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
아 그리고 이거 변수명 show로 ㅋㅋㅋ

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun show(articleId: Long): ArticleResponse {
나중에 조회에서 다양한 옵션에 따른 조회가 나올 수 있으니까 `showByArticleId`로 메서드명 가져가는건 어때??
Facade의 경우 여러 서비스들이 들어있어서 좀 더 메서드명을 디테일하게 가져가도 좋을 것 같아!!

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
> +    val hashtag: Hashtag = hashtag
이것도 var로 ?!

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
이거 그냥 메시지를 파라미터로 받는 생성자 말고 기본 생성자도 추가해주면 좋을듯? NotFoundException(), NotFoundException(message: String?) 이렇게 두 개!

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
이거 `EntityNotFoundException`으로 이름 하는건 어때? 별론가?? ㅋㅋㅋ

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/presentation/CommonExceptionAdvice.kt
> +        ResponseEntity(HttpStatus.NOT_FOUND)
여기도 상태 코드를 어노테이션으로?!

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> + */
게시글에 대한 좋아요를 관리하는 entity라고 설명을 쓰는게 더 좋을 듯?

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
> + */
```suggestion
/**
 * 게시물과 해시태그 정보를 관리하는 연관관계 매핑 entity
 *
 * @property id 아이디
 * @property article 게시글
 * @property hashtag 해시태그
 */
```

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/domain/ArticleOption.kt
> + */
```suggestion
/**
 * 게시물과 옵션 정보를 관리하는 연관관계 매핑 entity
 *
 * @property id 아이디
 * @property article 게시글
 * @property option 옵션
 */
```

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> +    val type: ArticleFavoriteType = type
여기도 var ?!

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavoriteType.kt
> +enum class ArticleFavoriteType(val text: String) {
뭔가 enum 정도도 docs를 작성해주면 좋을 거 같어!! 나중에 enum 많아질 때 파악하기 좋을 거 같아!

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/domain/Option.kt
> +    val type: OptionType = type
여기도? ㅋㅋㅋ

2021-04-19 13:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +@Table(name = "article")
아 그리고 우리 전체적으로 테이블 명은 복수형으로 바꾸자! articles, options 등등

2021-04-19 13:30 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    private val favoriteService: ArticleFavoriteService,
형님 요거 articleFavoriteService 로 명명법 바꾸면서 객체 이름도 articleFavoriteService로 하는게 맞는건지 확인이 필요해 보입니다!

2021-04-19 14:55 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    val author: User = author
>  Hibernate에서 Entity를 생성할 때 기본 생성자로 생성하고 projection 사용해서 값들을 초기화하거든

혹시 이부분 관련 자료좀 찾아줄수있어??? 나같은 경우는 1. `ID`처럼 자동으로 세팅되어야하는 것은 var로 두고 앞으로 변할 일 없는 프로퍼티 val로 두어도 된다라는 글을 보고서, 2. 많은 레퍼런스들이 val로 되어있던데, 
만약 JPA를 사용할 때 항상 projection 이라는 것을 통해 값을 초기화하고, 그래서 val은 항상 오류를 야기한다면 그 레퍼런스들이 다 잘못된거일텐데 뭔가 정확하게 짚고 넘어가는게 좋을거같아 !

2021-04-19 14:56 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            clips = favorites.count { it.type == ArticleFavoriteType.CLIP }.toLong(),
아아 기억남 !! 반영할게!

2021-04-19 14:57 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: throw NotFoundException("Not found")
뭐라고 표현하면 좋을까? 이런걸 사실 만나서 했어야했는데..
"사용자가 요청한 리소스가 없습니다" ?

2021-04-19 14:57 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            modifiedDate = article.modifiedDate.toString(),
오케이 !!

2021-04-19 15:03 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
> 컨트롤러에서의 반환 타입은 그냥 Response를 반환하는건 어떨까

아 이 부분에 대해서는 원래 성공시의 로직과 에러 로직이 저 메서드 하나에 뭉쳐있었어서 저렇게 했었기도 해 !
그런데 혹시 나중에도 "controller의 한 API에서 성공하는 경우는 항상 한 종류이다" 이게 계속 유지가 되려나??
아니면 물론 저런거 생각 안하고 메서드마다 다르게 유동적으로 해도 상관없긴한데 !?

2021-04-19 15:05 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
> 아 그리고 이거 변수명 show로 ㅋㅋㅋ

`showArticle & showArticles` vs `show vs showAll` ?? Article에 대한 controller니까 후자로 통일할까?

2021-04-19 15:05 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun show(articleId: Long): ArticleResponse {
오케이 !

2021-04-19 15:06 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    private val favoriteService: ArticleFavoriteService,
반영하겠습니다 !

2021-04-20 01:05 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: throw NotFoundException("Not found")
아 아니면 ErrorResponse를 하나 두는걸로 하자! 이번에는 그냥 이렇게 간단하게 메시지로 퉁치고 다음 번 이슈에서 에러 Response를 하나 구현하는걸로?

2021-04-20 02:44 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: throw NotFoundException("Not found")
이게 좋을듯!?

2021-04-20 05:33 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            modifiedDate = article.modifiedDate.toString(),
format 여러개가 있는데 일단 임의로 가장 적절해보이는거로 변경했음
나중에 필요에 따라서 포맷 변경하면 될듯?

2021-04-20 05:38 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: throw NotFoundException("Not found")
저도 찬성입니다. 에러문구도 하드코딩 말고 따로 만들어서 관리하는거 찬성!

2021-04-20 05:40 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
후자가 showArticles, showAll 말씀이신가요?~

2021-04-20 05:44 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            modifiedDate = article.modifiedDate.toString(),
근데 여기 구현하면서 생각든건데 Date format 변경하는 로직을 function으로 만들어서 BaseEntity에 두는건 어떤거같아?

BaseEntity에는 아무래도 Date 말고 들어갈게 있을까? 싶어서 DateEntity나 혹은 무엇이라도 네이밍을 변경하고 해당 메소드를 가지도록 하면 article, user 혹은 나중에 더 Date를 필요로 하는 부분에서 사용하기 편하겠다 생각했는데

2021-04-20 06:07 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
> 후자가 showArticles, showAll 말씀이신가요?~

제가 너무 대강말해서 ㅠ 혼동의 여지가 있겠네요 !
제 말은 1. `하나일때 showArticle, 여러개일때 showArticles` 로 할지 vs  2. `하나일때 show, 여러개일때 showAll` 로 할지
였습니다 !
ArticleController 내부의 메서드기 때문에 후자로 해도 될 것 같긴한데, 두분 의견이 궁금합니다 !

2021-04-20 06:17 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
> `EntityNotFoundException`

흐음 나쁘지 않은거같긴한데, 뭔가 우리가 DB에서 Entity를 찾는다고 말하기보다는 DB에서 `해당 아티클` 이나 `해당 유저` 혹은 `데이터`를 찾는다고 하잖아?? 그런 의미에서 Entity -> Instance나 Object, Data같은 다른것들은 어떤거같아??

2021-04-20 06:20 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
> 이거 그냥 메시지를 파라미터로 받는 생성자 말고 기본 생성자도 추가해주면 좋을듯? NotFoundException(), NotFoundException(message: String?) 이렇게 두 개!

이건 혹시 어떤 이유에서야??? 방금 생각해봤는데 
나는 오히려 Message를 nullable하지 않게 만들어서 어떠한 경우에도 메시지를 쓰도록 바꾸는게 더 좋을거같다고 생각했어 !
그리고 나중에 혹시나 메시지가 전혀 필요 없는 상황이 발생하면, 그 때 기본 생성자를 추가하는 것도 좋지 않나??!

```suggestion
    override val message: String
```

2021-04-20 06:22 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> + */
반영했음 !
근데 사실 나는 여기 볼때마다 뭔가 찝찝한게 좋아요, 나도 궁금해요, 스크랩을 싹 묶은 것은 favorite(좋아요) 가 아니라 다른거였음 좋겠다고 생각이 들어 ㅋㅋㅋ.. 저번에 준형님 의견이었나 리액션도 좋아보이고 !

2021-04-20 06:24 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
> + */
반영완료!

2021-04-20 06:24 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/domain/ArticleOption.kt
> + */
반영완료!

2021-04-20 06:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavoriteType.kt
> +enum class ArticleFavoriteType(val text: String) {
반영완료 !

2021-04-20 06:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +@Table(name = "article")
반영완료 !

2021-04-20 06:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    private val favoriteService: ArticleFavoriteService,
반영완료했습니다 !

2021-04-20 06:37 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            clips = favorites.count { it.type == ArticleFavoriteType.CLIP }.toLong(),
반영했어 ! 여긴 확인한번 부탁해 !

2021-04-20 07:42 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            modifiedDate = article.modifiedDate.toString(),
안 그래도 바꾸는 로직을 봤는데 원래 저렇게 복잡한가?? 아니면 Response로 그냥 LocalDateTime을 반환하는 식으로 해도 될 거 같고

또는 Response의 프로퍼티에 어노테이션으로 `@JsonFormat` 있는데 이거 사용하면 원하는 형식으로 반환될 걸? 아마 이게 맞는걸로 알고 있는데 확실한지는 모르겠다 ㅋㅋㅋ

2021-04-20 07:43 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    val author: User = author
아 나 이거 우리 팀에 물어봤는데 상관없데!!! 그 찾아보니까 id도 val로 쓸 수 있더라고, 0으로 초기화 로직 둬서!

그래서 내 생각엔 우리 엔티티 전체적으로 한번 싹 돌면서 불변, 가변 체크하면 좋을 것 같아서 이 부분 제외한 나머지 리뷰 다 끝나면 이걸 한번에 같이 슬랙에서 이야기하면서 고치자!! val이랑 var

2021-04-20 07:50 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
흠.. 이건 좀 고민되긴 하네.
내가 한번 고민해봤었는데 하나의 어그리거트(도메인, 여기서는 article 패키지)에서 반환되는 내용은 다 해당 도메인의 정보(article)일 거니까 굳이 Article을 붙이지 말자. 단지 조회 조건까지는 붙이면 좋을 듯?

예를 들어 showByArticleId라던지 이런 식? 이 ArticleId라고 하는 이유는 도메인은 Article이지만 facade에서는 다른 도메인의 서비스도 가져오니까 그런걸 대비해서 좀 더 명확하게 이름을 사용한다 정도?

Controller, Facade, Service까지 전반적으로 이런 식으로 통일하면 좋을 것 같아!! 
그런데 Service는 해당 도메인만 사용할걸 아니까 ShowById 정도로 해도 될 거 같고?

2021-04-20 07:54 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
1. Object나 Data의 경우 클래스 종류로 존재하니까 조금 애매할 거 같고 Instance도 괜찮은거 같기도 하고? 둘 중 하나 맘에 드는걸로 ㄲ
2. 아 이건 뭐 형 말도 맞는거 같고 뭘 고르든 상관없는 것 같아! 그냥 익셉션의 경우 한 번 만들면 거의 안 건드릴거 같아서 만드는 김에 만들어두면 좋을거 같아서? 
기본 생성자를 두면 나중에 람다식 사용할 때 편하다보니 쓰일지는 모르겠지만 주로 기본생성자랑 메세지를 받는 형식의 생성자 2개씩은 오버로딩 해두더라고. 그냥 이건 뭐 제안 정도라 안해도 상관없어!! ㅋㅋ
아 그런데 저거 nullable할 수 밖에 없을거 같은게 오버로딩이라 매개변수 타입 맞춰야 하지 않나? RuntimeException의 생성자 파라미터가 Nullable이라 자동으로 Nullable로 생성된 거 같은데?? 저거 고쳐져??

2021-04-20 07:57 UTC, lxxjn0 requested changes
이제 거의 다 괜찮은거 같아서 딱히 더 손 볼 부분은 없을듯?
나머지는 val, var 이거 같이 정하는거 마무리하고 Approve하면 될 거 같어

진짜 이거 형이 작업하는게 스팩이 꽤나 컸는데 진짜 수고햇따!!! 굿굿 💯

2021-04-20 07:57 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            ),
이건 그럼 다시 빼고 Response의 프로퍼티를 LocalDateTime으로 가져가고 어노테이션으로 처리하자!! ㅎㅅㅎ

2021-04-20 07:57 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/domain/OptionType.kt
> + * @property CLASS_FOUR 4분반
이건 프로퍼티가 아니라 상수라서 `@property text` 이거에 대해서만 작성하면 될 듯?

2021-04-20 07:57 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/user/domain/UserType.kt
> + * @property GRADUATE 졸업생
이것도 마찬가지!!

2021-04-20 08:25 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            modifiedDate = article.modifiedDate.toString(),
> Response로 그냥 LocalDateTime을 반환하는 식으로 해도 될 거 같고

근데 DTO는 원시타입으로 주는게 좋지 않을까!!? `@JsonFormat`에 대해 알아볼게 ! ㅋㅋ

2021-04-20 08:33 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    val author: User = author
>  id도 val로 쓸 수 있더라고, 0으로 초기화 로직 둬서!

아 id조차도 그렇게 되는거야!? 나도 "하이버네이트에서 엔티티를 상속받아서 세팅해준다"고 이해했어서 id같은 부분은 mutable이기 때문에 var 이어야 한다고 생각했는데 저건 왜 되느지 궁금하네.,

> 엔티티 전체적으로 한번 싹 돌면서 불변, 가변 체크하면 좋을 것 같아서

좋을듯 ! 위에서 말한 저건 왜 되는지 정확하게 알고 넘어가야것다!

2021-04-20 08:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
> 어그리거트(도메인, 여기서는 article 패키지)에서 반환되는 내용은 다 해당 도메인의 정보(article)일 거니까 굳이 Article을 붙이지 말자. 단지 조회 조건까지는 붙이면 좋을 듯?
예를 들어 showByArticleId라던지 이런 식?

1. 여기까지 나도 같은 의견이야. !
2. 여러개를 조회하는 부분은 `showAllBy~~~` 와 같은 형태로 해도 되겠지?
> 해당 도메인만 사용할걸 아니까 ShowById 정도로 해도 될 거 같고?

3. 이것도 오케이 !

2021-04-20 08:41 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
1. 준형님 의견도 들어보면 좋을 듯 합니다 !
2. 일단 그렇다면 nullable하지 않게 고치고 나중에 필요에따라 추가하는거로 할까!? 
> nullable할 수 밖에 없을거 같은게 오버로딩이라 매개변수 타입 맞춰야 하지 않나? 

아 이거는 사실 내가 명시한거야, 어떻게 전달할지 명확히 몰랐어서 nullable해놨는데 오버라이딩이라 Nullable하지 않게 바꿀 수 있는듯 !

2021-04-20 08:42 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
> 아 이 부분에 대해서는 원래 성공시의 로직과 에러 로직이 저 메서드 하나에 뭉쳐있었어서 저렇게 했었기도 해 !
그런데 혹시 나중에도 "controller의 한 API에서 성공하는 경우는 항상 한 종류이다" 이게 계속 유지가 되려나??
아니면 물론 저런거 생각 안하고 메서드마다 다르게 유동적으로 해도 상관없긴한데 !?

위에 써놓은 이부분은 어떻게하면 좋을까?!?

2021-04-20 08:44 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            ),
오키 적용했음 !

2021-04-20 08:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            modifiedDate = article.modifiedDate.toString(),
반영완료 !

2021-04-20 08:53 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
근데 이 exception 이미 존재하는거였네..? 어카지? 상관없나 ?,,,

![image](https://user-images.githubusercontent.com/49271821/115367553-461e7400-a201-11eb-8859-12fc98787cb1.png)

2021-04-20 08:56 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        ResponseEntity(articleFacade.show(id), HttpStatus.OK)
ㅇㅇ 저 메서드가 값을 반환하는 경우는 무조건 성공해서 반환하는 거니까 어노테이션으로 처리해도 괜찮을듯??

2021-04-20 13:54 UTC, JoonBro reviewed
고생하셨씁니다!

2021-04-21 01:19 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
> 조회할때 공용으로 쓸지 전부 나눠서 쓸지? 나눠서 정의해서 사용한다면 인스턴스든 데이터든 구분만 되면 될거같아요!

1. 별 다른 차이점이 없을 것 같긴해서 같이 써도 될 것 같아요 ! 만약 비즈니스적으로 차이점을 두어야 한다면 나중에 나누는 것도 고려하면 좋을거같아요 ㅎㅎ

> 존재하는 exception 처리가 되는지 테스트를 해봐야 알거같아요!

2. 이 부분은 이미 존재하는 `InstanceNotFoundException` 이나 `EntityNotFoundException` 을 사용해도 되는지 테스트를 해봐야 할 것 같다 라는 의미로 이해해도 될까요?
이거에 대한 제 생각은, JPA에서 사용하기 위해 만든거같이 이미 존재하는 것을 사용해도 되는가?? 라는 의문이 있어서요 ! 만약 문제가 없다면 괜찮지만, 일단 저는 준형님이 올려주신 링크(비지니스Exception 상속받아서 구체화하는 것) 처럼 해도 좋을거같긴해요

2021-04-21 01:23 UTC, hungry-jay commented
> 저도 그게 더 편할거 같긴 한데 머가 더 나은 방식인지는 잘 모르겠네요! 준영이 의견은 어떤가요~

1. 이건 준영이한테 추천받은 방식인데 DTO 자체에서 @JsonFormat 을 이용하니까 간결해지긴 했습니다 !!

> 저는 article내부 메서드기 때문에 상관없을 거 같긴 한데 추후 다른 컨트롤러에 show함수랑 이름이 똑같아지면 나중에 디버깅할때나 좀 어려울 수도 있을거 같다는 생각이 듭니다!

2. 이 부분에 대해 약간 감이 잘 안오는데요 ! 어떠한 상황이 있을지 예시로 알 수 있을까요?

2021-04-21 13:33 UTC, lxxjn0 requested changes
막 바꿀 거 적다보니 생각보다 많은데 금방 고칠 거 같어!!
이것만 다 수정되면 Approve 할게!!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            clips = favorites.count { it.type.isClip() }.toLong(),
이거 내꺼 댓글 API 작성하다가 든 생각인데 favorites는 리스트를 가지는 변수 이름에 어울리고 favoriteCount가 개수를 가지는 변수 이름에 어울린다고 생각하는데 이건 이번 주 작업 다 머지하고 다시 이슈로 파서 한 번에 API 명세 정하면서 수정하면 좋을 듯!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleResponse.kt
> +)
저거 어노테이션 들어가면서 약간 프로퍼티 별 구분이 필요할 것 같아서 사이에 공백을 넣어주는건 어떨까?

```suggestion
data class ArticleResponse(
    val options: List<String>,
    
    val title: String? = null,
    
    val anonymous: Boolean,
    
    val content: String,
    
    val author: Any,
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
    val createdDate: LocalDateTime,
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
    val modifiedDate: LocalDateTime,
    
    val hashtags: List<String>,
    
    val favorites: Long,
    
    val wonders: Long,
    
    val clips: Long
)
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: throw NotFoundException("Not found")
익셉션을 EntityNotFoundException으로 이름을 바꿨는데 여기는 수정이 안되어 있어. 이거 수정해야 할 듯!!
그리고 일단 나중에 형식을 정한다고 치지만 그래도 일단 예외 메시지는 조금이라도 상세하게 바꾸면 좋을 것 같아!!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    var id: Long? = null
이거 val로 바꾸자

```suggestion
    val id: Long = 0
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/ArticleRepository.kt
> +}
이게 자바가 아니라 코틀린이라 코드 본문을 사용하지 않을 경우 `{}`이거 지워도 되더라고. 우리 안쓰이는 곳은 다 지우면 좋을 듯?

```suggestion
interface ArticleRepository : JpaRepository<Article, Long>
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    @ResponseStatus(HttpStatus.OK)
```suggestion
    @ResponseStatus(value = HttpStatus.OK)
```

이런 식으로 쓰는 거 어때? 여기 매개변수로 들어가는 값이 여러개라 이렇게 써주면 뭔가 편할 것 같기도?!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    fun show(@PathVariable id: Long): ArticleResponse =
```suggestion
    fun showById(@PathVariable id: Long): ArticleResponse =
```

 이건 어때? 단건 조회라도 id 말고 다른 조건을 쓸 수도 있으니까?

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        repository.findAllByArticle(article)
이렇게 표현식 쓸 경우 반환타입 명시 안 해도 되니까 없애도 될 듯?

```suggestion
    fun showAllByArticle(article: Article) = repository.findAllByArticle(article)
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        articleFacade.showByArticleId(id)
여기도 생각해보니 표현식이니까 반환 타입 제거해도 될 듯

```suggestion
    fun show(@PathVariable id: Long) = articleFacade.showByArticleId(id)
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
> +    var id: Long? = null
이것도 val로!

```suggestion
    val id: Long = 0
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +        repository.findAllByArticle(article)
이것도 표현식!! 반환 타입 제거?!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/domain/ArticleOption.kt
> +    var id: Long? = null
```suggestion
    val id: Long = 0
```

이것도 val!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/exception/NotFoundException.kt
> +}
```suggestion
data class EntityNotFoundException(override val message: String) : RuntimeException()
```

이렇게 한 줄로 처리 가능할 듯? 그리고 파일 이름이랑 클래스 이름이랑 달라! 파일 이름을 클래스 이름에 맞추면 될 듯!

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/presentation/CommonExceptionAdvice.kt
> +}
ResponseStatus 위치가 잘못된 듯? 그리고 맨 마지막에 빈칸 추가됐어! 그리고 표현식이니까 반환 타입 제거! 메서드명도 수정!

```suggestion
class CommonExceptionAdvice {
    @ExceptionHandler(value = [EntityNotFoundException::class])
    @ResponseStatus(value = HttpStatus.NOT_FOUND)
    fun handleEntityNotFoundException(errorMessage: String) = errorMessage
}
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/application/ArticleFavoriteService.kt
> +        repository.findAllByArticle(article)
이것도 표현식, 반환 타입

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> +    var id: Long? = null
```suggestion
    val id: Long = 0
```

이것도 val

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleResponse.kt
> +    val author: Any,
또 이거 이제 봤는데 ProfileResponse가 없어서 그런거지?
이거 형꺼 머지하고 내꺼 머지될 때 내가 추가해둘게!! ㅋㅋㅋ

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> +    author: User,
이거 파라미터명 수정해야 할 듯?

```suggestion
    user: User,
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavoriteType.kt
> +    fun isClip(): Boolean = this == CLIP
얘들도 다 표현식이니까 반환 타입 없애도 될 듯?

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/Hashtag.kt
> +    var id: Long? = null
```suggestion
    val id: Long = 0
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +}
```suggestion
interface HashtagRepository : JpaRepository<Hashtag, Long>
```

2021-04-21 13:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/domain/Option.kt
> +    var id: Long? = null
```suggestion
    val id: Long = 0
```

2021-04-21 13:43 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            clips = favorites.count { it.type.isClip() }.toLong(),
아 근데 이거 내가 코멘트에  쓰긴 했는데 favorite 내부에 favorite, wonder, clip 있는거 자체가 이상한거같아
내부 favorite를 likes, wonders, clips 이런식으로 바꾸던지 favorite class 자체를 다르게 네이밍하면 좋을거같아

2021-04-21 13:44 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/ArticleRepository.kt
> +}
근데 이런건 나중에 prettier 쓰게되면 가능한부분이니까 지금은 일단 신경안써도되지않아? 일단 커밋 반영 해놓긴할게 !

2021-04-21 13:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleResponse.kt
> +)
반영완료 !

2021-04-21 13:47 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            clips = favorites.count { it.type.isClip() }.toLong(),
저도 다르게 가져가는게 좋아보입니다!

2021-04-21 13:48 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: throw NotFoundException("Not found")
수정 부분 수정했음 ! 위에 쓴거처럼 "사용자가 요청한 리소스가 없습니다" 이렇게 대강 명시해둘게.
계속 바꿀바에 그냥 더 자세한건 나중에 형식을 정해서 하는거로 하자 !

2021-04-21 13:50 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    var id: Long? = null
반영완료 !

2021-04-21 13:51 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    fun show(@PathVariable id: Long): ArticleResponse =
반영완료 !

2021-04-21 13:51 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    @ResponseStatus(HttpStatus.OK)
반영완료 !

2021-04-21 13:51 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    fun show(@PathVariable id: Long): ArticleResponse =
여기 준여이는 showAllByArticleId라고 했던데 comment에서 두개 다 코멘트 조회, 아티클 조회 함수면 두개 맞춰야되는거 맞지?

2021-04-21 13:53 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    @ResponseStatus(HttpStatus.OK)
그냥 저렇게 매개변수 전달하는 부분은 앞으로 전부 값 명시해주는거로 통일하는게 어때?
어디는 쓰고 어디는 안쓰고 이렇게하면 헷갈릴거같으니

아 그리고 메서드 반환형도 (간단한 경우에도)항상 명시하는거로 통일하는게 좋을거같아
전부 명시 안하는건 절대 안되기 때문에, 전부 명시 하는거로 해서 통일성있게 가는게 좋을거같아.

2021-04-21 13:57 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        repository.findAllByArticle(article)
여기도 위에 써놓은거처럼 그냥 다 명시하는게 어때?
가독성 측면에서(물론 주관적인거지만) 명시하는게 훨씬 좋지않나??

2021-04-21 13:58 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
> +    var id: Long? = null
반영완료 !

2021-04-21 13:58 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/domain/ArticleOption.kt
> +    var id: Long? = null
반영완료 !

2021-04-21 14:01 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/presentation/CommonExceptionAdvice.kt
> +}
반영완료 !

2021-04-21 14:01 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleResponse.kt
> +    val author: Any,
author말하는거야? 저기부분은 너꺼 머지되면서 추가해야할거같아 !

2021-04-21 14:05 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> +    author: User,
어.. 뭐지? 수정해서 올려놓은건데 왜 너한텐 저렇게보이지?
저 파일 view File 눌러서 확인해보면 바뀐거 적용되어있음

![image](https://user-images.githubusercontent.com/49271821/115567215-fa012b80-a2f5-11eb-9778-2841dc296a20.png)

2021-04-21 14:14 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/Hashtag.kt
> +    var id: Long? = null
반영 완료 !

2021-04-21 14:14 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +}
반영 완료 !

2021-04-21 14:14 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/option/domain/Option.kt
> +    var id: Long? = null
반영 완료 !

2021-04-21 14:17 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    fun show(@PathVariable id: Long): ArticleResponse =
> 여기 준여이는 showAllByArticleId라고 했던데 comment에서 두개 다 코멘트 조회, 아티클 조회 함수면 두개 맞춰야되는거 맞지?

이 부분 이해를 잘 못했습니다. ! 다시 한번 설명해주실수 있나요??

2021-04-21 14:30 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    fun show(@PathVariable id: Long): ArticleResponse =
아 준영이보고 말했던건데 죄송합니다!
준영이 pr보고 댓글 단거였는데 제가 id랑 articleId랑 헷갈렸어욥 !! 무시하셔도 될꺼 같아요!

2021-04-21 15:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    @ResponseStatus(HttpStatus.OK)
이 부분에 대한 논의 slack에 남겨놓았음 !

2021-04-22 07:47 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
> +    author: User,
모르겠네? 이번 리뷰에서 체크해볼게1!

2021-04-22 08:02 UTC, lxxjn0 approved these changes
추가로 남긴 코멘트까지만 한 번 확인하고 반영하면 좋을 듯? 그리고 작업 다 끝나면 머지 전에 `git pull --rebase origin develop` 한 번 하고 여기서 squash and merge 버튼으로 머지해줘!!

리뷰가 거의 200개가 됐는데 이거 다 반영한다고 진짜 고생많았으!!! 👍🏼

2021-04-22 08:02 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavoriteType.kt
> +    CLIP(text = "스크랩");
이거 매개변수가 하나짜리는 안해줘도 되지 않을까? 두 개 이상 될 때 구분하는 의미가 있다고 생각이 들어서. 이건 조금 더 명확하기 이번 회의 때 결정하면 좋을 듯!

2021-04-22 08:02 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/domain/OptionType.kt
> +    CLASS_FOUR(text = "4분반"),
이것도!

2021-04-22 09:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/presentation/CommonExceptionAdvice.kt
> +    fun handleEntityNotFoundException(errorMessage: String): String = errorMessage
`e.message` 요렇게 써지는구나 ! 수정했슴!

2021-04-22 09:44 UTC, merged