feat(comment): 댓글 조회 API 구현
dev-floor/untitled-server pull request #13
Opened 2021-04-21 13:07 UTC by lxxjn0

### 상세 내용
- Article 작업 내용 squash merge 진행 (`feature/6`)
  - Comment, CommentFavorite 위주로만 봐주시면 됩니다!

closes #9

2021-04-21 13:34 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    fun showAllByArticleId(@PathVariable articleId: Long) =
여기 함수 명명법 주원형님이랑 다르게 명명된거같은데? show 로 하기로 한거 아니였나???

2021-04-21 13:59 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/favorite/application/FavoriteService.kt
> +    fun findAllByArticle(article: Article): List<Favorite> =
showAllByArticle()로 함수명 변경!

2021-04-21 14:08 UTC, JoonBro reviewed
리뷰작성 완료했습니다. 최대한 봤는데...ㅎ

2021-04-21 14:15 UTC, JoonBro requested changes

2021-04-21 14:15 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentResponse.kt
> +data class CommentResponse(
여기서 리스폰스 정의할때 내가 없었어서 그런데 댓글 남긴 시간은 없어도 될까? 아티클 같은 경우도 있는데 댓글도 있는게 좋을거같은 생각이 들어서 의견 물어볼께~

2021-04-21 14:32 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentFacade.kt
> +                favorites = commentFavoriteRepository.countAllByComment(it)
여기 `commentFavoriteRepository` 가 아니라 `commentFavoriteService` 로 접근해야하는 부분 아닌가요 !?

2021-04-21 15:04 UTC, hungry-jay reviewed
아직 Article부분이 merge되지 않아서인지 
바뀐 부분 or 확인하지 않아도 될 파일들이 너무 많이보이네요 !
머지 이후 rebase 하면 다시 리뷰하겠슴니다

2021-04-21 15:06 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentFacade.kt
> +                favorites = commentFavoriteRepository.countAllByComment(it)
이거 왜 밑에랑 분리되었지..?;;;

2021-04-21 15:48 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
제가 주원형님 리뷰에 무시하라고 말씀드렸던 부분이 이거였는데요! 
![image](https://user-images.githubusercontent.com/44499629/115582770-3b003c80-a304-11eb-8132-e991265dac65.png)
저는 제가 id로 아티클 조회하는게 userid로 아티클 조회하는건줄 알고 제가 잘못 생각했구나 했는데 articleId로 article 조회하는거면 함수명도 showByArticleId로 변경하는게 좋을거 같아요!!
![image](https://user-images.githubusercontent.com/44499629/115583040-7c90e780-a304-11eb-8226-488d1853eceb.png)

2021-04-22 01:55 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/favorite/application/FavoriteService.kt
> +    fun findAllByArticle(article: Article): List<Favorite> =
이건 아마 내가 작업한 코드가 아니라 머지 시점에서 확인하고 반영하면 될 듯!!

2021-04-22 01:56 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentResponse.kt
> +data class CommentResponse(
필드에 추가해둘게요!! ㅎㅅㅎ

2021-04-22 01:57 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentFacade.kt
> +                favorites = commentFavoriteRepository.countAllByComment(it)
어 이거 내가 잘못 사용했구나 ㅋㅋ 수정하겠슴다!!

2021-04-22 01:59 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/domain/CommentRepository.kt
> +}
어 이거 코드 포맷터에서 추가하도록 설정 해뒀는데 한번 확인 해볼게요!!

2021-04-22 02:00 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
아 저것도 오타났나보다 ㅋㅋ 수정해두겠음요!!

2021-04-22 02:03 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
> 추가적으로, 코멘트 하나에 대한 get 맵핑에서처럼, id가 두개가 들어올 경우가 있을거같은데, 구별하기 위해서 articleId, commentId 를 사용할거고, 전체에서 통일성을 주기 위해서는 article controller 부분에서도 get resource부분 id -> articleId 로 하는게 좋아보이네여(이건 수정 완료 !)

어, 난 이 부분은 article에서 `GET articles/{id}` 의 경우 그냥 pathVariable을 id로 두는게 좋을 것 같은데? comment도 comments/{id}였으면 그냥 id를 썼을건데 해당 도메인이 아닌 다른 id라서 저렇게 명시했던거야. Article에서 articleId로 조회하는 경우는 그냥 id를 쓰는게 더 좋다고 생각하고, 만약 ArticleController에서 다른 두 아이디를 받을 경우는 구체적으로 명시해주는게 좋을 것 같다는게 내 생각인데 어때?

2021-04-22 02:04 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/user/application/ProfileResponse.kt
> +    val type: UserType,
아 이거는 Enum 타입이 json 파일로 변경될 때 Enum.name 으로 자동 변경되서 저렇게 두긴 했어요!!

2021-04-22 02:06 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentResponse.kt
> +    val user: ProfileResponse,
그냥 ProfileResponse가 json으로 변경되는 것 처럼 동일하게 바껴!!
```json
{
  "user" : {
    "nickname" : "hello"
    ...
  },
  ...
}
```

이런 식으로!

2021-04-22 02:10 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
아티클에서 자기가 쓴 게시글 보기 그런기능에서 유저아이디로 검색할 일이 있을거 같은데?? 그렇게되면 유저아이디 아티클아이디 이렇게 명세하는게 좋아보여서 추가될때 수정해도되지만 추가될 확률이 높지 않을까?!

2021-04-22 02:12 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
내가 얘기하는 부분이 아이디 두개일때라고 얘기하는 부분이 맞나?? 두개를 가지고 동시에 조회할때 얘기인가? 잘 이해를 못했네!

2021-04-22 02:29 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
그렇담 이거도 정하면 좋을듯해요 !

해당 도메인의 Id에 대해서는 Id로 명시(article Controller에서는 articleId -> id로 명시) vs 해당 도메인에서도 도메인이름까지 전부 명시 (article Controller에서도 id -> articleId로 명시)

2021-04-22 02:30 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentResponse.kt
> +    val user: ProfileResponse,
아아 그러면 저렇게 보내줬을 때  프론트 입장에서 `{ nickname, title } = user` 요렇게 json으로 바로 사용이 가능하다는 이야기로 이해하면 되나 !?

2021-04-22 02:31 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/user/application/ProfileResponse.kt
> +    val type: UserType,
오 참고해볼게 !!

2021-04-22 02:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
@JoonBro 말 한 부분 맞는듯? 뭔가 내가 생각하기에 method 명에 그냥 Id만 들어가 있으면 해당 도메인 엔티티에 대한 id로 생각할 것 같고 만약 추가로 다른 엔티티에 대한 id가 필요하면 그때 구체적으로 명시하는게 좀 더 편하지 않을까 생각했는데 이건 조금 고민할 만한 거리인거 같긴 하네..
둘 다 나쁘진 않다고 생각해서. 아니면 이런 부분에서 계속 고민거리가 생긴다는 말은 우리가 패키지 구조 분리를 잘못 한 걸 수도 있고. 이건 조금 더 공부를 하면서 차근차근 개선해나가는거 어때?

2021-04-22 02:48 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
> 패키지 구조 분리를 잘못 한 걸 수도 있고. 이건 조금 더 공부를 하면서 차근차근 개선해나가는거 어때?

근데 이건 사실 코드 스타일에서 일관성을 찾고자하는거니까 !? 자연스러운거 아닐까 ?? 오히려 처음에 이렇게 많은 고민을 한다면 나중에 발생할 수 있는 리팩토링 비용을 줄일 수 있고, 우리끼리 개발에 대한 명확한 바운더리가 생기니까 앞으로는 더 편하게 개발 할 수 있지 않을까!??

2021-04-22 15:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
내가 지금 DDD 책을 읽고 있는데 읽다보면 '한 어그리거트(여기선 패키지라 가정) 내에서의 용어의 모양이 다른 어그리거트에서 동일하다고 해서 그게 같은 값을 의미하진 않는다.  각 어그리거트 내에서의 의미를 생각해야 한다' 이런 식으로 이해하게 되거든? 내가 잘 한 건지 모르겠지만..

저 말이 어려운데 이걸 지금 상황에 풀어서 생각해봤을 때 article이란 패키지 내에서의 id와 comment 내에서의 id에 혼동이 오면 안된다. 이건 각각의 어그리거트 내에서 id 인거지 서로 의미에 영향을 줄 수 없다. 즉, article 내에서 id는 article의 id, comment 내에서의 id는 comment의 id. 이 둘이 이름이 같다고 같은 의미라 생각하면 안된다. 이렇게 생각했거든

그러니까 이미 comment 패키지로 들어와서 내부에서 코드를 볼 때 id라는 도메인 용어는 comment 엔티티에 대한 id라고 생각하는게 맞지 않을까? 라는 생각이었어.

이건 우선 형 코드에서도 이런 식으로 바꿔서 유지하되 한 번 말해보면 좋을 것 같아! 지금 패키지 구조 자체가 DDD 형태를 따라가고 있는 만큼 내가 좀 더 공부해서 최대한 녹여내보도록 해보려고!!

2021-04-22 15:14 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentResponse.kt
> +    val user: ProfileResponse,
엉엉!!

2021-04-22 15:31 UTC, lxxjn0 commented
코드 리뷰 반영했고, 추가적으로 develop에서 수정한 내용 참고 바랍니다.

- `favorite` 패키지 명을 `articlefavorite`으로 변경
- Enum 클래스의 프로퍼티 접근 지정자 일괄 수정
  - 현재 `private`로 되어 있는데 이럴 경우 추후 Enum 사용 시 접근이 불가함
  - 이 부분 `private` -> `public`으로 수정
- `ArticleResponse`의 `author`프로퍼티 타입을 `ProfileResponse`로 수정
- `User` 엔티티 프로퍼티 var -> val로 수정

2021-04-23 02:22 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/domain/CommentRepository.kt
> +}
여기 EOL처리 필요해요 !

2021-04-23 02:22 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/commentfavorite/domain/CommentFavoriteRepository.kt
> +}
여기 EOL처리 필요해요 !

2021-04-23 02:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/user/application/ProfileResponse.kt
> +    val image: String,
우리 근데 user entity에서 image 프로퍼티가 nullable이 아닌데 이거 맞나!?
사용자가 사진 입력 안하면 null로 가져가고 프론트에서 임의로 뭔가 입혀주면 되는거아닌가!?!?

2021-04-23 02:29 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    @GetMapping("/article/{articleId}/comments")
굿굿 이렇게 들으니까 이게 맞는거같다
comment 패키지에서 id로 표현하는건 당연히 comment의 id!

2021-04-23 02:31 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/user/application/ProfileResponse.kt
> +    val image: String,
생각해보니 그렇게 처리하는게 더 편할 것 같긴 하네! nullable로 바꿀게!!

2021-04-23 02:57 UTC, hungry-jay approved these changes

2021-04-23 06:04 UTC, merged