#14 feature(article): 게시글 생성 API 구현
dev-floor/untitled-server pull request #19
Opened 2021-04-29 07:32 UTC by JoonBro

- 작업내용 : Article 생성시 articleOption 생성, hashtag 생성(없을 때), articleHashtag 생성 

close #14

2021-04-29 08:59 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
1. DTO -> Entity로 변경해주는 코드는 Article에 두는게 어떨까요 !?
user와 articleDTO를 사용해서 Article 객체를 만들어주는 것이기 때문에 Article에 있는게 좋을 것 같아요 !

2. 변수명도 `of` 혹은 `toEntity` 바꿔서, 저 메서드를 사용하는 부분(Facade)에서 
`Article.of(articleRequest, user)` 이와같이 사용하도록 한다면, 가독성 측면에서도 좋아질 것 같아요 !

```suggestion
    companion object {
        fun of(
            articleRequest: ArticleRequest,
            user: User
        ) = Article(
            title = articleRequest.title,
            anonymous = articleRequest.anonymous,
            content = articleRequest.content,
            author = user
        )
    }
```

2021-04-29 09:00 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        val article = articleService.create(articleRequest.toArticleWithUser(articleRequest, user))
밑의작성한 리뷰를 적용하게 된다면 이 코드가 아래와같이 변경될 것 같아요 !
```suggestion
        val article = articleService.create(Article.of(articleRequest, user))
```

2021-04-29 09:02 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    }
혹시 25, 26 empty line은 ktlint가 안잡아주나요!?

2021-04-29 09:05 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    }
아 제가 직접 돌려보니 이부분 lint가 잡아주긴 하네요 !!
인텔리제이 우측의 Gradle -> Tasks -> formatting -> ktlintFormat 클릭해 style 적용하시면 좋을것같아요
종종 까먹는걸 방지하기 위해 git hook을 적용해보시는 것도 좋을 것 같습니다!

2021-04-29 09:17 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        }
이와 같이 변경하면 코드가 더 간단해 질 수도 있을거같아요 !!
```suggestion
        hashtagList.forEach {
            articleHashtagList.add(repository.save(ArticleHashtag(article, it)))
        }
```

2021-04-29 09:18 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
이와 같이 변경하면 코드가 더 간단해 질 수도 있을거같아요 !!
아래와 같이 작성하면 코드가 더 간단해질 수 있을 것 같아요 !
```suggestion
        hashtagList.forEach {
            articleHashtagList.add(repository.save(ArticleHashtag(article, it)))
        }
```

2021-04-29 09:19 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
아 그런데, 해당 create 메서드를 이용하는 facade에서는 create의 반환값인 `List<ArticleHashtag>` 를 받아서 할당만 해놓지, 정작 그 변수를 이용하지는 않는 것으로 보입니다 !
따라서 아무것도 반환하지 않는 형태로 바꾸고, 21번째 줄과 25번째 줄을 생략해도 되지 않을까요!?

2021-04-29 09:21 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
이 부분도 위와 동일합니다.
1. 이 메소드를 사용하는 facade에서는 이 메소드의 반환인 `List<ArticleOption>` 을 할당만 해놓고, 전혀 사용하지 않고 있습니다 ! 따라서 여기도 생략 가능할 것 같고,
2. for문 또한 위 처럼 변경 가능할 것 같아요 !

2021-04-29 09:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    fun show(hashtags: List <String>): List<Hashtag> {
메서드가 List를 반환하는 것으로 보입니다 !
따라서 showAllByNames와 같이 메서드명을 변경하는게 어떨까요?
```suggestion
    fun showAllByNames(hashtags: List <String>): List<Hashtag> {
```

2021-04-29 09:30 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +    fun findByNameIn(hashtagNameList: List <String>): List<Hashtag>
1. 이 부분이 엊그제인가 슬랙에 공유해주셨던 query를 사용하는?? 부분이 맞나요?
현재는 쿼리가 필요 없기 때문에 `In` 은 없애주면 어떨까요?

2. 이 부분 또한 name에 해당하는 것들 전부 반환하기 때문에 findAllByName이 적절할 것 같아요!

3. 변수명에 List와 같이 특정 타입을 유추할수 있는 용어를 지양하는 것이 좋다고 합니다. ! 타입이 추후 변경되면 메서드명까지 수정해야하기 때문에요. 따라서 매개변수부분 hashtagNames로 변경하는 것도 좋을거같습니다
```suggestion
    fun findAllByName(hashtagNames: List <String>): List<Hashtag>
```

2021-04-29 09:34 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
아래와 같이 변경하면 더 깔끔해질 것 같아요 !
```suggestion
    fun show(options: List<String>): List<Option> {
        return options.map {
            repository.findByType(showOptionType(it))
        }
    }
```

2021-04-29 09:36 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        val articleHashtags =
밑에도 말씀 드렸긴한데, 이 변수 사용되지 않는 것으로 보입니다 !

2021-04-29 09:36 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        val articleOptions =
밑에도 말씀 드렸긴한데, 이 변수 사용되지 않는 것으로 보입니다 !

2021-04-29 09:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
제가 줄을 잘못 insert했네요ㅠ 여기서 commit suggestion을 누르지 않고, 직접 변경하셔야 될 것 같아요 ㅠ

2021-04-29 09:40 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
이 부분 OptionType을 반환하는 메소드니까, 메소드 자체를 OptionType 내부에 두는 것은 어떨까요!?

2021-04-29 09:42 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
아래와같이 OptionType 내부에 둘 수 있을 것 같아요 !
```
companion object {
        fun of(optionName: String): OptionType {
            return valueOf(optionName)
        }
    }
```

2021-04-29 09:43 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
메소드를 호출하는 부분에서는
`repository.findByType(OptionType.of(it))` 요렇게 쓸 수 있을거 같습니다

2021-04-29 09:45 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            } else null
Facade 내부 로직이 조금 복잡해보이는데, 이건 이번 리뷰 반영 후에 다시한번 더 보는게 좋을 것 같습니다 !

2021-04-29 14:16 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
어, 이 부분은 전 지금이 맞다고 생각합니다!

article 엔티티 내부에서 dto를 article로 만들면 article이 articleRequest를 의존하게 됩니다. 의존 방향이 역전돼요!
만약 프론트에서 request 형태가 바뀌면 변경 범위가 articleRequest까지 영향을 미쳐야지 도메인 로직인 article 엔티티까지 미치면 안됩니다!

그래서 지금처럼 DTO에서 Entity를 만들어주는게 맞는 것 같네요!

2021-04-29 14:19 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
위처럼 로직이 그대로 Request에 존재할 경우 주원이형이 2번에서 제안한 것처럼 로직을 바꿀 필요는 없을 것 같습니다.
추가적으로 여기서는 적용하는게 옳지 않아보이지만 주원이형이 제안한 방법을 정적 팩토리 메서드라고 부릅니다.

이건 아무 글이나 링크 걸긴 했는데 [생성자 대신 정적 팩토리 메서드를 고려하라](https://velog.io/@litien/%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC) 이런 종류의 글을 읽어보면 좀 더 도움이 되지 않을까 싶습니다.

2021-04-29 14:22 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
여기서도 for문을 forEach문으로 변경하는 것이 항상 좋은 방법인가에 대해 알아보면 좋을 것 같아요!

[for-loop 를 Stream.forEach() 로 바꾸지 말아야 할 3가지 이유](https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/)

2021-04-29 14:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
아.. 의존성을 생각해봤을땐 DTO에서 만드는게 맞을거같네요 !
생각해보니까 도메인에서 dto를 입력를 받아 무언가를 만들어주는건 오히려 이상해보일수있겠네요 !
그렇다면 이 부분만 반영해주셔도 좋을거같아요 !
```suggestion
    fun toArticleWithUser(articleRequest: ArticleRequest, user: User): Article {
        return Article(
            title = articleRequest.title,
            anonymous = articleRequest.anonymous,
            content = articleRequest.content
            author = user)
    }
```

2021-04-29 14:52 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
제가 생각했을 때 for과 forEach의 가장 큰 차이는
iter 돌다가 break나 continue를 통해 루프를 빠져나오는 것이 필요하냐 혹은 해당 list를 한바퀴 전부 도는 것이 목적이냐에 따라 다른 것 같아요.
그런데 현재 코드에서는 list 한바퀴를 전체 돌면서 index를 통해 각 element에 접근하고 있는데, 중간에 빠져나오는 것이 필요한게 아니라면 forEach가 좀더 적절한 코드라고 생각합니다.

2021-04-29 14:54 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
아 그리고 성능에 대해서도, 일반적인 반복문이 아닌 list, map과 같은 컬렉션을 도는 부분이라면 forEach가 더 빠르다고도 합니다 !

2021-04-29 14:55 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
요건 forEach 구현부 입니다. 보니까 얘도 내부적으로는 for로 구현되어있네요
![image](https://user-images.githubusercontent.com/49271821/116571787-5b547a80-a946-11eb-94f5-5314d1a6515d.png)

2021-04-29 15:27 UTC, lxxjn0 requested changes
처음 코틀린으로 작성해준 코드라고 생각하기엔 너무 충분히 잘 작성해주셨네요!! 👍🏼 
우선 참고하면 좋을만한 코멘트를 상세히 달아뒀는데 참고해서 수정 부탁드릴게요!!

굿굿입니다 💯

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        val article = articleService.create(articleRequest.toArticleWithUser(articleRequest, user))
여기 사이에 의미없는 공백이 들어간 것 같습니다!!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            } else null
이 부분은 `articleRequest.options`가 emptyList이면 그냥 넘어가도 되는 로직일 것 같아요!!
그리고 만약 `articleRequest.options`가 emptyList가 아닌데 조회해 온 `options`가 emptyList라면? 이건 존재하지 않는 옵션을 등록하려고 하는 거라서 여기에 도달하기 전에 조회 부분에서 에러가 발생할 거에요.

그래서 최대한 불필요한 작업을 막기 위해

```
if (articleRequest.options가 emptyList가 아니라면) {
    optionService에서 option을 조회해온다.
    articleOptionService에 해당 게시글과 option 간의 관계를 생성한다. 이때 반환되는 articleOptions는 필요없으니까 변수에 할당하지 않는다.
}
```

이런 느낌으로 하면 되지 않을까요?

추가적으로 `articleRequest.options`가 emptyList가 아니라면 `articleRequest.options`를 반복하면서 한 번에 작업이 가능하도록 처리 할 수 있을 것 같아요!!
이 부분은 java의 stream이나 kotlin의 체이닝 메서드?(맞나 모르겠네요) 이걸 참고하면 좋을 것 같습니다!!
[kotlin docs](https://kotlinlang.org/docs/basic-syntax.html#collections)의 3번째 Using lambda... 이 부분 참고해서 학습해보면 좋을 것 같아요!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        val hashtags = hashtagService.show(articleRequest.hashtags)
여기서 hashtagService에 넘어가는 해시태그 중 존재하지 않는 태그의 경우 생성하는 로직까지 포함되어 있을 것 같아요!!
그런 경우에 좀 더 이름을 명시적으로 가져가주면 좋을 것 같습니다!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        )
게시글을 생성할 경우 response를 안 넘겨주기로 결정돼서 생성된 article의 id만 넘겨주면 될 것 같아요!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +            } else null
이 부분도 위에서 말한 lambda식을 활용한 방법으로 수정해보면 좋을 것 같습니다! 이 부분은 다음 리뷰에서 피드백 주는 걸로 할게요!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +        return Article(articleRequest.title, articleRequest.anonymous, articleRequest.content, user)
이 부분 named arguments로 처리해주면 좋을 것 같아요!!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +        return articleFacade.create(articleRequest, user)
User는 나중에 디버깅 할 때 용이하게 title이나 content 등등 빈 문자열 대신 의미없는 텍스트라도 담아두면 좋을 것 같아요!!
그리고 이 부분도 named arguments로 처리 부탁드릴게요!!

추가적으로 id만 반환하면 될 것 같아서 이 부분도 수정하면 좋을 것 같아요!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteRepository.kt
>  }
의미없는 빈 문자열이 추가됐습니다!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
이 부분은 `create`라는 이름의 메서드는 단 건(article 1개, hashtag 1개만 인자로 받음)만 생성하도록 하고 `createAllByHashtags`라는 메서드를 새로 만드는 건 어떨까요?

이 부분은 한 번 참고해보시라고 코드를 작성해보면

```kotlin
    @Transactional
    fun create(article: Article, hashtag: Hashtag): ArticleHashtag {
        return repository.save(ArticleHashtag(article, hashtag))
    }

    @Transactional
    fun createAllByHashtags(article: Article, hashtags: List<Hashtag>): List<ArticleHashtag> {
        return hashtags.map { ArticleHashtag(article, it) }
            .let { repository.saveAll(it) }
    }
```

이건 한 번 참고해보고 잘 모르겠으면 한 번 공부해보면 좋을 것 같습니다!! 👍🏼

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtagRepository.kt
>  }
여기도 불필요한 공백!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
이 부분은 앞선 `ArticleHashtagService`에서 보여드린 코드를 보고 한 번 수정해보시면 좋을 것 같아요!!
그리고 추가적으로 `toArticleOption` 메서드의 역할은 뭘까요? 그리고 이렇게 만들면 어떤 장점이 있나요??

메서드를 어떤 기준을 가지고 분리하면 좋을지도 고민해보면 좋을 것 같습니다!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
transactional에 readonly 붙인거 👍🏼 
저도 주원이형 생각이랑 마찬가지로 조금 더 명시적인 이름을 가져가면 좋을 것 같아요!! 추가적으로 받아오는 파라미터의 이름 또한 좀 더 의미를 알 수 있게 고쳐보면 좋을 것 같네요!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
이 부분도 메서드명은 위에서 남긴 리뷰와 동일한 관점입니다!
추가적인 로직은 다른 서비스에서 보여줬던 예시들을 참고해서 직접 작성해보면 좋을 것 같아요!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +    fun findByNameIn(hashtagNameList: List <String>): List<Hashtag>
이 부분은 주원이형 피드백에 이어서 달게요!!

이건 뒤에 In이 들어가는게 맞을 것 같아요!! 일단 IDE에서 자동완성 해주는 네이밍이 이처럼 생성될겁니다(아마도?)
그리고 실제로 쿼리도 In절로 날라갈거에요.
위에서 제안해 준 findAllByName이라는 메서드로 생성하면
```kotlin
fun findAllByName(name: String) : List<Hashtag>
```

이런 식일겁니다. 즉 하나의 Name에 해당하는 모든 Hashtag가 조회될 거에요! (물론 비즈니스적으로는 불가능하지만 JPA에서는 이렇게 인식할겁니다)

```kotlin
fun findAllByNameIn(names: List<String>): List<Hashtag>
```

이건 뒤에 names가 in절 조건으로 들어가서 조회될 것이고요.
그래서 위 상황에서는 마지막에 In을 붙이는게 맞을 것 같네요!!

추가적으로 3번에 List라는 이런 특정 타입을 지칭하는 용어를 사용해서 명명하지 않는게 좋다는 부분은 주원이형이 잘 설명해준 것 같아요!!
단순하게 List에서 Set으로 자료구조를 바꾼다면, 기존에 이름이 names가 아닌 nameList라면 명명까지 바꿔야겠죠? 그런데 names였다면 복수형이기 때문에 굳이 명명을 바꿀 필요는 없었을겁니다!! 그래서 주로 불용어를 명명에 사용하지 않습니다!!!

2021-04-29 15:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
이 부분도 주원이형이 좋은 피드백 남겨줘서 코드적인 부분에서만 추가로 설명하겠습니다.
우선 option의 name을 가지고 OptionType을 조회하는 부분은 주원이형이 추천해준 대로 OptionType 내부에 구현해두면 좋을 것 같아요!!

그런데 주원이형이 추가해 준 코드에서 잘못된 부분들이 있어서 이 부분들만 체크해두겠습니다!

```kotlin
// OptionType.kt
enum class OptionType(val text: String) {
    CLASS_ONE("1분반"),
    CLASS_TWO("2분반"),
    CLASS_THREE("3분반"),
    CLASS_FOUR("4분반"),
    ;

    companion object {
        fun from(text: String): OptionType {
            return values().first { it.text == text }
        }
    }
}
```

우선 여기서 생성된 `from` 메서드를 아까 다른 피드백에서 설명해줬던 정적 팩토리 메서드라고 합니다. 그래서 이처럼 구현할 수 있고 first 메서드의 경우 위 `CLASS_ONE` ~ `CLASS_FOUR` 의 text가 파라미터로 전달받은 값과 일치하는지 여부를 확인하고 해당하는 OptionType을 반환해줍니다.

주원이형이 올려둔 `valueOf()`의 경우 매개변수로 `"CLASS_ONE"` 이런 String 값을 넘겨줘서 해당하는 OptionType을 찾게 도와주는 함수입니다.

그래서 여기서 만약 파라미터로 넘어오는 값이 `"1분반"`과 같은 문자열이라면 위와 같이 구현하면 될 것 같고, 만약 `"CLASS_ONE"`과 같은 문자열이라면 굳이 함수를 만들 필요 없이 제공해주는 `OptionType.valueOf()` 메서드를 사용하면 될 것 같습니다!!

우선 여기서는 전자라고 가정하고 작업을 진행해주시면 될 것 같아요!!

추가적으로 팩토리 메서드 명을 of가 아닌 from을 했는데 이 부분도 앞서 달아준 [enum 링크](https://velog.io/@litien/%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC)에서 제안하는 메서드 명을 참고해보면 좋을 것 같습니다 (이 제안하는 메서드 명은 이펙티브 자바라는 책에서 제안하는 내용과 동일해서 참고 링크를 추가해뒀습니다)

2021-04-29 15:32 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        )
엥 아니지않ㄴ아!? 정답이 없는거니깐 우리끼리 걍 편한대로 response 넘겨주는것으로 결정하지 않았나용

2021-04-29 15:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
저도 이 부분 보면서 DTO와 entity를 맵핑해주는 좋은방법이 뭘까 고민중이긴 한데요, 일단 코틀린에서는 직접 맵핑해줄 때 각각이 어디에 맵핑될지 가독성자체가 좋아서 많이들 그냥 맵핑하기도 하더라구요 !

아 그리고 찾아보다가 ModelMapper? 라는애를 우연히 보게 되었는데 Entity to dto, dto to Entity 잘 할수있게 도와주는 것 같더라구요. (그런데 이걸 사용하는게 적절할지는 사실 잘 모르겠어요 아직 저도 찾아보고있어서..)

그래서 이 부분도 한번 참고해보시면 좋을 것 같습니다.

2021-04-30 01:18 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +    fun findByNameIn(hashtagNameList: List <String>): List<Hashtag>
제가 In이라는 것에 대해 잘못 이해하고 있었네요 ! 준형님이 올려주신 자료 다시한번 보고 이해했습니다!

2021-04-30 01:57 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +
오 Java에서 stream을 통한 forEach랑 코틀린이랑 조금 차이가 있네요!! 좋은 정보 감사함다 ㅎㅅㅎ

2021-04-30 01:58 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        )
그래서 게시글의 경우는 어차피 redirect가 발생할 것 같아서 response없이, 댓글 같은 경우는 redirect 없이 해당 페이지에서 다시 정보를 띄워줘야해서 response 포함해서.

이렇게 결정된 걸로 알고있는데 아니였어?
어차피 게시글은 생성하면 상세조회 페이지로 redirect가 필요하기 때문에 response를 넘겨줄 필요가 없을 것 같은데.

2021-04-30 01:59 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
위 코드에서 dto랑 entity를 매핑하는 부분은 없지 않나요???

2021-04-30 02:09 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
아 어제 피곤할때 달아서 헷갈렸네요
https://github.com/dev-floor/untitled-server/pull/19#discussion_r622862187
여기의 `toArticleWithUser` 이 부분이랑 혼동했습니다. !! 저 리뷰는 그대로 다시 저기에 달아놓을게요

2021-04-30 02:09 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
이 부분 보면서 DTO와 entity를 맵핑해주는 좋은방법이 뭘까 고민중이긴 한데요, 일단 코틀린에서는 직접 맵핑해줄 때 각각이 어디에 맵핑될지 가독성자체가 좋아서 많이들 그냥 맵핑하기도 하더라구요 !

아 그리고 찾아보다가 ModelMapper? 라는애를 우연히 보게 되었는데 Entity to dto, dto to Entity 잘 할수있게 도와주는 것 같더라구요. (그런데 이걸 사용하는게 적절할지는 사실 잘 모르겠어요 아직 저도 찾아보고있어서..)

그래서 이 부분도 한번 참고해보시면 좋을 것 같습니다.

2021-04-30 02:17 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        )
redirect라는게 뭔지 잘 몰라서.. redirect == "정보를 얻기 위해 다시 API를 호출한다"로 이해하면되나!?

2021-04-30 08:56 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
ModelMapper에 대해서 조금 찾아봤는데 일단 Kotlin 레퍼런스가 많이 없고 성능 이슈가 있는 것 같습니다.
따라서 Kotlin에서는 직접 매핑하는게 제일 간단하고 좋아보이네요 !

2021-05-01 07:52 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        )
그치 실질적으로 API가 다시 호출할 수 밖에 없는 상황이라 보면 될 것 같아.

상황을 가정해볼게.

프론트에서 게시글을 생성하는 화면이 `https://hello.com/articles/create` 라는 URL에서 진행된다고 하자.
그럼 다 작성된 게시글을 생성 요청을 할거잖아.
그럼 post로 우리한테 요청이 들어오고 우린 생성이 완료되면 response(이때 id는 1이라고 가정)를 주겠지.
그럼 사용자는 게시글 생성이 완료되었다는 것을 알거니까 내가 생성한 게시글의 상세 페이지로 가고 싶을거잖아.

그럼 상세 페이지는 `https://hello.com/articles/1` 이라는 URL로 가야지 보여질거거든?
그럼 이 페이지가 랜더링 되는 시점에서 get 요청이 다시 보내지긴 하겠지.

생성한 페이지에서 해당 게시글에 대한 상세 페이지로 navigate 시켜준다를 redirect 시켜준다고 생각하면 될 것 같아.

2021-05-01 14:00 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +    }
변경완료했습니다!

2021-05-01 14:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    }
제가 설정을 아직 안헀네욥!! 가르쳐주신대로 적용해보겠습니다.

2021-05-01 16:40 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
enum class OptionType(val text: String) {
    CLASS_ONE("1분반"),
    CLASS_TWO("2분반"),
    CLASS_THREE("3분반"),
    CLASS_FOUR("4분반"),
    companion object{
        fun of(optionName: String): OptionType {
            return valueOf(optionName)
        }
    }
}


어떻게 사용하는건지 내일 여쭤볼게요 !! companion object!

2021-05-01 16:50 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
제가 실수했네요! 함수없이 생성하겠습니다~

2021-05-03 16:01 UTC, hungry-jay reviewed
아직 Kotlin 익숙하지 않으실텐데, 개발, 리팩토링 고생하셨습니다 !!

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        if (!articleRequest.hashtags.isNotEmpty()) {
이 부분 혹시 `!`과 `Not`을 없애고 아래와같이 변경하면 안되는 점이 있나요!??
```suggestion
        if (articleRequest.hashtags.isEmpty()) {
```

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +                    articleHashtagService.createAllByHashtags(article, it)
DTO에서의 hastags, options 리스트는 non-null인 것으로 보이는데

line 31에서 `isNullOrEmpty()` 대신 `isEmpty()`로,
line 25에서 `!`를 제거하고 `isNotEmpty()` 로 변경해도 되지 않나요?

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
이 부분의 코드가 잘 이해가 가지 않는 부분이 있습니다 !
1. (line 29에서) 사용자가 등록하고자하는 hashtag가 "없는" 경우 -> 여기 혹시 "있는" 경우에 여야 하는거 아닌가요??
2. 만약 이 로직이라면, 사용자가 작성한 해시태그중 일부만 hashtag 테이블에 등록되어있을 때는 31번째 줄이 false가 되어 hashtag 테이블에 create하는 과정을 생략하는데, 이 경우에는 기존에 hashtag에 등록되어있지 않은 해시태그는 저장되지 않는 것 아닌가요???

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +        return Article(
굉장히 개인적인 의견인데요,! 여기 혹시 `toEntity` 와 같은 메소드명은 어떠하신가요!?
메서드 사용부를 보면 `articleService.create(articleRequest.toArticleWithUser(articleRequest, user))`
이렇게 되어있는데요, `ArticleWithUser` 로 변경한다는 네임보다 `Entity` 로 변경한다는 네임을 사용한다면 해당 메소드의 목적(엔티티로 변경) 이 더 명확하게 전달되지 않을까 해서요 !

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteRepository.kt
>  }
lint처리가 안되어있는 것 같아요 !

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
이 부분이 아마 슬랙에서 말씀하셨던, 깃이 꼬여서 반영이 안된 부분인 것 같아요 !!
아래와 같이 바꿀 수 있을거같아요
```suggestion
    @Transactional
    fun createHashtags(hashtags: List<String>): List<Hashtag> {
        return hashtags.map {
            repository.save(Hashtag(it))
        }
    }
```

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +}
여기도 반영 안 된 부분 같아요 ! 이 부분에 대해서는 Unresolve conversation 누르셔서 리뷰 내용 한번 확인하시고 반영하시면 좋을 것 같아요!
```suggestion
interface HashtagRepository : JpaRepository<Hashtag, Long>{
    fun findAllByNameIn(hashtagNames: List <String>): List<Hashtag>
}
```

2021-05-03 16:01 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
Hashtag 내부에서의 메서드이기 때문에 그냥 `create`로 네이밍하는게 어떨까요 !?
마찬가지로 18번째 줄의 `createHashtags`는 `createAll` 로 변경 가능할 것 같아요!

2021-05-07 05:04 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        if (!articleRequest.hashtags.isNotEmpty()) {
없습니다! 수정하겠습니다!

2021-05-07 05:05 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +                    articleHashtagService.createAllByHashtags(article, it)
non-null일지라도 null이 들어올 경우를 처리를 안해주면은 예외케이스가 어떠한 경우에 발생했을 때 오류를 유발할 수 있다고 생각합니다! 널처리를 해주는게 더 좋다고 생각합니다!

2021-05-07 05:13 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
1. 맞습니다 ! 오류입니다 수정하겠습니다.
2. 맞습니다 ! 제가 신규해시태그일 경우/등록되어있을 경우 분기 로직을 수정해야겠네욥. !!

2021-05-07 05:17 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +        return Article(
toEntity 함수가 어떤 객체 타입에서 어떤 객체 타입으로 변환되는지 명시가 되지 않으면 여러개 타입으로 변환할 때는 어떻게 해야하나용? 예를 들어 저 함수는 articleRequest를 user객체를 사용하여 article객체를 만드는 함수입니다. articleRequest를 다른 entity로 바꾸는 함수가 추후에 필요할 경우 명명을 가져갈 방법을 정해야할거 같습니다! 

toArticle() 이라던지!! 엔티티라고 예를 들어 말씀하신거고 toArticle을 말씀하신건가용..?

2021-05-07 05:18 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
오호 넵!! 감사합니다!

2021-05-07 05:19 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
그러면 하나의 해시태그 만들경우 create, 해시태그 여러개 한번에 만들 경우 createAll 말씀하시는 거죵? 넵 알겠습니당!!

2021-05-07 05:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +                    articleHashtagService.createAllByHashtags(article, it)
코틀린에서는 nullable한 필드를 뒤에 ?를 붙여서 타입을 지정합니다. 그래서 주원이형이 말한 것처럼 non-null인 필드에는 null 자체가 허용이 안될 거에요.

즉, hashtags나 options가 null이라면 ArticleRequest를 생성하는 시점에서 아마 오류가 발생할거에요.
자바라면 null 체크를 하는게 맞는데 코틀린은 Null Safety를 통해 이를 해결하였습니다! 그래서 null 필드가 아니라면 절대 null이 들어올 수 없을 거에요.

2021-05-07 05:34 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +        return Article(
저도 최소한 `toArticle` 정도의 네이밍은 필요할 것 같아요! dto의 종류가 다양해지다 보면 dto의 이름만 보고 어떤 entity로 매핑이 가능하겠다는 것을 판단하기 힘들 것 같습니다. 그래서 어떤 클래스로 변경을 하는지는 명명으로 표현해주는게 좋을 것 같아요.

거기서 추가적으로 `WithUser`의 경우 붙여도 되고 안붙여도 되고..ㅎㅎㅎ IDE를 쓰면 어떤 파라미터를 받을 수 있는지를 알려주기 때문에 꼭 메서드 명에 명시할 필요는 없다고 생각이 듭니다.

2021-05-07 06:32 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +                    articleHashtagService.createAllByHashtags(article, it)
그렇군용!! 알겠습니다!

2021-05-07 09:13 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +        return Article(
Article 도메인 내부의 DTO에서 `ArticleRequest.toEntity` 와 같은 형태로 변경한다면 Article이 될 것이다 라고 예상할 수 있겠다 라고 생각해서 달았긴한데요! Entity로 변경한다는걸 써줄거라면 그냥 `toArticle`과 같이 엔티티명을 명시하는 것이 훨씬 가독성이 좋아보이긴 하네요!

2021-05-07 09:13 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
넵넵 !! 맞습니다!

2021-05-07 16:39 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleRequest.kt
> +        return Article(
toArticle로 하겠습니다!

2021-05-08 06:04 UTC, hungry-jay reviewed
2차 리뷰입니다 !! 많진 않고 한번씩 확인 부탁드려요~~

2021-05-08 06:04 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
`articleRequest.hashtags`가 empty인 경우에는 emptyList이기 때문에 forEach loop 자체가 실행되지 않습니다. 따라서, emptyList인지를 판별하는 조건문은 불필요해 보입니다 ! 또한 중복되는 코드를 아래처럼 줄일 수 있지 않을까 합니다 !

아, 그리고 위의 31번째 줄은 `hashtagService`에 "이미 존재하는 경우"에 또 추가해주는 것으로 보여, 제가 해당 로직에 `!`를 붙여주긴 했는데요. 혹시 이 로직이 원래 의도하시던 로직이 맞나요!?
```suggestion
        articleRequest.hashtags.forEach {
            if(!hashtagService.existsByName(it))
                hashtagService.create(it)
            articleHashtagService.createByHashtag(article, Hashtag(it))
        }
```

2021-05-08 06:04 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/option/domain/OptionRepository.kt
> +    fun findByTypeIn(types: List<OptionType>): List<Option>
In 조건에 해당하는 것들을 리스트로 뽑아내는 부분이기 때문에 `All`을 붙여주는건 어떨까요?
```suggestion
    fun findAllByTypeIn(types: List<OptionType>): List<Option>
```

2021-05-08 06:04 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +    fun findAllByNameIn(hashtagNameList: List<String>): List<Hashtag>
저번 리뷰에서도 언급했듯이 변수명에 타입을 유추할 수 있는 List와 같은 것을 지양하면 좋을 것 같습니다 ! `hashtagNames` 와 같은 형태로 사용한다면, 정말 만약에 추후에 타입이 변경되어야 하는 상황이 발생했을 때 해당 변수가 사용된 모든 곳에서 바꿔야 하는 상황을 방지할 수 있을 것 같습니다.!!

2021-05-08 06:04 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +        return hashtagList
이 부분 반영이 되지 않은 것 같습니다 ! https://github.com/dev-floor/untitled-server/pull/19#discussion_r625184936

2021-05-09 04:12 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/option/domain/OptionRepository.kt
> +    fun findByTypeIn(types: List<OptionType>): List<Option>
반영했습니다!

2021-05-09 04:13 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +    fun findAllByNameIn(hashtagNameList: List<String>): List<Hashtag>
죄송합니다ㅜ 요거 빼먹었네욥! 반영했습니다!

2021-05-09 04:15 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +        return hashtagList
넵 수정했습니당!

2021-05-09 04:19 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
1. forEach가 emptyList일 때 실행되지 않군요! 조건문 제거하겠습니다.
2. 네! 31번쨰줄 ! 붙이는게 맞습니다! 허나 32번째 줄에 articleHashtag를 생성할 때 Hashtag(it)은 해시태그를 새로 생성하여 사용하는 것 아닌가요? 기존에 해시태그가 있을 경우 hashtagId를 가져와야되는데 형님처럼하면 새로운 id가 생성되는거 아닌가용?? 여쭤봅니당!

2021-05-09 07:03 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
생각해보니까 그렇네요 !! 이미 저장되어있는 hashtag와 관계를 맺도록 해야하는데 그 부분을 미처 생각하지 못했네요 !
그러면 아래와 같이 코드를 변경할 수 있을거같아요 !

hashtag 변수를 새로 선언하지 않으려면 `(if ... else ...).let { ... }` 요렇게 묶어서 쓸수도 있긴한데 저 코드가 더 깔끔해보여서 저걸 추천해드립니다 !
원래 준형님이 작성하셨던 if else 코드나 중복을 줄인 제 코드 중 가독성이 좋다고 판단하시는거로 사용하시면 될 것 같아요~

```suggestion
        articleRequest.hashtags.forEach {
            val hashtag = if (hashtagService.existsByName(it))
                hashtagService.create(it)
            else hashtagService.showByName(it)
            articleHashtagService.createByHashtag(article, hashtag)
        }
```

2021-05-09 07:11 UTC, hungry-jay reviewed
린트 돌리다가 해당 부분을 발견해서 추가 리뷰 남깁니다!

2021-05-09 07:11 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
ktlint는 기본적으로 wildcard(*) import를 허용하지 않습니다!

그래서 제가 ktlint를 도입할 당시 `disabled-rules`에 wild-card-import를 추가해, 일부러 허용하도록 바꿨었는데,
준영이한테 "wildcard를 허용하지 않음으로써, import한 목록을 상세하게 볼수 있다"는 리뷰를 받아 허용하지 않도록 바꿨습니다.!
IDE 내부 설정을 통해 wildcard(*)를 사용하지 않도록 설정을 바꾸시고 변경 전단계로 변경해주심 될거같아요 !

2021-05-09 07:29 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        }
형님께 더 깔끔해보입니다 수정하겠습니당! 감사합니당!

2021-05-09 08:15 UTC, hungry-jay reviewed
리뷰가 거의 다 끝나가는 것 같습니다 !
이번 리뷰 내용은
1. 반영 안된 리뷰 반영
2. 변수명 (list ->  그냥 복수형) 변경
3. @Transactional 불필요한 곳 제거
입니다 !!

2021-05-09 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    }
repository의 메서드 내부적으로 트랜잭션 처리를 한다고 합니다 ! 따라서 서비스의 한 메소드 내에서 repository에 단 한번만 접근을 한다면 @transactional 어노테이션이 불필요 할 것 같아요 !

Ref) https://github.com/dev-floor/untitled-server/pull/20#discussion_r628177767
```suggestion

    fun create(article: Article): Article {
        return repository.save(article)
    }
```

2021-05-09 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +import org.springframework.web.bind.annotation.*
여기 리뷰 반영이 되지 않은 것 같습니다 !

2021-05-09 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
이 부분도 Transactional 어노테이션이 불필요할 것 같습니다!

2021-05-09 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
아마 여기서는 한 메서드 내부에서 repository에 loop를 통해 접근하기 때문에 Transactional이 필요할 것 같네요!!

아 그리고 여기 변수명도 hashtagList -> hashtags 로 변경하면 좋을 것 같습니다!!

2021-05-09 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
여기도 앞에서 처럼 Transactional이 불필요해보입니다!
```suggestion
    fun createByOption(article: Article, option: Option) {
        repository.save(ArticleOption(article, option))
    }
```

2021-05-09 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
여기도 repository에 한번만 접근하는 메서드는 Transactional 어노테이션을 제거하면 될것같아요!

2021-05-09 08:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
추가적으로 해당 로직을 saveAll 메서드를 사용하도록 해서 고치는 건 어떨까요?

2021-05-09 08:29 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +import org.springframework.web.bind.annotation.*
분명히 수정했는데... 다시하겠습니다 죄송합니다ㅜ

2021-05-09 09:55 UTC, hungry-jay approved these changes
개발, 리팩토링 고생하셨습니다 !!

2021-05-09 11:44 UTC, lxxjn0 requested changes
리뷰 달았어요!!! 확인 부탁드릴게요~~

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun create(articleRequest: ArticleRequest, user: User): Long {
이건 개인적인 제안이긴 한데, request가 하나만 들어오는 지금 같은 상황에선 변수명을 `articleRequest`에서 `request`같이 간단한 명명으로 사용하면 코드가 더 짧고 간결해져서 좋더라구요!! 
한 번 참고해보면 좋을 것 같아요!!!

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +    fun create(articleRequest: ArticleRequest, user: User): Long {
다른 부분들도요~~

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        return article.id
`articleRequest.options.isNotEmpty()` 로직을 request 내부에 하나의 메서드로 만들어 보는 건 어떨까요?
```kotlin
// ArticleRequest.kt
fun isOptionsNotEmpty(): Boolean = options.isNotEmpty()
```
이런 식으로?

getter로 프로퍼티를 가져와서 메서드를 실행하는 것 보다는 이렇게 하나의 메서드로 만들어서 request한테 시키는게 더 로직도 명확하고 보기 좋을 것 같아요!!

그리고 line 29번부터 34번까지 로직을 조금 개선하면 좋을 것 같은데, 이 부분은 파트에서 같이 이야기하면서 수정하면 좋을 것 같아요!!
약간 HashtagFacade에게 로직을 넘겨주는건 어떨까 싶은데 한번 이야기해보면 좋을 것 같아요!!

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
따로 리뷰를 남겼는지 기억이 잘 안나는데 이 부분을 saveAll로 로직을 개선하면 더 좋을 것 같아요!!

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
아 그리고 이 두 부분에서 느껴지는 건 굳이 article과 hashtag를 인자로 받아와서 내부에서 저장하기 보다는
```kotlin
fun create(articleHashtag: ArticleHashtag) {}

fun createAll(articleHashtags: List<ArticleHashtag>) {}
```

이렇게 하고 사용하는 쪽에서 articleHashtag를 만들어서 넘겨주도록 하는 건 어떨까요??

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
여기도 앞선 리뷰랑 마찬가지로의 생각입니다!!

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
여기도 `@Transactional` 어노테이션!!

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +    fun existsByName(hashtag: String): Boolean
메서드 사이에는 한 칸씩 띄우면 좋을 것 같아요!!

2021-05-09 11:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/application/OptionService.kt
> +    }
```suggestion
    fun showAllByOptionType(optionTexts: List<String>): List<Option> {
        val optionTypes = optionTexts.map { OptionType.from(it) }
        return repository.findAllByTypeIn(optionTypes)
    }
```

이런 식은 어떤가요?? 저는 개인적으로 인자로 넘어갈 때 라인이 너무 길어지지 않으면 이렇게 변수로 빼서 이름을 지어주고(여기선 optionTypes) 그걸 인자로 넘겨주면 코드가 더 잘 이해가고 좋더라구요!!

2021-05-09 14:41 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
아까 주원이형님 리뷰를 통해 create에 어노테이션 뺸건데 붙여??

2021-05-09 14:43 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        return article.id
1. 나는 인터넷검색하면서 하는데 코틀린으로 개발하는게 게터로 가져와서 메서드를 자유롭게 쓰는 거 같더라고 그래서 굳이 안만들었었는데 만들게!
2. 나도 해시태그 파사드로 로직을 넘기는 생각도 해봤었어! 뭔가 해시태그에 대한 로직이라 생각해서 여기서 처리하는게 맞나 싶었거든! 주원이형은 어떻게 생각하시나요!! @hungry-jay

2021-05-10 04:38 UTC, hungry-jay reviewed
리뷰 끝이라고 생각했ㅇ는데.. 오늘 새롭게 알게된 것이 있어 다시 리뷰남깁니다.!!
JPA와 트랜잭션 관련한 것입니다.!

2021-05-10 04:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
18-23번째 줄 메서드들 각각 `createAll`, `create` 로 수정 가능할 것 같아요 !
아 그리고 몰랐었는데 @Transactional 디폴트로 제공해주는 것은 JPA에서 기본으로 제공해주는 메서드만 이라고 하더라구요!
https://stackoverflow.com/questions/39827054/spring-jpa-repository-transactionality
모든 메소드에 Transaction 처리가 되는줄 알고 리뷰를 남겼었는데, 이 부분 참고해주시면 좋을거같아요 !

또한, JPA에서 제공하는 메소드 외에 Custom 메소드는 @Transactional 처리를 직접 해주어야 하는데, 이 때 두가지 방법이 있을거같아요 ! @Transactional 선언을 1. 해당 메소드를 사용하는 Service에서 하기 2. 메소드 선언부(Repository)에 하기
아무래도 두번째 방법을 채택하는 것이 메서드 사용부에 각각 @Transactional 선언하는 방법보다 좋아보입니다!

2021-05-10 04:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
> +    }
이 부분도 메서드명 변경이 필요해보입니다!

2021-05-10 04:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    }
앞서 말씀드렸듯 커스텀 메소드라면 여기도 @Transactional을 Repository에 선언하는 것이 어떨까요?

2021-05-10 04:55 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
아 그런데 제 코드 고치면서 생각해보니, 클래스에 선언해버리면 read-only 인 것과 write가 필요한 곳을 구분짓는 것이 안될 것 같네요. 저의 경우에는 결국 메서드 각각에 Transactional 선언을 해두긴 했는데, 이 부분은 논의가 필요해보입니다 !

2021-05-10 06:06 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
`@Transactional`이 오버라이딩이 가능해서 repository interface에 `@Transactional` 어노테이션을 선언하고, 내부 메서드 중 readOnly인 메서드에 대해서는 따로 어노테이션을 오버라이드 하는 방법도 있을 것 같네요!

2021-05-10 06:24 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +    }
아 오버라이딩 이용하는게 깔끔할거같긴하네요 !

2021-05-13 04:33 UTC, hungry-jay reviewed
고생하셨습니다 !
hashtagFacade에서 의논하고 싶은 부분이 딱 하나 있습니다. 확인부탁드려요~

2021-05-13 04:33 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        articleHashtagService.createAll(hashtags.map { ArticleHashtag(article, it) })
Hashtag를 생성(혹은 조회)하고 나서는 항상 ArticleHashtag도 함께 생성해야 할 것 같은데,
여기 혹시 이렇게 바꿔 두 로직을 HashtagFacade 내부의 한 메서드에 묶어놓으면 어떨까요?

```suggestion
        request.hashtags.forEach { hashtagFacade.createByName(article, it) }
```

아래는 HashtagFacade에서의 `createByName` 입니다.
```
    @Transactional
    fun createByName(article: Article, hashtagName: String) {
        val hashtag = if (!hashtagService.existsByName(hashtagName))
            hashtagService.create(Hashtag(hashtagName))
        else hashtagService.showByName(hashtagName)
        articleHashtagService.create(ArticleHashtag(article, hashtag))
    }
```

2021-05-13 04:33 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        articleHashtagService.createAll(hashtags.map { ArticleHashtag(article, it) })
그리고 해당 메소드에서 항상 Hashtag를 create하지는 않는데, 혹시 더 좋은 메서드명 없을까요?

2021-05-15 08:30 UTC, lxxjn0 requested changes
마지막 리뷴데 이거 나머지만 한번 확인해보고 마무리 해도 될 것 같ㅇ요!!

2021-05-15 08:30 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/domain/OptionRepository.kt
> +}
여기 공백이 하나 들어가있어요

2021-05-15 08:30 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagFacade.kt
> +    }
이 로직이  service로 가는건 어때?

2021-05-15 08:30 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtagRepository.kt
>  }
여기도 의미없는 공백이 추가된 듯?

2021-05-15 08:30 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteRepository.kt
>  }
여기도, 이거 린트 때문인가? 여기도 공백 추가됨

2021-05-15 08:30 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
> +        articleHashtagService.createAll(hashtags.map { ArticleHashtag(article, it) })
이건 나도 계속 고민이네.. 어떻게 하는게 더 좋을지..

2021-05-16 07:34 UTC, lxxjn0 approved these changes

2021-05-16 07:34 UTC, merged