feat(board): 게시판(게시글 목록) 조회 구현
dev-floor/untitled-server pull request #20
Opened 2021-05-03 15:00 UTC by hungry-jay

### 상세 내용
* 스크린 구성이 안되었기 때문에, 게시판 조회 중 게시글 목록에 대한 부분만 구현했습니다. (feature/6)

closes #17

2021-05-07 12:44 UTC, lxxjn0 requested changes
아직 명세가 덜 정해진 부분이 있어서 코드 전체적으로 피드백 줄 부분은 적었던 거 같아!
몇가지 코멘트 남긴 부분들만 한 번 확인해줘!!

2021-05-07 12:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
이 부분은 왜 `showById`라고 고친거야??

그 저번에 내가 말한 그냥 id로 적어도 되지 않을까? 라는 부분은 service 레이어 정도라고 생각했거든.
service 레이어는 해당 도메인에 대한 정보만 넘어가는데 facade의 경우엔 article 도메인이 아닌 다른 도메인의 정보도 충분히 넘어갈 수 있는 부분이라서 `showByArticleId`라고 명시하는게 좀 더 나을 것 같아!

2021-05-07 12:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    }
이 부분은 저번에 우리 한 줄로 해결 안되면 블록바디로 바꾸자 해서 이렇게 바꾼거 맞지?
근데 왜 또 이거 바뀐거 보니까 이전이 더 가독성이 좋아보이지.... ㅋㅋㅋㅋㅋㅋㅋ

그냥 이 부분 꼭 포맷을 정하지 말고 보기에 따라 가독성이 더 좋아보이는 형식으로 쓰면 안되나?
우리가 너무 A부터 Z까지 정하고 하는거 같어..
뭔가 이 부분은 난 이전 코드가 더 가독성이 좋아보이는데 다른 사람들 생각은 어때?? ㅋㅋㅋㅋㅋㅋㅋ

2021-05-07 12:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
>      @Transactional(readOnly = true)
이거 `@Transactional` 굳이 안부쳐도 될 것 같아.
이번에 팀에서 내가 이렇게 사용하다가 피드백을 받았는데 repository를 여러 번 호출하는 경우에 이걸 붙이는 게 의미가 있는데 지금처럼 한 번만 호출하는 경우는 어차피 이미 repository의 메서드에 `@Tranactional`이 붙어있어서 굳이 붙일 필요가 없다는 이유였어.

2021-05-07 12:44 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        val articles = articleService.showAll().map { article ->
너무 map의 인자로 많은 코드가 넘어가는 것 같아. 그리고 오히려 인덴트를 파악하기도 힘들고 코드가 너무 길어지는 느낌이야.
이런 경우에 차라리 함수를 분리해보는 건 어떨까??

2021-05-07 18:20 UTC, JoonBro requested changes
아직 정해지지 않은 부분들이 많은데 임시로 구현하시느라 고생 많으셨습니다!

2021-05-07 18:20 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
저도 준영이말에 찬성합니다!

2021-05-07 18:20 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    }
가독성이라는게 주관적인거라 팀원마다 다르게 되면 통일성이 부분부분 없어질 수도 있을거 같은데... 통일성이 없어도 괜찮다면 나도 유동적으로 가져가는게 좋다고 생각합니다. 

이 경우는 나도 변경전이 가독성이 더 좋아보이네.. 한줄로 해결안되면이 아니라 저럴경우 그냥 블록바디 말고 =를 쓰자고 정해도 괜찮을거 같기도 하고!!

2021-05-07 18:20 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    fun showById(): BoardResponse {
showById()이면 parameter로 id를 받아야 하는거 아닌가용??

2021-05-07 18:20 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        val articles = articleService.showAll().map { article ->
그리고 게시판에 해당하는 article만 조회해서 보여줘야하니까 showAll()보다는 showByBoardId()? 처럼 해야되는 거 아닌가용?? 위에 리뷰와 동일합니당. 제가 로직을 잘못 이해하고 있는건지 여쭤보고 싶습니다!

2021-05-08 03:34 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
맞아요 여기는 전에 리뷰에서 이야기했던 부분을 참고하긴 했어요! https://github.com/dev-floor/untitled-server/pull/13#discussion_r618494806
위의 글에서 이해한 바는, "Article이라는 패키지 내부 ArticleController에서 Id라고 명시한다면 (여러 Id들이 존재할지라도) Id가 다른 패키지의 Id와 헷갈려서는 안된다는 것" 인데
이 관점에서 보면, "ArticleFacade 또한 여러 서비스가 모여있는 곳이긴 할지라도 Article 패키지에 속해있는것이니까 여기서 쓰이는 Id는 Article의 Id임을 헷갈려서는 안된다"가 되는 것 아닌가요?
또한, 쓰임 측면에서도 `ArticleFacade.showById(id)` 이와 같은 형태로 쓰인다면 여기서 사용되는 Id가 어떠한 Id에 해당하는지는 보다 자명해질 것이라고 생각했습니다

2021-05-08 03:38 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    }
여기는 또 얘기 꺼낼까말까 했다가 일단 정한대로 하긴 했는데요!
그냥 가독성을 해치지 않는 선에서 자유롭게 사용하면 될 것 같아요. 저도 코틀린 사용하는 사람들과 의견도 나누고 했었는데, 사람마다 너무 달라서 답은 없다고 생각하구요.
다만 해당 부분에 대해 가독성이 좋지 않다고 생각하는 부분에 대해서만 리뷰 시 의견을 나누면 좋을 것 같아요

2021-05-08 03:51 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        val articles = articleService.showAll().map { article ->
> 너무 map의 인자로 많은 코드가 넘어가는 것 같아. 그리고 오히려 인덴트를 파악하기도 힘들고 코드가 너무 길어지는 느낌이야.
이런 경우에 차라리 함수를 분리해보는 건 어떨까??
`List<ArticleResponse>` 를 반환하는 메서드를 BoardFacade 내에 별도로 구현하는게 좋겠다는 말인거지 !?

2021-05-08 03:54 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        val articles = articleService.showAll().map { article ->
> 그리고 게시판에 해당하는 article만 조회해서 보여줘야하니까 showAll()보다는 showByBoardId()? 처럼 해야되는 거 아닌가용?? 위에 리뷰와 동일합니당. 제가 로직을 잘못 이해하고 있는건지 여쭤보고 싶습니다!

맞아요.! 이건 저번 미팅때 말했듯 현재 Board에 대한 entity가 아직 없어서 Article 목록 조회에 대한 것만 굉장히 애매하게만 구현해놓은 상태이구요, 때문에 merge하지 않고 로컬 브랜치로 놓았다가 나중에 다 구현되면 PR하는게 어떨까 했던 이유가 이것입니다 !

2021-05-08 03:54 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    fun showById(): BoardResponse {
> 맞아요.! 이건 저번 미팅때 말했듯 현재 Board에 대한 entity가 아직 없어서 Article 목록 조회에 대한 것만 굉장히 애매하게만 구현해놓은 상태이구요, 때문에 merge하지 않고 로컬 브랜치로 놓았다가 나중에 다 구현되면 PR하는게 어떨까 했던 이유가 이것입니다 !

이 부분 또한 다른 코멘트에서 말했듯 아직 엔티티가 없어서 적당히 틀만 구현해놓은 것입니다 ! 엔티티 구성 이후 추가 예정이에요

2021-05-08 06:09 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
>      @Transactional(readOnly = true)
이부분 찾아봤는데 !! Repository의 메서드에 디폴트로 transactional하게 처리를 해주는구나..!
그러면 현재 내가 작성한 Service 부분의 대부분은 repository를 단 한번 호출하도록 되어있는데 이 부분들에 대해서는 별도의 `@Transactional` 어노테이션이 필요 없는게 되는거지 !?

2021-05-08 10:18 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    }
넵!! 저는 확실히 수정 전이 더 가독성이 좋아 보이긴 해요!

2021-05-08 10:26 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
나도 한번 다시 고민을 해봤거든. 우선 controller나 service에서 `articleId`가 아닌 `id`가 나을 것 같다고 말한 이유를 생각해보니까
1. controller의 경우 다양한 도메인의 `id`가 들어올 수 있지만(articleId나 commentId와 같이) 메서드를 직접 사용하는 곳은 없다. 즉, 명명으로 사용 시 혼란이 오는 상황이 없다보니 간략하게 가져가는게 좋다고 생각했던 것 같고, 그런 관점에서 도메인의 `id`의 경우 간단한게 `id`로 가져가는게 좋을 것 같음.
2. service의 경우 딱 해당 도메인에 대한 정보만 전달되므로 Article의 경우 `id`는 무조건 `ArticleId`이기 때문에 따로 `ArticleId`라고 명시하지 않아도 된다고 생각.

이런 이유로 아마 두 상황에 대해서는 id라고 해도 충분히 이해가 갈 수 있다고 생각했어.

ArticleFacade의 경우 해당 객체의 메서드들에 전달될 수 있는 `id`의 종류도 많고, 직접 메서드를 사용하는 상황이 있다보니 메서드 명에서 최대한 혼동을 줄이면 좋겠다라는 생각으로 명시하는게 어떨까 생각했던 것 같어.
근데 또 쓰다보니 해당 도메인에 대한 `id`는 굳이 명시하지 않아도 될 것 같기도 하고... 고민되네..

일단은 내가 왜 두 상황에 대해서 다르게 말했는지는 위의 이유들이었어. 메서드 명이나 코드는 항상 상황에 따라서 최대한 적절하게 작성하는게 좋다고 생각하고 그러다보니 두 상황에 따라 다르게 제안을 했던 것 같네.

뭐 그렇다고 Id라고 사용하는걸 반대한다는 것도 아니고, 둘 다 상관은 없을 것 같어.

한번 읽어보고 형 생각도 정리해보고 결정하면 좋을 듯?

2021-05-08 10:27 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
>      @Transactional(readOnly = true)
엉엉, 트랜잭션을 붙이는 이유가 아토믹하게 로직을 처리하고자 하는 거잖아. 그렇다보니 다양한 repository를 조회하는 상황에 대해서 사용하는게 적절할 것 같어!!

2021-05-08 10:28 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        val articles = articleService.showAll().map { article ->
일단 한번 좀 더 코드를 간단하게 수정해보고 같이 피드백 해보면 될 듯?

2021-05-09 04:40 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
articleFacade내에서 showById면 article을 id를 통해 보여준다자나?? 근데 article과 관련된 articleOption, articleHashtag같은 경우도 facade에서 다뤄야 하는거 아니야? 그러면 showArticle뿐만아니라 , showArticleOption과 같은 것들이 있을 수 있을텐데 그러면 각각 객체별로 id는 정해져있으니까 showArticleById는 어떨까요????

2021-05-09 04:41 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    }
넵 그럼 자유롭게 사용하는걸로!!

2021-05-09 07:43 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
> ArticleFacade의 경우 해당 객체의 메서드들에 전달될 수 있는 id의 종류도 많고, 직접 메서드를 사용하는 상황이 있다보니 메서드 명에서 최대한 혼동을 줄이면 좋겠다라는 생각으로 명시하는게 어떨까 생각했던 것 같어.
근데 또 쓰다보니 해당 도메인에 대한 id는 굳이 명시하지 않아도 될 것 같기도 하고... 고민되네..

흠.. 아 그런데 생각해보면, controller던 facade던 해당 도메인외의 Id도 사용되는건 마찬가지 아닌가 !? (Comment controller와 facade에서 ArticleId가 사용되는 것처럼) ->> 그렇다면 service는 그냥 Id로 사용해도 되는데, facade와 controller는 둘다 도메인을 명시하던 안하던, 통일되게 가는게 좋지 않을까!?

그러면 저러한 혼동을 줄 수 있는 곳(controller, facade)에서는 둘다 도메인을 명시하는 것이 어떨까!? 🤔

2021-05-09 07:45 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
> article과 관련된 articleOption, articleHashtag같은 경우도 facade에서 다뤄야 하는거 아니야?

흠... 얘네에 대한 비즈니스 로직들은 (만약 여러 서비스를 사용해야하고, 따라서 facade에서 처리해야한다면) articleOptionFacade 혹은 articleHashtagFacade를 따로 구성해야 하는 것 아닌가요 !? 아님 articleFacade에서 다뤄야하는지.. 좀 혼동이 오네요 ㅠ

`showArticleById` vs `showById` 이 부분은 Crudrepository에서 사용하는 네이밍을 따라가다보니까 후자를 택하게된거같아요 ! 그 편이 혼동이 없고 좋을 것 같아서 !?!?

2021-05-09 07:47 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
> 그러면 저러한 혼동을 줄 수 있는 곳(controller, facade)에서는 둘다 도메인을 명시하는 것이 어떨까!? 🤔

아 근데 이렇게 남기고 코드를 보니까, controller에서 도메인을 굳이 명시하는게 좀.. 굳이?? 라는 생각이 드네요 ㅠ 흠..

2021-05-09 08:19 UTC, hungry-jay commented
아 이번 리뷰 반영하면서 생각을 해봤는데요, Article목록 조회하는 부분이 BoardFacade에 있어야하는가 고민이 됩니다.!
게시글 상세조회시 Comment에 따로 API call을 하는 것 처럼, Board 조회 시 Article에 API call을 날리는 것이 맞아보이기도 하구요..

아마 Board 스크린이 구성되면 저희끼리 이야기를 해야할 것 같고, 그 과정에서 제가 개발한 부분에서 많은 리팩토링이 필요해보입니다!
아직 스크린 구성 전이니, 일단은 Boardfacade 내부에 구성하는 것으로 하고, 변경하는 것이 좋아보이는데 이 점에 대해 어떻게 생각하시나요!!??
@JoonBro 
@lxxjn0

2021-05-10 06:18 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
>          val article = articleService.showById(articleId)
아 controller의 경우 말한 것처럼 다른 도메인의 id가 넘어오는 건 맞어, 그런데 해당 메서드를 우리가 코드상에서 호출하는 부분이 없으니까 따로 붙이지 않아도 되지 않을까 생각했어.
우선 service에는 확실하게 붙이지 않아도 된다고 생각하고 controller나 facade의 경우는 아직도 고민이 되긴 하네.. 이건 같이 애기를 해봐야지 좀 더 명확해지긴 하겠다.

2021-05-11 06:20 UTC, JoonBro requested changes
Board 조회 시 Article에 API call을 날리는 것이 맞아보이기도 하구요..
-> 요 말씀이 Board Controller에서 받아서 articleFacade로 콜하자는 말씀이신거죵???

2021-05-11 06:20 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    private fun showArticles(): List<ArticlesResponse> {
제가 확실하진 않은데 이 함수 내부에 조회하는 함수가 여러개 존재할 때 transactional 처리가 필요한 부분 아닌가용??

2021-05-11 06:20 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        return articleService.showAll().map { article ->
요롷게도 쓸수 있군욥!! 하나 배워갑니당 !!

2021-05-11 07:48 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    private fun showArticles(): List<ArticlesResponse> {
해당 메서드를 호출하는 `showByBoardId` 에 Transaction이 적용되어 있기 때문에, 이 메소드에서 호출하는 다른 부분들 또한 트랜젝션이 적용되어있는 프록시 안에서 수행된다고 하더라구요 !

또한, 이처럼 내부 메서드를 호출하는 경우에는 Transactional이 적용된 프록시를 호출 하는게 아니라 그냥 내부 메서드를 불러오는거라 @transactional이 붙어있어도 적용자체가 되지 않는다고 합니다.!!

2021-05-11 09:46 UTC, lxxjn0 requested changes
우선은 메서드 분리 관련 부분에 대해서 상세하게 피드백 추가했어요!!
이거 피드백 한 번 참고해서 적용해보시고 마지막으로 리뷰 한번 하고 마무리 해도 될 것 같아요!!!

2021-05-11 09:46 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
제가 의도한 메서드 분리는 이런 방향은 아니긴 했는데 ㅋㅋㅋㅋ 메서드가 최대한 하나의 일만 하도록 작성하는게 좋을 것 같은데 `showArticles` 메서드를 보면 그냥 로직의 위치만 바꾼 정도로 메서드를 나눈 것 같아요.

이렇게 수정하면 이전 코드에 비해서 딱히 잘 코드가 분리됐다고 보기 어려울 것 같아서 일단 제가 한 번 코드를 작성해봤는데 한번 참고 부탁드릴게요!!

![image](https://user-images.githubusercontent.com/48052622/117795084-ced08300-b288-11eb-8fcd-933004b3b792.png)

AriclesResponse는 명명이 너무 헛갈리는 것 같아서 ArticleFeedResponse가 어떨까 싶네요.
그리고 추가적으로 코드들을 조금 분산시켜서 적절한 클래스에 메서드를 구현하였는데 한 번 참고해보시면 좋을 것 같아요!!

사진은 클릭하면 크게 볼 수 있습니다. 코드도 아래 첨부해둘게요!!

```kotlin
// BoardFacade.kt
@Service
class BoardFacade(
    private val articleService: ArticleService,
    private val articleFavoriteService: ArticleFavoriteService,
    private val articleOptionService: ArticleOptionService
) {
    @Transactional(readOnly = true)
    fun showByBoardId(): BoardResponse {
        val articles = articleService.showAll()
            .map { createArticleFeedResponse(it) }

        return BoardResponse(
            articles = articles
        )
    }

    private fun createArticleFeedResponse(it: Article): ArticleFeedResponse {
        val articleFavorites = articleFavoriteService.showAllByArticle(it)
        val options = articleOptionService.showAllByArticle(it)

        return ArticleFeedResponse(
            options = options,
            article = it,
            articleFavorites = articleFavorites
        )
    }
}
```

```kotlin
// ArticleFavorite.kt
@Entity
@Table(name = "favorites")
class ArticleFavorite(
    article: Article,
    user: User,
    type: ArticleFavoriteType
) {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "favorite_id")
    val id: Long = 0

    @ManyToOne
    @JoinColumn(name = "article_id")
    val article: Article = article

    @ManyToOne
    @JoinColumn(name = "user_id")
    val user: User = user

    @Column(name = "favorite_type")
    @Enumerated(value = EnumType.STRING)
    var type: ArticleFavoriteType = type

    fun matchType(type: ArticleFavoriteType): Boolean = this.type == type
}
```

```kotlin
// ArticleFeedResponse.kt
data class ArticleFeedResponse(
    val id: Long,

    val options: List<String>,

    val title: String? = null,

    val anonymous: Boolean,

    val authorName: String,

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
    val createdDate: LocalDateTime,

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
    val modifiedDate: LocalDateTime,

    val content: String,

    val favorites: Long,

    val wonders: Long,

    val clips: Long,
) {
    constructor(
        options: List<ArticleOption>,
        article: Article,
        articleFavorites: List<ArticleFavorite>
    ) : this(
        id = article.id,
        options = options.map { it.option.type.text },
        title = article.title,
        anonymous = article.anonymous,
        authorName = article.author.nickname,
        createdDate = article.createdDate,
        modifiedDate = article.modifiedDate,
        content = article.sliceContentByLength(CONTENT_MAX_LENGTH),
        favorites = articleFavorites.count { it.matchType(FAVORITE) }.toLong(),
        wonders = articleFavorites.count { it.matchType(WONDER) }.toLong(),
        clips = articleFavorites.count { it.matchType(CLIP) }.toLong(),
    )

    companion object {
        private const val CONTENT_MAX_LENGTH: Long = 300
    }
}
```

```kotlin
// Article.kt
@Entity
@Table(name = "articles")
class Article(
    title: String?,
    anonymous: Boolean,
    content: String,
    author: User,
) : BaseEntity() {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "article_id")
    val id: Long = 0

    @Column(name = "title")
    var title: String? = title
        protected set

    @Column(name = "anonymous")
    var anonymous: Boolean = anonymous
        protected set

    @Column(name = "content")
    var content: String = content
        protected set

    @ManyToOne
    @JoinColumn(name = "author_id")
    val author: User = author

    fun sliceContentByLength(length: Long): String = content.substring(length.toInt())
}
```

2021-05-12 02:07 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
`articlesResponse` 네이밍에 대해 생각을 안해본건 아닌데, 해당 이름으로 정한 이유는 다른 곳에서도 복수형의 표현은 `hashtags` `options`와 같이 일반적인 영어에서의 복수형처럼 -s, -es 를 사용하고 있기 때문이었어. 당장 article 리스트를 불러오는 곳에서는 feed라는 네이밍을 한다면 헷갈리는 것도 줄고, 어울리기도 한다고 생각해.!

그런데 생각해봐야할 점 중 하나가, 추후에 새롭게 생길 수 있는 '다른 리스트를 불러와야 하는 곳'에서는 다른 네이밍이 어울릴 수도 있고, 그러다 보면 나중에는 네이밍때문에 오히려 복잡해질 수도 있지 않을까?? 차라리 가독성을 높이고 그 때마다 새로운 네이밍을 하는게 좋으려나?

2021-05-12 02:14 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
`ArticlesResponse`에서 compannion object로 글자수 300 제한을 두는것도 생각을 해보긴 했는데 , 퍼사드에 둔 이유는 해당 부분이 어디까지나 (게시판에서 게시글 목록을 불러오는) 비즈니스 로직에 해당되는 것이라고 생각해서야. 만약 추후에 "유저가 본인이 쓴 글 목록"을 불러와야 하는 부분이 생겼을 때 만약 전달되는 DTO가 같다면, 해당 DTO를 재사용해도 될 것 같은데 그 때는 글자 제한이 300자가 아닐수도 있는거잖아 !?

2021-05-12 02:22 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
DTO를 contructor로 정리하는건, 너코드 봤을 때 profile을 사용하는 곳이 두 군데인가 그랬던거로 기억하는데, 그래서 좋아보이긴 했었어 ! 그래서 내꺼도 적용할까 하다보니까 어차피 한군데에서만 사용하고 DTO에서 맵핑하나, 비즈니스 로직에서 맵핑하나 그게 그거다라고 생각했는데 저건 확실히 contructor로 묶어놓는게 재사용할때도 좋을거같긴하네!

2021-05-12 03:26 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
`matchType` 메서드를 사용하는것도 불필요한 메서드를 줄일수있고 좋을거같다 !

2021-05-12 03:31 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
`sliceContentByLength` 이 부분 또한, 원래 DTO에 구현을 해놓기는 했었는데 다시 facade로 뺀 이유가 윗윗윗에서 300자 제한 로직을 DTO에 두지 않은거와 같은 맥락이야. 300자로 slice하는 로직자체가 '게시물 목록을 보기 위한 비즈니스 로직' 이라고 생각해서, 물론 그 로직을 다른 곳에 두면 깔끔해보이고 좋지만, 비즈니스 로직은 어디까지나 비즈니스 로직을 수행하는 곳에 있어야 할 것 같아서

2021-05-12 08:24 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +    }
위에 리뷰 순서대로 번호 매겨서 답변 달아둘게!

#### 1번 코멘트
일단 내가 생각하기에 `ArticlesResponse` 이름을 생각해보면 response 내부에 복수형 List를 가지고 있겠구나 라는 생각이 들거든. 그런데 내부에는 게시글 목록 리스트에 사용되는 **단 건**들에 대한 정보잖아. 이런 관점에서 response에 복수형을 붙여서 사용하면 너무 헛갈릴 것 같아.

그리고 이후에도 다양한 곳에서 다른 네이밍이 필요할 건데 지금 `ArticleResponse`, `ArticlesResponse` 이렇게 사용하면 그 다음 상황에서 이름은 어떤 기준으로 지어야 할까?
내가 생각하기엔 API를 사용하는 곳에 전달하는 데이터의 목적을 고려해서 이름을 지으면 더 좋을 것 같아. 그러면 당연히 그 때마다 새로운 네이밍을 가져가게 될 것 같고? 네이밍을 통일감 있게 가져가는 것보다는 각 상황에 맞는 적절한 이름을 주는게 더 장점이 많을 것 같다고 생각해

#### 2번 코멘트
이런 가정은 너무 미래 지향적인 가정인거 같아. 그렇다면 만약 해당 DTO를 사용하는 모든 곳에서 항상 300자 이하로 게시글을 잘라야 하는데, 그럼 서비스의 메서드마다 매번 300자가 넘는지 판단하고 처리하는 로직을 가져야 할까? 이렇게 가정하면 또 내가 작성한 코드가 적절한 걸꺼잖아.

난 개인적으로 지금 해당하는 코드가 어디에 있는지 더 적절한가를 고려해서 짜는게 더 맞다라고 생각해. 물론 어느정도 예상 가능한 범위 내에서는 확장성을 고려하면 좋지, 그런데 지금은 우리가 기획적으로도 전혀 가정되어 있지 않은 사실에 대한 확장성을 고려하고 있는데, 개인적으로 이건 오버엔지니어링에 가깝지 않은가 싶어.

그리고 사실 300자 이상이면 ...으로 보여준다, 안 보여준다가 비즈니스 로직이라고 생각할 수도 있지만, 난 오히려 뷰에 대한 로직에 가깝다고 생각하거든.
비즈니스 로직은 데이터에 대한 검증이나 판단 등을 통해 로직을 가져가는 것이라고 생각하는데 프론트에 300자까지면 보내준다? 이건 비즈니스 로직보다는 데이터를 전달하는 계층에서 처리해도 충분히 가능한 정보라고 생각하고, 사실 이걸 굳이 백에서 처리안하고 전체 데이터를 넘겨줘도 프론트에서 처리할 수 있잖아. 단지 우리가 성능적, 편의적인 부분을 위해서 처리해서 보내주는 거니까 해당 데이터를 300자까지 잘라서 보내주는 건 충분히 DTO가 가져도 될 만한 로직인 것 같아.

추가적으로 내가 생각하는 비즈니스 로직을 예로 들면 사용자가 게시글을 생성하는 로직을 생각해볼게.

- 게시글을 생성할 때 Option을 설정하고 Hashtag를 작성할 수 있다.
- Option은 기존에 존재하는 Option만 가능하다. 만약 그렇지 않다면 예외를 발생시켜야 한다.
- Hashtag는 기존에 존재하는 내용일 경우 가져다가 쓰고, 만약 존재하지 않는다면 새롭게 생성한 후, 생성된 Hashtag를 가져다 쓴다

이렇게 하나의 로직이 실행되기 위해서 필요한 비즈니스적인 과정들이 비즈니스 로직이라고 생각하고, 게시글을 조회하고 전달할 때 데이터를 처리하는 건 데이터를 저장하거나 변경하는 과정이 아니라 이미 조회가 완료된 데이터를 프론트에 전달할 때 가공하는 작업에 가까우니까 비즈니스 로직보다는 뷰 로직에 가깝다고 생각해.

#### 5번 코멘트
`sliceContentByLenght` 메서드에 대해서 해당 로직의 재사용성을 고려하면 오히려 Article에 있는게 더 맞지 않을까? 매번 Article 객체를 가져와야지만 가능한 로직이지 않아?

객체 지향적인 설계는 이전에 말했던 것처럼 메시지를 보내라잖아. `게시글의 길이를 n만큼 해서 자른다`라는 로직을 '게시글, 너 콘텐츠 가져와봐. 그리고 전달해주면 콘텐츠를 facade에서 내가 맞게 잘라야지'라기 보다는 '게시글, 나 이 길이만큼의 콘텐츠가 필요한데 너가 잘라서 나한테 보내줘' 라고 하는게 좀 더 객체 지향적인 설계 아닐까?

그리고 도메인 객체인 Article의 content 길이를 특정한 길이만큼 자른다는 비즈니스 로직이라기보단 도메인 로직이라고 보는게 더 맞는 것 같아.

DTO를 위한 로직이라면 `sliceContentByThreeHundredLenght()` 이렇게 짜야지 DTO에 의존적인 로직인거고, 우리가 특정한 길이를 전달해서 그에 맞는 길이의 content를 반환해 달라고 했는데 이게 단순히 DTO를 위한 로직이라고 볼 수 있을까?

객체 지향이 객체 중심적인 설계인데 article.getConent로 값을 가져와서 외부에서 처리하는 건 객체 지향적인 설계일까? 최대한 객체들 각각에 로직을 응집도있게 설계하고, 그래야지 더 재사용성이 높아지는데 만약 이 로직을 facade에 둔다면 해당 로직을 사용하는 곳이 facade가 아닌 다른 곳이 되는 경우에 매번 동일한 코드가 반복적으로 구현이 되어야해. 이건 응집도 있는 구현이 아니기 때문에 발생하는 문제일거고.

service가 모든 비즈니스적인 로직을 다 가지고 있는다가 정답은 아니라고 생각해. 그리고 비즈니스 로직과 도메인 로직과 뷰 로직은 각기 다르다고 생각하고.
특정한 행위(게시글 생성)을 처리하는 데 있어서 부가적으로 필요한 과정들(옵션을 검증하거나 해시태그를 검증하거나 등등..)
추가적인 예시로 댓글을 수정할 때 로그인한 사용자가 댓글의 생성자가 맞는 지 판단하고 이게 익명이라면 수정이 불가능하고 익명이 아니라면 수정이 가능! 이런게 비즈니스적인 로직이라고 생각하고, 글의 길이를 자른다, 뭐 입력받은 문자열 OptionName에 맞는 옵션을 찾는다, 이런 건 비즈니스가 바뀐다고 바뀌는 로직이 아니잖아. 그렇기 때문에 optionType이라는 도메인 객체에 from과 같은 메서드를 둔 거고. 이런 로직은 도메인 로직이라고 생각하는게 난 맞을 것 같아.

일단 위 코멘트에 대한 내 생각을 정리해서 달아봤는데 혹시 보고 다른 의견 있으면 다시 물어봐줘!!

2021-05-15 09:24 UTC, lxxjn0 approved these changes
이거 두 부분만 한번 확인 부탁드려요!!

2021-05-15 09:24 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        )
이거 파라미터 하나밖에 없으면 따로 named arguments로 처리 안해도 될 듯?

2021-05-15 09:24 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
이거 그냥 저번에 내가 재안한 코드처럼 content.substring(length.toInt()) 이런 식으로 써도 되지 않을까? 어차피 300길이 이하면 원래 원본이 반환되고 아니면 잘라서 반환할거니까?

2021-05-15 09:29 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        )
여기는 게시판 스크린 구성 이후 어차피 DTO 부분 추가되는거 아냐??? 여기는 어차피 수정해야할 부분이니까 일단 냅두자

2021-05-15 09:32 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
이렇게하면 런타임에러발생하던데?? 파라미터 하나전달하면 startIndex에 맵핑되고, 300 길이 미만인 경우에는 out of range 될거야 아마!

2021-05-15 10:02 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        )
아 사실 이걸 BoardResponse로도 쓸지도 잘 모르긴 하네. 그럼 그냥 일단 List<ArticleResponse>를 반환타입으로 바꾸는건 어때?

2021-05-15 10:05 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
아 그건 내가 실행을 안해봐서 몰랐네!! 아 그래고 else문을 그냥 if문에서 early return으로 바꾸는건 어떨까?
https://jamie95.tistory.com/99 이거 링크 한번 참고해보면 좋을듯!!

2021-05-15 10:21 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardFacade.kt
> +        )
그냥 이 PR에 대한 리뷰는 좀 뒤로 미루는게 어때?
일단 board 스크린이 정해진게 없는데 DTO를 따로 만든건 필요할 것 같아서였어.
그런데 말그대로 확실한게 없으니까 이 부분에 대한 리뷰와 리팩토링이 비용 낭비가 아닌가 하는 생각이 들어.! 그래서 처음에 내가 게시판 스크린 구성 끝나고 PR올리겠다고 이야기한거였고. 나중에 게시판 구성 끝나고 이부분 코드작업을 다시 하는게 효율적일거같은데 어떨까?

2021-05-15 10:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
if else 분기가 복잡하면 해당 패턴으로 작성하는게 의미가 있을것같은데 이 부분에서 굳이 필요할까??
일단 여긴 삼항연산자로 짜려고 했는데 코틀린에서는 삼항연산자가 없고 대신 return if A else B를 사용하라고 하더라고!
그런데 여기를 early return으로 변경하면서 얻는 이점이 있을까?

2021-05-15 10:47 UTC, lxxjn0 approved these changes
코멘트 한번 확인해주세요!

2021-05-15 10:47 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
if else가 안티패턴이 발생하기 쉬운 구조래. 그래서 최대한 if else를 쓰기보단 if문이랑 리턴문으로 해결하고 if else가 많아지면 아예 코드 구조를 개선해야 하는 시점이라고 생각하면 될듯?

2021-05-15 10:47 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
3항 연산자도 난 이해하기 어려워서 안쓰는게 좋다고 생각하고 내가 말한 구조는
```kotlin
if (content.length > length) {
    return content.substring(0, length + 1)
}
return content
```

이렇게? 그리고 라이브러리 함수같은거에 굳이 named arguments 붙일 필요는 없을듯, 너무 복잡하고 코드가 오히려 이해하기 어려워보여

2021-05-15 10:52 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +        else content
일단 뭐 가독성이야 주관적인거고 삼항연산자의 가독성이 좋지 않다고 생각하니까 그부분은 early return으로 변경할게 !

named argument는 사실 원래 없었는데, 너가 전에 짰던 코드 봤을때 length가 startIndex에 맵핑되는지 몰랐던거로 보였어서 일부러 따로 붙인거였거든 ?? 이걸 볼때마다 헷갈려서 내부구조 살펴보는거보다 그냥 명시하는게 좋지않을까?

2021-05-16 07:52 UTC, JoonBro approved these changes

2021-05-16 07:52 UTC, merged