feat(comment): 댓글 생성 API 구현
dev-floor/untitled-server pull request #33
Opened 2021-05-19 10:27 UTC by lxxjn0

### 상세 내용
- 댓글 생성 API 구현
- 테스트 코드 작성
- CommentFacade 제거

closes #30

2021-05-20 06:49 UTC, hungry-jay reviewed
DTO 따로 패키지로 묶어놓은거 좋은거같아.! + Test 코드 참고해서 나도 테스트 슬슬 시작해볼게!

2021-05-20 06:49 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +    }
comments 변수가 map돌리는 부분에만 사용될거라면, facade에서 작성했던 원래의 코드가 더 좋지 않을까!?
가독성때문에 이렇게 바꾼거같은데, 내 의견은 그쪽이 더 좋아보이긴 해!
근데 지금의 코드도 깔끔하고 괜찮을거같아서 이건 바꾸고싶음 바꾸고 아님 냅둬도 될듯!

2021-05-20 06:49 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    ) = commentService.create(articleId, author, request)
반환형을 명시하는게 좋지않을까?
https://kotlinlang.org/docs/coding-conventions.html#expression-bodies
이 부분에서 {}블록 -> expression으로 가면서 반환형을 없애긴 했는데, 내 생각에 expression을 사용할때 반환형을 생략할수 있다는거지, 쓰지 말아라를 의미하는건 아닌거같아.

아니면 우리끼리 팀 컨벤션을 만들어도 좋을거같아. Boolean이나 숫자를 return한다거나 이런 정말 간단한 경우 오히려 반환형을 쓰는게 더 안좋아보이긴 했거든. 그래서 이걸 생각해봤는데, 원시타입의 경우 반환형을 생략하고, 여기에서처럼 객체를 반환하는 경우에는 반환형을 명시하는게 어떨까?

2021-05-20 06:49 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +            .also { CommentResponse(it) }
여기 왜 DTO가 아니라 엔티티를 반환하도록 한거야??

2021-05-20 06:49 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/application/request/CommentRequest.kt
> +)
Req랑 Res로 패키지 나눠놓으니까 훨씬 보기 좋은거같다.! 다음에 만났을 때 한번에 싹 req, res로 패키지화하면 좋을거같네!

2021-05-20 07:17 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    ) = commentService.create(articleId, author, request)
안그래도 이 부분을 나도 계속 고민이 들긴 했었거든. 근데 변수를 사용하는 부분을 생각해보니 안쓰는게 더 낫다는 입장이 됐어.
코드 중에 예시를 하나 가져와보면

```kotlin
// ArticleFacade.kt
    @Transactional(readOnly = true)
    fun showByArticleId(articleId: Long): ArticleResponse =
        articleService.showById(articleId)
            .let {
                val options = articleOptionService.showAllByArticle(it)
                val hashtags = articleHashtagService.showAllByArticle(it)
                val favorites = articleFavoriteService.showAllByArticle(it)

                ArticleResponse(
                    options = options,
                    article = it,
                    hashtags = hashtags,
                    favorites = favorites,
                )
            }
```

이 코드가 있거든. 여기서 변수명을 집중해서 보면
```kotlin
val options = articleOptionService.showAllByArticle(it)
val hashtags = articleHashtagService.showAllByArticle(it)
val favorites = articleFavoriteService.showAllByArticle(it)
```

우리가 지금 이렇게 쓰고 있지
```kotlin
val options: List<ArticleOption> = articleOptionService.showAllByArticle(it)
val hashtags: List<ArticleHashtag> = articleHashtagService.showAllByArticle(it)
val favorites: List<ArticleFavorite> = articleFavoriteService.showAllByArticle(it)
```

이렇게 반환타입을 명시해서 쓰진 않고 있잖아.
코드를 작성해 나갈 때, 변수명을 정하는 시점에서 사용하는 메서드(예로 `articleOptionService.showAllByArticle`)가 어떤 타입을 반환하는지 마우스만 올리면 확인이 가능하니까 그걸 참고해서 변수명을 지었거든.
뭔가 그런 관점에서 변수가 어떤 타입인지 우리가 명시안하고 잘 사용하는 것처럼 메서드도 명시하지 않아도 사용할 때 큰 지장은 없지 않을까? 하는 생각인데 어떄?

2021-05-20 07:18 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +    }
아 이거 형 리뷰에도 내가 썼는데, 맥락이 다른 코드에 대해서는 끊어가는게 가독성이 더 좋은 것 같다고 느껴져서 이렇게 끊어서 코드 작성한거였는데 이런 관점은 어떤 거 같아?

2021-05-20 07:19 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +            .also { CommentResponse(it) }
아 그러게;; 이거 수정을 내가 잘못했나보다 ㅋㅋㅋ 이거 수정해둘게!

2021-05-20 07:43 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    ) = commentService.create(articleId, author, request)
이런식으로 할당해주는 부분에서는 변수명에서 타입을 유추할수 있잖아??
`val options = articleOptionService.showAllByArticle(it)`
options니까 자연스럽게 option들이 오겠구나를 알 수 있을거같은데,

`commentService.create(~~)` 같은 메서드는 이 이름만으로 타입이 유추가 되지 않기때문에 반환형을 명시하는게 좋다고 생각했어 ! 누군가 controller 코드를 봤을 때 "이 엔드포인트는 create 부분이니까 아무것도 반환하지 않겠구나" 라고 충분히 생각할 수 있는 부분이라고 생각해서. !

2021-05-20 12:59 UTC, JoonBro requested changes
고생하셨습니다.

2021-05-20 12:59 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    ) = commentService.create(articleId, author, request)
답이 정해져있지는 않은거같은데 나도 개인적으로는 컨트롤러단에서는 리턴 타입이 프론트에 전달하는 입장이니까 가독성이 좋은 리턴타입 명시하는 부분이 훨씬 좋을거 같다는 생각이 듭니다!

2021-05-21 04:20 UTC, hungry-jay reviewed
리뷰 얼마 없긴한데 한번 확인해줘 !

2021-05-21 04:20 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/comment/application/response/CommentResponse.kt
>      val user: ProfileResponse,
우리 API 명세 보니까 user 말고 author라고 되어있는데, 여기 그렇게 바꿔야하지 않을까?

2021-05-21 04:20 UTC, hungry-jay commented on src/test/kotlin/com/devfloor/untitled/comment/application/CommentServiceTest.kt
> +            description = "description"
여기 trailing comma 빠져있어!
```suggestion
            description = "description",
```

아 여기 말고도 테스트코드 아랫쪽 부분도 trailing comma 빠져있는 부분 채워넣으면 될거같아 !

2021-05-26 13:20 UTC, merged