feat(article): 게시글 삭제 API 구현, 게시글 Facade 제거
dev-floor/untitled-server pull request #37
Opened 2021-05-27 02:17 UTC by hungry-jay

### 상세 내용
* 삭제 API 구현
  * article 제거 시 연결된 엔티티 articleHashtag, articleOption 삭제하도록 했습니다.
  * 그외 Comment나 Favorite은 아직 무조건 삭제해야한다는 그런게 정해진게 없어서 일단 냅뒀습니다.
* 퍼사드 제거
  * 퍼사드 로직 그대로 service로 옮기고, 코드 불필요해보이는 부분들 줄여놓았습니다.
  * ArticleService부분 `showById` -> `showByArticleIdOrNull`로 변경했습니다. 더 좋은 네이밍 있으면 추천해주세요 !
  * 게시판 조회에서 BoardFacade 있는 버전으로 가져갔을거같아서 일단 여긴 안건드렸습니다.
* ArticleController에서도 id -> articleId 이렇게 명시하도록 바꿨는데 메서드네임도 바꿔야될까요?
  * 그럼 앞으로 모든 부분에서 도메인에 대한걸 "무조건" 명시하는걸까요??!

closes #28

2021-05-27 03:29 UTC, lxxjn0 requested changes
이번꺼는 거의 따로 리뷰 남길게 없었던 거 같아. 그래서 참고해주길 바라는 부분들만 달아뒀고 그 영속성 전이 부분만 조금 더 같이 고민해보면 좋을 것 같어. cascade를 쓰는게 맞을지 로직 상에서 직접 지워주는게 맞을지?

2021-05-27 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
이거 Null이 반환되지 않으니까 그냥 `showByArticleId`로 하는게 맞을 것 같아

2021-05-27 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
위에 코멘트를 달고보니 아래 다른 메서드랑 명명이 겹쳐서 이거 private 메서드로 바꾸고 다른 명명을 추천할까 했는데 다른 서비스에서 사용되더라고. 그런데 내 생각인데 entity를 필요로 하는 로직은 그냥 service에 두지 말고 repository 사용하도록 하는게 어떨까?

코드 반복이 조금 있을 수 있겠지만 지금 메서드를 없애고 사용하는 곳에서 `repository.findByIdOrNull` 이걸로 쓸 수 있게? 그럼 사용하는 곳에서도 null에 따른 분기나 로직 처리에 자유도 생기기도 하고 service에서는 private 메서드가 아니라면 response를 반환하도록 하면 일관적일 것 같기도 하고.

그런데 또 이게 마냥 좋은 방법이 맞을까 싶기도 하고. 이건 조금 더 생각해보긴 해야겠다.

2021-05-27 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun destroyById(articleId: Long) = repository.deleteById(articleId)
`destroyByArticleId`로 이름 바꾸는 거 어떨까. 일단 DDD 제대로 공부하고 이해하기 전에는 어떤 id인지 다 명시하는 방향으로 가는게 좋을 것 같아.

2021-05-27 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +        repository.findByName(hashtagName) ?: repository.save(Hashtag(hashtagName))
```suggestion
    fun createByName(hashtagName: String): Hashtag = repository.findByName(hashtagName)
            ?: repository.save(Hashtag(hashtagName))
```

이거 이렇게 할 수도 있나? 내가 아직 코틀린 문법이 어색해서 그런건지.. 기존 삼항연산자랑 비슷하게 생겨서 그런가..
이게 더 이해가 잘 가긴 하던데 한번 참고해주면 좋을 듯 ㅎㅅㅎ

2021-05-27 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/option/domain/OptionType.kt
> +        fun from(text: String): OptionType = values().first { it.text == text }
from 같은 건 정적 팩토리 메서드 몀명으로 주로 쓰이니까 반환타입 안붙여도 되지 않을까? 하는 생각이 들었는데 이것도 그냥 참고로 해줘 ㅎㅅㅎ

2021-05-27 03:55 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
> 이거 Null이 반환되지 않으니까 그냥 showByArticleId로 하는게 맞을 것 같아

이건 메서드 이름 중복때문에 이렇게 따로 바꾼거야. 다른 네이밍을 생각해봐도 딱히 떠오르는게 없어서

2021-05-27 03:59 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
> 코드 반복이 조금 있을 수 있겠지만 지금 메서드를 없애고 사용하는 곳에서 repository.findByIdOrNull 이걸로 쓸 수 있게? 그럼 사용하는 곳에서도 null에 따른 분기나 로직 처리에 자유도 생기기도 하고 service에서는 private 메서드가 아니라면 response를 반환하도록 하면 일관적일 것 같기도 하고.

조금 무슨말인지 이해가 잘 안됐는데 내가 이해한대로라면 해당 메서드를 지우자는말이야??
일단 코드 반복을 무시하고 이렇게 구현한다고 하면 articleService가 아닌 다른 곳에서 ArticleRepository에 접근하도록 해야하는거아니야?

2021-05-27 06:24 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
엉 맞어. 만약 articleService랑 articleRepository 중 하나를 의존한다면 repository를 의존하는게 좀 더 나으니깐? service의 경우 해당 도메인의 repository말고 다른 의존도 많은데 repository를 직접 의존하면 하나만 의존성을 가지면 되서. 이렇게 다른 레퍼지토리를 의존성으로 가지는게 DDD에서 응용 서비스일거야. 그래서 보통 repository만으로 해결이 가능하면 repository를 의존성으로 걸고, 그것 이상으로 비즈니스 로직이 필요한 경우 service를 의존으로 걸더라고

2021-05-27 08:17 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
그런데 한 서비스에서 다른 레파지토리에 대한 의존성을 갖는건 오히려 불필요한 의존관계를 갖게되는거 아니야?

지금 우리 프로젝트의 경우에 이러한 의존관계 자체가 없고, 한 도메인에 대한 레포지토리는 해당 도메인 서비스에서만 접근하도록 하고 있잖아. 그런데, 굳이 이걸 이렇게 의존관계를 갖게해버리면 얻는 장점보다 오히려 의존관계가 더 복잡해질 우려가있을거같은데.?!?

그리고 null에 대한 로직 처리에 대한 자유도를 이야기했는데, 바꿔말하면 다른 서비스에서 article 조회 때마다 일일이 null에 대한 신경을 써줘야한다는 이야기잖아.! 그런데 이걸하면서 얻을 수 있는 장점이 뭐야 ?

2021-05-27 14:25 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
위에서 앞서 이 방법이 좋은 방법이 맞을지 모르겠다고 말한것도 기존의 방법이 형이 마지막 문장에서 말한 것과 같은 이점들이 있어서 잘 모르겠다고 한거긴 해.

그런데 위에서 말한 부분
> 그런데 한 서비스에서 다른 레파지토리에 대한 의존성을 갖는건 오히려 불필요한 의존관계를 갖게되는거 아니야?
>
> 지금 우리 프로젝트의 경우에 이러한 의존관계 자체가 없고, 한 도메인에 대한 레포지토리는 해당 도메인 서비스에서만 접근하도록 하고 있잖아. 그런데, 굳이 이걸 이렇게 의존관계를 갖게해버리면 얻는 장점보다 오히려 의존관계가 더 복잡해질 우려가있을거같은데.?!?

이건 좀 말이 이상한 게 만약 의존관계가 현재 상태를 보면
- ArticleService
  - ArticleRepository
  - ArticleHashtagService
  - ArticleOptionService
  - ArticleFavoriteService
  - HashtagService
  - OptionService
- CommentService
  - CommentRepository
  - ArticleService
  - CommentFavoriteService

이렇게 의존관계가 맺어져있잖아. 지금 상태로는 CommentService가 ArticleService를 의존하고 있는데 ArticleService는 위에 articleRepository와 5개의 추가적인 서비스에 의존을 가지고 있어. 거기다 당연히 각각의 5개의 서비스가 더 다양한 의존을 가지고 있기 때문에 그 의존관계의 양은 훨씬 늘어나고 복잡하겠지.

그런데 여기서 ArticleService가 아닌 articleRepository를 의존하게 된다면 articleRepository 하나만 의존하고 나머지 불필요한 5개의 서비스를 의존하지 않게 되잖아.

그러면 훨씬 더 의존관계가 간단해지지. 의존관계가 프로퍼티로 주입받는 갯수만 의존관계가 아니고 그 주입받는 대상들이 필요한 의존관계도 모두 포함하니까, 그렇기 때문에 낮은 레벨의 객체를 의존하는게 더 좋은거지.

의존성을 가지는 위치를 높이는거랑 높은 위치에 있는 객체를 의존하는거랑은 전혀 다른 의미야. 풀어말하자면

articleRepository가 의존성을 가지는 것 vs articleService가 의존성을 가지는 것 -> 후자
articleRepository를 의존성으로 가지는 것 vs articleService를 의존성으로 가지는 것 -> 전자

이렇게 생각한다면 CommentService가 ArticleRepository를 가지는게 의존관계가 복잡해진다? 그건 아닌 것 같아.

2021-05-27 15:53 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
내가 복잡해질거같다고 말한거는 당장 의존관계가 간단해질지 복잡해질지에 대한 이야기가 아니라 추후에 어떻게 될지 몰라서 한 말이었어.!

나중에 비즈니스로직 더 커지고 서비스가 추가되면 그 때에도 지금과같은 고민을 할거고, 만약 그때 서비스를 의존하도록 다시 바꿔버릴 수 있을텐데 그러면 그 서비스에서는 한 도메인의 서비스와 레퍼지토리에 전부 의존을 해버리는 상황도 올거같은데..

그리고 지금 한 레퍼지토리는 일단 한 서비스에서만 접근하도록 되어있고 내가 생각할때는 당장 그게 덜 복잡해보였는데, 이걸 그렇게 바꿔버리고 그 관점으로 가게되면 서비스와 서비스간 의존관계는 없어도 될거고 결국엔 한 서비스에서 여러 레포지토리에 접근하는 형태가 될수도 있을거같은데..?

2021-05-27 15:54 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
그리고 결국엔 이걸 함으로써 얻을 수 있는 장점이라는걸 여전히 모르겠어

2021-05-28 01:38 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
일단 내 생각을 차례로 적어보면

> 내가 복잡해질거같다고 말한거는 당장 의존관계가 간단해질지 복잡해질지에 대한 이야기가 아니라 추후에 어떻게 될지 몰라서 한 말이었어.!

일단 이 의견에 대해서 내 생각은
- articleRepository를 의존하다가 추후 articleService를 의존하는 방향으로 변경되면 지금은 단순하지만 추후에 더 복잡해질 수 있다
- articleService를 의존한다면 지금도 복잡하고 나중엔 더 복잡해질 수 있다

이렇게 정리될 것 같고,

> 나중에 비즈니스로직 더 커지고 서비스가 추가되면 그 때에도 지금과같은 고민을 할거고, 만약 그때 서비스를 의존하도록 다시 바꿔버릴 수 있을텐데 그러면 그 서비스에서는 한 도메인의 서비스와 레퍼지토리에 전부 의존을 해버리는 상황도 올거같은데..

이건 repository로 의존을 바꾸는 지금 상황을 말하는 건지, 아니면 facade에서 service로 변환하는 상황을 말하는 건지 모르겠네.. 만약 전자라는 가정하에 articleRepository를 의존하다가 articleService를 의존하게 되는 상황이 온다면 당연히 articleRepository의 의존은 제거하고 그에 적절한 메서드를 articleService에 구현해서 사용하도록 하겠지? 그럼 동시에 두 개를 의존하는 상황은 발생하지 않을 것 같아!!

> 그리고 지금 한 레퍼지토리는 일단 한 서비스에서만 접근하도록 되어있고 내가 생각할때는 당장 그게 덜 복잡해보였는데, 이걸 그렇게 바꿔버리고 그 관점으로 가게되면 서비스와 서비스간 의존관계는 없어도 될거고 결국엔 한 서비스에서는 다른 서비스에가 아니라 여러 레포지토리들에만 접근하는 형태가 될수도 있을거같은데..?

여기서 서비스간의 의존관계가 없어도 된다는 말은 아니라고 생각하는게 만약 사용자를 삭제하는 부분에서 동시에 사용자가 작성한 게시글, 댓글, 좋아요 등을 모두 삭제한다고 가정하자. 그럼 또 사용자의 게시글을 삭제하기 위해서는 관련된 연관 정보를 함께 삭제해야 할건데 이 로직을 모두 userService에 작성해두기엔 너무 복잡하잖아. 그럼 아마 articleService의 destroy 관련 함수를 호출해서 처리할 수 있겠지.

service가 비즈니스 로직을 관리하는 곳이라고 했는데 한 비즈니스 로직을 실행하기 위한 다른 비즈니스 로직이 필요하다면, 그 비즈니스 로직이 구현되어 있는 service에 메서드는 충분히 사용할 수 있고, 그렇다면 service를 충분히 의존할 수 있지.

물론 장점은 아직까지는 단순히 articleService에 대한 의존성을 articleRepository를 의존하도록 낮출 수 있다는 것? 그럼으로 얻는 단점은 코드의 중복이 생기긴 하겠지.

둘 중 어디에 더 중요하게 가치를 두는지에 따라서 결정하는게 좋을 것 같아!

2021-05-28 06:33 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
> 한 비즈니스 로직을 실행하기 위한 다른 비즈니스 로직이 필요하다면, 그 비즈니스 로직이 구현되어 있는 service에 메서드는 충분히 사용할 수 있고, 그렇다면 service를 충분히 의존할 수 있지.

난 지금이 이미 이 상황에 충분히 적합하고, 충분히 service를 의존할 수 있는 상황이라고 생각하는데.

만약 그럼에도 불구하고 지금의 형태에서 각 service간 의존관계를 줄이고 repository라는 하위 수준으로 의존하도록 바꾸는게 좋다는거면, 내가 볼 때 다른 부분도 바꾸지 않을 이유가 없을거같은데..

그리고 의존관계를 줄임으로써 얻는 장점이 서로 변경에 영향을 줄여 각자 변경에 용이하게 만들고, 결국에 생산성을 높이는게 목적일텐데 이게 과연 생산성을 키우는 방향인가 생각하니 그렇지 않다고 생각이 들어서.

2021-05-28 06:44 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
아 그리고 궁금한게, repository가 낮은 레벨의 객체? 라고 이야기했는데. DB에 접근하는 repository가 낮은 레벨의 객체라고 말할수 있는거야?

2021-05-28 08:36 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>          ?: throw EntityNotFoundException("사용자가 요청한 리소스가 없습니다")
> 난 지금이 이미 이 상황에 충분히 적합하고, 충분히 service를 의존할 수 있는 상황이라고 생각하는데.
>
> 만약 그럼에도 불구하고 지금의 형태에서 각 service간 의존관계를 줄이고 repository라는 하위 수준으로 의존하도록 바꾸는게 좋다는거면, 내가 볼 때 다른 부분도 바꾸지 않을 이유가 없을거같은데..

맞어, 그래서 내가 알기로는 도메인 서비스가 아닌 응용 서비스를 구현할 때 보통 repository로 먼저 의존 관계를 가지도록 하고, 생각보다 특정 도메인에 대한 비즈니스 로직이 많이 추가된다면 그때 service로 의존 관계를 변경하더라고.

지금 상황이 service로 의존 관계를 가져도 괜찮은 것 같다고 생각하기도 하는데, service에서 사용하는 코드가 예외 처리하는 역할밖에 없다보니 코드 중복이 조금 생기더라도 의존 관계를 낮추고 repository를 의존하도록 하는게 어떨까? 하는 의견이었어. 코드의 중복이 생기는 부분은 사실 아쉽긴 한데 그래도 service를 의존하는 상태에서 repository로 낮추는 것만으로도 의미가 있지 않을까? 라고 생각해서.

그리고 사실 나도 의존 관계를 어떻게 관리하는게 더 좋은지에 대한 확실한 지식은 없어서 지금 말은 하지만 어떤 방법이 더 좋은 방법인지를 잘 모르겠어... 그래도 그냥 지금까지 코드짜면서 느낀건 어떤 하나의 객체가 불리기 위해 필요한 것들이 의존 관계인데 service에서 repository로 낮추면 이런 의존하게 되는 객체들이 많이 줄어들게 되고 보다 안전할 수 있다? 근데 사실 이것도 확실하진 않아서 형의 의견이 맞을 수도 있고 나도 헛갈리네..


> 아 그리고 궁금한게, repository가 낮은 레벨의 객체? 라고 이야기했는데. DB에 접근하는 repository가 낮은 레벨의 객체라고 말할수 있는거야?

아 그리고 여기서 레벨이 낮다(?)라고 말하는게 맞을지 모르겠지만 내가 말한 낮은 레벨이란 의미는 '계층이 낮다, 안쪽에 있다' 였어. repository의 경우 domain 레이어다보니 내가 낮다고 말한 것 같아!

2021-05-29 10:47 UTC, JoonBro requested changes

2021-05-29 10:47 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +            .apply { modify(request.title, request.content) }
여기 이부분 Comment 같은 경우 저희끼리 얘기하면서 저는

` fun modifyById(commentId: Long, request: CommentModifyRequest) {        showByCommentId(commentId).modifyContent(request.content) } `

요렇게 수정했는데 이부분도 apply 빼고 사용할 수 있는 부분이지 않을까 싶어서요!

2021-05-29 10:47 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>      private val repository: ArticleRepository,
연관관계를 어떻게 가져갈지 모르겠는데 다른 repository도 참조하자! 라고 결정되면 이부분 명명을 articleRepository로 가져가야될거같아요!

2021-05-31 10:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +            .apply { modify(request.title, request.content) }
아 저도 이 부분을 생각하기는 했었는데, 현재 article의 modify 로직이 "변경"만을 책임지지, "변경 후 객체 반환" 까지는 하지 않습니다.! 그래서 apply를 통해 `article` 변수가 Article 객체를 받도록 이렇게 구현했었는데요, 아래 링크는 이거에 대한 이야기를 나눴던 리뷰입니다.! 한번 읽어보시고 의견 말씀해주세요!
https://github.com/dev-floor/untitled-server/pull/29#discussion_r635845347

2021-06-01 05:59 UTC, JoonBro requested changes
리뷰 남깁니다!
레포지토리로 직접 연관관계를 가지도록 변경하면서 명확한 기준이 어떤건지 헷갈리네요! 
혹시 제가 리뷰남긴 내용에 대해 가르쳐주시면 감사하겠습니당 ㅜ

2021-06-01 05:59 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun showAll(): List<Article> = articleRepository.findAll()
이 함수도 비즈니스 로직이 없고 조회성 함수라 서비스 내에서 존재안해도 될거같은데 맞을까요..?
(다른 서비스에서 showAll()이 아니라 articleRepository.findAll()을 바로 사용?)

2021-06-01 05:59 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>                  val articleHashtags = articleHashtagService.showAllByArticle(it)
articleHastagRepository.findAllByArticle() 을 바로 사용해도 될거같은데..
리뷰를 하면서 저희 저번주 회의때 논의했던 내용이 명확하지 않은 거 같아서.. 제가 이해를 잘 못했을 수도 있는데..
혹시 아니라면 설명 부탁드려도 될까요!

2021-06-01 07:14 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun showAll(): List<Article> = articleRepository.findAll()
해당 부분이 BoardFacade부분인데, 그 부분은 건들지 않았습니다.!

일단 냅둔 이유는, board부분 이슈를 맡을 사람이 facade를 없애고 boardService 부분을 개발하면서 articleService를 사용할지 articleRepository를 사용할지 결정하는 상황이 올거라고 생각해서 입니다.

2021-06-01 07:19 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>                  val articleHashtags = articleHashtagService.showAllByArticle(it)
예~전에 구현해놓았던 `showByArticleIdOrNull` 메서드는 해당 로직에서 에러처리를 하기 때문에 사용하는 쪽의 비즈니스로직에서 에러 처리를 자유롭게 할 수 없다는 이유가 있었습니다.
따라서, repository로 접근하도록 하면서 얻는 이점이 1. 에러처리를 할 수 있고, 2. Service의존 -> Repository 의존으로 바꿀 수 있다는 장점이 있습니다.

그런데, 이 부분에 articleHashtagService -> articleHashtagRepository로 변경해버리면, 별다른 비즈니스 로직 없이 repository로 바로 접근해서 처리할 수는 있겠지만, 기존 articleHashtagService만 의존 -> articleHashtagService, articleHashtagRepository 둘다 의존 하게 됩니다.!(아래쪽에 modify쪽에 사용되는 부분이 있는데, 거기서 사용하는 articleHashtagService의 로직에는 비즈니스 로직이 충분히 있다고 판단했습니다.)

2021-06-01 14:49 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>                  val articleHashtags = articleHashtagService.showAllByArticle(it)
그러게, 이런 상황일 경우도 참 애매하네.. 일단 형이 짠 데로 가고 나중에 우리가 코드 짜다가 좀 더 괜찮은 방법이 있으면 그때 또 고민해보쟈!!

2021-06-01 15:05 UTC, lxxjn0 requested changes
나 이거 하나만 리뷰 남겼는데 한 번 확인해줘!!

2021-06-01 15:05 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
>      val article: Article = article
이거 나도 궁금해서 찾아봤는데 https://kok202.tistory.com/174 여기 게시글에 잘 설명되어 있더라고.

OnDelete 어노테이션은 DDL에 명시해주는거고 JPA에서 직접 찾아가서 지우도록 할거면 ManyToOne 어노테이션에 cascade=CascadeType.REMOVE를 명시해주면 된다네.

근데 내가 예전에 플젝할 때는 이거 cascade 안 걸고 직접 repository에서 삭제했는데 찾아보니까 객체에서 OneToMany로 필드에서 리스트를 연관관계로 가지고 있을 경우 cascade를 활용해서 주로 삭제하고 우리같이 ManyToOne인 경우 직접 삭제를 하나봐.

OneToMany에서 Many쪽 객체는 삭제를 할 수 있는 필드가 없어서 cascade가 필요한데 ManyToOne의 경우 우리가 article 필드가 있으니까 이걸로 조회해서 삭제할 수 있어서 직접 삭제하고. 사람들 사용 용도를 보니까 OneToMany나 ManyToMany에서 주로 사용하는거 같아!

2021-06-01 15:21 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
>                  val articleHashtags = articleHashtagService.showAllByArticle(it)
오호 그렇군요! 이런경우는 일단 service단에 비즈니스 로직이 없더라도 구현해서 사용하겠습니다 저도 ~

2021-06-01 15:21 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun showAll(): List<Article> = articleRepository.findAll()
넹~ 알겠습니다!

2021-06-01 15:23 UTC, JoonBro approved these changes
저는 리뷰 더이상 없습니다~ 고생하셨습니다!!! 
그 cascade에 대해서 3이서 논의해서 결정되면 머지하면 될거같네용!!

2021-06-01 15:23 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +            .apply { modify(request.title, request.content) }
이해했습니다!! 감사합니당

2021-06-02 11:54 UTC, lxxjn0 approved these changes
코드 더 수정할 부분 없는 거 같아!! todo 관련 부분이랑 추가적으로 제안정도로 남겨뒀는데 그것만 형 판단하에 확인하고 바로 머지해도 될 듯!! 수고많았어~~ 👍🏼

2021-06-02 11:54 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +            ?: throw EntityNotFoundException("존재하지 않는 게시글 입니다.")
이건 또 개인적인 의견이긴 한데 ㅋㅋㅋㅋ `articleRepository.findByIdOrNull`에서 조회한 article을 변수로 빼고 그걸 사용하는 건 어때?
예외를 처리하는 로직이 `articleRepository.findByIdOrNull` 코드에서 너무 멀리 떨어져있어서 약간 집중도가 떨어지는 느낌이 들어서. 예외가 발생한 지점이랑 멀리 떨어져있다보니 찾기 어려운 느낌?? 근데 이건 개인적인 느낌이라 형이 한 번 보고 괜찮으면 반영하고 지금 코드도 괜찮으면 그대로 둬도 되고!! 그냥 참고하라고 달았어!!

2021-06-02 11:54 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtagRepository.kt
> +    @Query(value = "DELETE FROM ArticleHashtag WHERE article = :article") // TODO: queryDSL
이거 todo 지우는 건 별론가? 내가 알기로 원래 todo를 작성해두고 머지하는걸 지양하라고 했거든. 그 의미가 todo를 할 걸 남겨두고 작업을 마무리하지 말라! 이런 뜻이었던 거 같아.
어차피 우리 다 인지하고 있는 부분이니까 차라리 개선사항을 notion에 정리해두고 지워도 괜찮을듯!! 아래 다른 코드에서 todo도 마찬가지!

2021-06-02 13:10 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtagRepository.kt
> +    @Query(value = "DELETE FROM ArticleHashtag WHERE article = :article") // TODO: queryDSL
반영했어!!

2021-06-02 13:10 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +            ?: throw EntityNotFoundException("존재하지 않는 게시글 입니다.")
반영했음!

2021-06-02 13:15 UTC, merged