feat(comment): 댓글 삭제 API 구현
dev-floor/untitled-server pull request #38
Opened 2021-05-29 12:16 UTC by JoonBro

논의중인 service, repository 연관관계 부분 결정나면 한번에 수정하는게 좋을 거 같습니다.

2021-05-31 14:07 UTC, lxxjn0 requested changes
우선 간략하고 빨리 코멘트 남겨봤는데 한번 확인 부탁해요~~~ ㅎㅅㅎ

2021-05-31 14:07 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
>  ) {
여기 CommentService가 또 자기 자신을 가지고 있는데??

2021-05-31 14:07 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +    }
이거 아마 외래키 참조 때문에 삭제 순서를 바꿔야 하는걸로 알고 있어!!
그리고 이건 개인적인 의견인데 괄호 안에 계속 메서드나 함수가 들어가면 가독성이 조금 어려운 것 같아서 체이닝으로 처리하는건 어떨까?

```suggestion
    fun destroyByCommentId(commentId: Long) {
        showByCommentId(commentId).run {
            commentFavoriteRepository.deleteByComment(it)
        }
        commentRepository.deleteById(commentId)
    }
```

2021-05-31 14:07 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +    ) = commentService.destroyByCommentId(commentId)
인자가 하나면 한 줄로 처리할 수도 있을 것 같은데 혹시 줄여지면 줄이고 아니면 함수 정의부는 한줄로, 선언부를 다음줄로 넘기는 것도 괜찮을 것 같아!

2021-05-31 14:07 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/commentfavorite/application/CommentFavoriteService.kt
> +)
해당 서비스에 코드가 더이상 존재하지 않는다면 그냥 삭제해도 괜찮을듯?

2021-06-01 08:15 UTC, hungry-jay reviewed
리뷰 남겼습니다 !
딴것들보다 삭제 시 cascade 옵션을 주는걸 많이 찾아봤는데, 이 부분 같이 이야기해보면 좋을거같아요 !

2021-06-01 08:15 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +        }
엔티티에 cascade 옵션을 주는 방법도 있을거같아요.! 옵션을 주면, 굳이 비즈니스 로직으로 처리하지 않아도 (혹시나) FK로 참조하는 레코드가 삭제되었을 때 무결성을 위반하는 일은 막을 수 있겠죠.

그래서 저는 현재 게시물 삭제에서 다 삭제하는 방향으로 구현했는데, 많은 글들을 읽어보니 사실 cascade를 잘 사용하지 않는 것으로 보입니다.

1. (가장 큰 이유) 현업, 많은 곳에서 soft delete를 하기 때문에 삭제하면 안됨.
2. 성능 이슈가 있다고도 얼핏 들은거같은데,(이건 정확하지 않습니다.) 사실 있다고 하더라도 크리티컬 할것같지 않고, 찾아봐도 이거에 대한 이야기는 나오질 않네요..

이정도인데, 일단 저희가 삭제를 어떻게할지 확실하게 정해진 것이 없는거같아서 일단은 이야기 해보는 것이 첫번째일 것 같아요.

----- 

참고로 cascade 옵션을 주는 방식은 여러가지가 있는데, 저는 이 부분들을 참고해 ondelete가 가장 적절해보여 @OnDelete를 사용했습니다.!

https://stackoverflow.com/questions/27472538/cascade-remove-vs-orphanremoval-true-vs-ondelete-cascade
https://stackoverflow.com/questions/7197181/jpa-unidirectional-many-to-one-and-cascading-delete/38495206

2021-06-01 08:15 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +        commentService.destroyByCommentId(commentId)
저희 Query String을 통해 articleId를 받아올 수 있도록 해야하지 않나요??

2021-06-01 08:15 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/commentfavorite/domain/CommentFavoriteRepository.kt
> +    fun deleteByComment(comment: Comment)
여기 n건 삭제니까 `deleteAllByComment` 가 되어야 할 것 같아요 !

2021-06-01 15:12 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +        }
https://github.com/dev-floor/untitled-server/pull/37#discussion_r643191820

이거 나도 주원이형 리뷰에 달아뒀는데 한 번 이야기해봐야 할 것 같아

2021-06-01 15:12 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +        commentService.destroyByCommentId(commentId)
이거는 댓글 삭제할 때 게시글 아이디가 필요가 없어서 상관없을거 같어!

2021-06-01 15:15 UTC, lxxjn0 approved these changes
따로 피드백 할 부분이 없는 것 같어!! 👍🏼 
cascade 부분에 대해서만 이야기 마무리하고 머지하면 될 듯?

2021-06-01 15:15 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +        }
아 그리고 만약 여기서 scope function은 뭔가 let이 적절할 것 같은 느낌? this로 사용되어야 할 부분이 없어보이고 반환값도 없는 것 같아서!!

2021-06-01 15:26 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/comment/presentation/CommentController.kt
> +        commentService.destroyByCommentId(commentId)
네 댓글삭제할때 commentId가(primary key) 존재해서 아티클을 사용하지 않더라구요!!
나중에 아티클 삭제할 때 comment 객체 내부에 아티클 정보를 삭제해야될 때 그때 수정이나 함수 생성이 필요해보입니다!

2021-06-02 14:58 UTC, hungry-jay approved these changes
고생하셨습니다 !

2021-06-02 15:16 UTC, merged