feat(board): 게시판 상세 조회 API
dev-floor/untitled-server pull request #41
Opened 2021-06-02 17:20 UTC by lxxjn0

### 상세 설명
- 게시판 도메인 구현
  ![image](https://user-images.githubusercontent.com/48052622/120524592-2f7b5780-c412-11eb-8030-e11e2daeeae1.png)
- 전반적인 코드 수정

closes #35

2021-06-02 17:23 UTC, lxxjn0 commented
졸프로 쓸 프로젝트가 없어서 급하게 수정한다고 말 못하고 건드린 코드가 좀 있습니다..
또 새롭게 구현하고 싶은 구조도 있어서 일단 마음대로 막 반영했는데 이상한 부분들 진짜 편하게 지적해도 되니까 거친 피드백 부탁함다 ㅎㅅㅎ

2021-06-03 06:16 UTC, hungry-jay reviewed
양이 꽤많고 복잡한데 고생많았어 !
1. 로깅 추가한거 좋은거같고,
2. BaseEnum은 좀 일관성??을 주기위한거지?
3. API 변수화한거도 좋은거같아 !

일단 양이 많아서 궁금한점이나 리뷰할점이 많았는데 천천히 읽어보면 될 거같아!

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        val articleHashtags = articleHashtagService.findAllByArticle(article)
로직에서 두가지 네이밍이 있으니까 헷갈려서 전반적인 네이밍을 repository랑 같게 바꾼거같은데
그럴거면 아예 Controller, Service에 있는 메서드 이름도 다 바꿔서 일관성있게 가져가는게 어때?

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: EntityNotFoundException.notExistsId(Article::class, articleId)
이 부분 에러 처리가 동떨어져있어서 scope function 없애고 처리하자고 한거 아녔어???
다시 바꾼 이유가 뭐야??

++ Line 34 `showByArticleId` 이 메서드에서는 scope function을 적용하지 않은 이유는 뭐야?

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/response/ArticleFeedResponse.kt
> +
이 부분은 왜 주석처리되어있는거야?

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    board: Board,
엔티티 위쪽 주석에 새로 추가된 board에 대한거도 추가로 써놓으면 좋을거같아 !

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    }
여기 if랑 else가 인덴트가 안맞으니까 뭔가 `if .. else` 구조로 한눈에 인지하기가 어려운거같은데
밑에처럼 바꾸면 어떨까??
```suggestion
    fun sliceContentByLength(length: Long): String =
        if (content.length > length) {
            content.substring(startIndex = 0, endIndex = (length + 1).toInt())
        } else {
            content
        }
```

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    ) = articleService.modifyByArticleId(articleId, request)
이 부분 CommentController에 있는 `modifyByCommentId` 여기 참고해서 이렇게한건데
그 부분 이 컨벤션때메 저런 구조로 한거 아녔어??
https://kotlinlang.org/docs/coding-conventions.html#expression-bodies

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        articleHashtagRepository.save(articleHashtag)
이 메서드 사용되지 않는거같은데 지워도 될거같아 !

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
여기도 네이밍 위에처럼 통일하면 좋을거가틈 !

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        articleHashtagRepository.saveAll(articleHashtags)
ArticleHashtag 객체를 생성하는 로직을 ArticleService에 두는 이유가 뭐야??
이렇게하면 `saveAll` 을 호출하는 모든 곳에서 항상
1. ArticleHashtag 객체 생성 2. saveAll 호출 이렇게 되어야하는거 아냐?

ArticleHashtag를 생성하기 위해서는 항상 Article과 Hashtag가 있어야하니까 여기서 객체를 생성하고 저장하도록 하는게 좋지않아??(현재 ArticleOptionService의 save 로직처럼)

그렇게 하면 modify같은데서도 이 메서드에 article, hashtag만 넘겨주고 이용하면 될거같고..

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +        log.info("[BoardController.showByBoardId] 게시판 상세정보 조회 - url: $BOARD_API_URI/${boardId}")
탬플릿 {} 지워도 될거같음!

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +            grade = courses.firstOrNull()?.grade,
이 코드 이해가 잘 안되는데,
게시판 상세 조회 시, 한 게시판에 존재할 수 있는 여러 수업들 중 하나(임의로)를 보여주는거야??

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/board/domain/Board.kt
> +    val openingSemester: OpeningSemester = openingSemester
@Embedded , @Embeddable이 뭐지 하고 찾아봤는데 이거로 만든 객체를 VO 라고 보면 되는거야??

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +            .also { log.info("[BoardController.showByBoardId] 게시판 상세정보 조회 완료 - response: $it") }
@lxxjn0 @JoonBro 
보다보니까 한줄에 100자 넘어가는부분이 몇군데 있는거같던데
그 제한때문에 이런데를 개행하는건 쫌 별로인거같다는 생각이 들어요

혹시 editorconfig에 100자 제한을 120자로 늘려보는건 어떨까요??

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +    }
여기도 {} 없애도될듯!

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
>      fun modifyByCommentId(commentId: Long, request: CommentModifyRequest) {
Dirty checking 하게하려면 트랜잭션 어노테이션 붙여야하는거 아니야?

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +        ?: EntityNotFoundException.notExistsId(Comment::class, commentId)
여기 비교해보면 scope function때문에 너무 가독성이 떨어지는느낌이지 않아??
```suggestion
    fun destroyByCommentId(commentId: Long) {
        val comment = commentRepository.findByIdOrNull(commentId)
            ?: EntityNotFoundException.notExistsId(Comment::class, commentId)
        
        commentFavoriteRepository.deleteAllByComment(comment)
        commentRepository.delete(comment)
    }
```

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/common/application/response/BaseEnumResponse.kt
> +        fun from(elem: BaseEnum) = BaseEnumResponse(elem.id, elem.text)
elem이 element야?? 변수명 풀네임으로 사용하는게 어때?

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/common/domain/BaseEnum.kt
> +    val id: String
여기 enum에서 name이 예약어라서 id라고 네이밍한거야??
다른 엔티티에서 id를 Long으로 사용하고있기도하고 뭔가 id가 name처럼 쓰이고있어서 좀 헷갈리는데
다른 이름 없을까..?

2021-06-03 06:16 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    fun createAllByNames(names: List<String>): List<Hashtag> = names.map(this::createByName)
createAllByNames 호출하는 곳에 이미 Transaction 처리가 되어있는데 여기 둘다 @Transactional 지워도 되지 않아?

밖에서는 항상 윗 메서드 말고 createAllByNames를 부를테니까 위에껀 private으로 되어도 될거같아!

2021-06-03 06:16 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +fun HashtagRepository.findByNameOrNull(name: String): Hashtag? = findByName(name).orElse(null)
개인적인 의견인데, CrudRepository처럼 Extension 전용 파일을 따로 만드는게 어떨까??

2021-06-03 06:39 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        val articleHashtags = articleHashtagService.findAllByArticle(article)
나 이거를 저번에 말한 것처럼
service에서 단순히 repository의 함수를 전달하는 수준인 메서드 -> repository 명과 동일하게
비즈니스 로직이 존재하는 메서드 => 기존에 정한 명명법

이런 기준으로 정한건데 이렇게 가져가는건 어때?

2021-06-03 06:40 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: EntityNotFoundException.notExistsId(Article::class, articleId)
아 맞어 그랬는데 이거 깃헙에서 볼 때는 삭제된 row 하고 다 같이떠서 너무 멀어보였는데 실제 코드보니까 기존 방법이 더 보기 좋더라고, 그래서 형이 처음 작업한 것처럼 했어!

2021-06-03 06:42 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: EntityNotFoundException.notExistsId(Article::class, articleId)
아 저건 한번 바꿔봤는데 스코프 내부에서 변수를 선언하는 로직도 많고 그래서 위에 코드처럼 한 눈에 보이진 않더라고.. 일단 내가 보기에 가독성이 각각 좋아보이는 방법으로 다시 바꿔뒀는데 어떤 식으로 가는게 좋을까?
이거 내가 코드 수정하다가 가독성 보기 좋게 바꾸다보니 막 바뀐거 같아서!! 형 의견 보고 그 쪽으로 고쳐도 될 거 같아!

2021-06-03 06:42 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/response/ArticleFeedResponse.kt
> +
아 이건 지금 수정중이야!!

2021-06-03 06:42 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    board: Board,
이것도 지금 반영중!!

2021-06-03 06:43 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    }
아 이거 봤는데 google kotlin 컨벤션에서 이런 식으로 사용하더라고. 그래서 똑같은 방식으로 쓰면 좋겠다 해서 수정한거 였는데 아래 방법이 좀 더 나을라나?

2021-06-03 06:45 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    ) = articleService.modifyByArticleId(articleId, request)
아 이거 저번에 이야기할 때 Unit의 경우 expression으로 표현해도 반환타입 명시하지 않는게 맞다고 해서 그냥 expression으로 내가 바꿨는데 기존 코드가 더 나은가? 위에 변경한 모습이 더 나으면 CommentController도 바꿔둘게!!

2021-06-03 06:45 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        articleHashtagRepository.save(articleHashtag)
아 그렇네!! 오키오키

2021-06-03 06:46 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
아 이건 그냥 레포지토리 메서드 넘기는게 아니고 비즈니스 로직이 있어서 이름 다르게 했어!

2021-06-03 06:48 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
> +        articleHashtagRepository.saveAll(articleHashtags)
아 그렇네, 그럼 이거 사실 매핑해주는거 말곤 repository 로직 사용하는거랑 똑같으니까 메서드 명은 saveAll 그대로 가져가고 전달받는 파리미터를 바꾸는 걸로 갈게!!

2021-06-03 06:49 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +        log.info("[BoardController.showByBoardId] 게시판 상세정보 조회 - url: $BOARD_API_URI/${boardId}")
이거 수정했어!!

2021-06-03 06:51 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +            grade = courses.firstOrNull()?.grade,
저거 학년(grade)이라서 만약 수업 게시판의 경우 해당 게시판과 연관된 수업에서 grade를 가져오는거!!

board가 연관관계를 가지고 있는 courses는 모두 grade가 같다는 전제 조건 하에 첫번째 수업의 grade를 바로 가져오자, 만약 수업 게시판이 아닌 경우 courses가 존재하지 않고 당연히 grade가 존재하지 않으니까 null을 반환한다!

이렇게 이해하면 될 것 같아!!

2021-06-03 06:51 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/domain/Board.kt
> +    val openingSemester: OpeningSemester = openingSemester
엉엉 그냥 값 객체라고 보면 될 것 같아!!

2021-06-03 06:52 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +            .also { log.info("[BoardController.showByBoardId] 게시판 상세정보 조회 완료 - response: $it") }
아 이거 일단 지금 수정하긴 했는데 120으로 바꾸는거 나도 괜찮긴 해서 이건 맞춰지는 방향으로 가져갈게

2021-06-03 06:52 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +    }
아 이것도 수정완료!! 내가 formatter를 안돌리고 올렸더라고... ㅜㅜ

2021-06-03 06:53 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
>      fun modifyByCommentId(commentId: Long, request: CommentModifyRequest) {
아 맞네!! 실수할 뻔!! 땡큐 수정해둘게!!

2021-06-03 06:53 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/comment/application/CommentService.kt
> +        ?: EntityNotFoundException.notExistsId(Comment::class, commentId)
아 좀 그런가? 근데 아래 코드도 가독성 좋은 것 같아서 아래 스타일로 바꿔들게!!

2021-06-03 06:53 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/application/response/BaseEnumResponse.kt
> +        fun from(elem: BaseEnum) = BaseEnumResponse(elem.id, elem.text)
오키오키!!

2021-06-03 06:55 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/application/response/BaseEnumResponse.kt
> +        fun from(elem: BaseEnum) = BaseEnumResponse(elem.id, elem.text)
이거 enum으로 변수명 바꿨어!!

2021-06-03 06:56 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/domain/BaseEnum.kt
> +    val id: String
그래서 나도 좀 생각해봤는데 enum 입장에서는 name이 유니크 할 수 밖에 없어서 식별자 역할도 돼서 id로 이름을 정하긴 했거든.
사실 회사에서 enum 코드를 관리할 때 이런 방법을 써서 여기에 가져와서 적용해보긴 했어...ㅋㅋㅋㅋ

2021-06-03 06:58 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/application/HashtagService.kt
> +    fun createAllByNames(names: List<String>): List<Hashtag> = names.map(this::createByName)
이거 private으로 안 둔게 다른데서 사용할 가능성이 높을 것 같아서 일단 살려뒀거든.. 단건으로 사용할 경우도 잦을 것 같아서 일단 public으로 열어뒀는데 닫아야할라나?

그 호출하는 곳에 @Transaction이 되어있긴 하지만 해당 서비스의 메서드를 컨트롤러에서 단독으로 부를 수도 있으니까 일단 Transactional은 다  달아뒀어!! 사용하는 곳에 종속되게 어노테이션을 선언하는건 뭔가 좀 안 좋은 것 같아서!!
HashtagService의 메서드인데 사용하는 곳에 따라 종속되게 바뀌는 거보단 일단 어떤 상황에서든 정상적으로 동작하게 구현해두는게 맞지 않을까 싶었어!

2021-06-03 06:59 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
> +fun HashtagRepository.findByNameOrNull(name: String): Hashtag? = findByName(name).orElse(null)
그렇게 뽑을까 했는데 findByName이 어떤 레포지토리에는 있고 어디에는 없고 그러더라고. 그래서 공통 메서드로 뽑는게 안될 것 같아서 이렇게 개별적으로 두는게 나을 것 같아!!

2021-06-03 11:02 UTC, JoonBro requested changes
엔티티들이 많아지고 복잡해지면서 어려웠을텐데 고생 많으셨습니다~
간단한 리뷰 댓글 달았습니다~

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        val articleHashtags = articleHashtagService.findAllByArticle(article)
메서드명으로 비즈니스 로직이 존재하는지 안하는지 구분은 할 수 있을거 같긴 한데.. 나도 잘 모르겠네 ㅋㅋ

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun showAllFeedsByBoardId(boardId: Long): List<ArticleFeedResponse> {
예전에 피드로 명명을 가져간다했었는데 검색해봤을때도 게시판? 게시글들이 정리되어 있는 것을 피드라고 하더라고? 인스타에서
즉 내 피드 내 게시글들인거고 그렇게 보면 굳이 우리가 feed라는 객체도 없으니까 showAllArticlesByBoardId가 더 낫지 않을까?

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: EntityNotFoundException.notExistsId(Article::class, articleId)
++ Line 34 : 변수 선언이 있더라도 article생성 -> 4개 변수 생성이니까 난 scope도 보기 괜찮았어

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    ) = articleService.modifyByArticleId(articleId, request)
컨벤션에 보면 메서드 파라미터가 여러개 + 길이가 길때 
```
fun modifyByArticleId(
        @PathVariable articleId: Long,
        @RequestBody request: ArticleModifyRequest,
    ) {        
          return articleService.modifyByArticleId(articleId, request)
    }
```
인데 밑밑줄 읽어보면(컨벤션) single expression 일때는 expression을 쓰자 되어있자나
그러면 이게 뒤에 적혀있는거니까 위 템플릿에서 expression으로만 바꿔 써야되나? 지금 변경분처럼?

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
>      fun modifyByArticle(article: Article, options: List<Option>) {
여기서 삭제 후 재생성해서 저장하는 방법도 비즈니스 로직으로 봐야되는건가????
수정하는 함수같은경우는 비즈니스 로직 유무에 따라 update/modify 명명을 다르게 가져가야할 이유는 없는건가?

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +        val courses = boardCourseRepository.findAllByBoard(board)
여기서도 board객체, course객체 둘다 조회해서 사용하는데
슬랙에서 말한거처럼 board객체에도 professor/subject가 있고
course에도 professor/subject가 있게 되는거 아니야????

그리고 Board에 해당하는 수업이 여러개인건 분반 달라서 그런거지?

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/response/BoardResponse.kt
> +    companion object {
요렇게 구현한게 정적 팩토리 메서드 맞지?

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/domain/Board.kt
> +    val openingSemester: OpeningSemester = openingSemester
그러면 혹시 위해 professor나 subject에는 해당 어노테이션을 사용안하는 이유는 뭐야?

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +            .also { log.info("[BoardController.showByBoardId] 게시판 상세정보 조회 완료 - response: $it") }
조하용~

2021-06-03 11:02 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/common/domain/Semester.kt
> +    override val text: String,
여기 오버라이딩 부분 내가잘 몰라서 그런데 설명 부탁해도될까?

2021-06-04 06:54 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        val articleHashtags = articleHashtagService.findAllByArticle(article)
음.. 근데 한 메서드 내부에서 두개의 네이밍이 존재하는 경우가 발생하다보니까
좀 헷갈릴수있는 소지가 있어보여서 !
그냥 전부 repository 명과 동일하게 가져가는건 어때??

나같은 경우도 service 로직 짤 때 repository로 헷갈려서 delete로 짰다가 다시 전부 destroy로 바꿨던적이 있었는데, 우리가 정한 네이밍을 사용하자 한다면 일단 통일이 안되고, repository 네이밍을 사용하자하면 통일이 가능할거같아 !

2021-06-04 06:56 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +        ?: EntityNotFoundException.notExistsId(Article::class, articleId)
나도 둘다 보기 편해서 그냥 지금이 셋다 보기 편하다면 지금상태로 걍 가져가면 될거같음 !
위에는 scope를 적용하지 않은 이유가 따로 있는가!? 였던거라 !!

2021-06-04 07:03 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    }
https://developer.android.com/kotlin/style-guide?hl=ko
여기 참고한거??? 흠 뭐가 좋을지 잘 몰게따 @JoonBro 준형님은 어떠세요??

2021-06-04 07:06 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
> +    ) = articleService.modifyByArticleId(articleId, request)
>인데 밑밑줄 읽어보면(컨벤션) single expression 일때는 expression을 쓰자 되어있자나
그러면 이게 뒤에 적혀있는거니까 위 템플릿에서 expression으로만 바꿔 써야되나? 지금 변경분처럼?

흠 아 이렇게 생각할수도 있겠네요.!

좀 컨벤션에 나오지 않은 부분들이 많아서 좀 애매하네.. 사실 나도 expression이 좋아보이긴하는데 어떻게하면좋을까여긴??

2021-06-04 07:06 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
이건 슬랙에서 이야기해보자!

2021-06-04 07:17 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/domain/Board.kt
> +    val openingSemester: OpeningSemester = openingSemester
제 생각이긴 하지만, 아마 불변의 값객체?? 의 경우에 VO를 사용하는 것으로 알고 있는데, 위의 Opening Semester나 Timetable같은게 그 경우이기 때문에 여기에만 vo로 사용하는 것 같아요!

2021-06-04 07:21 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun showAllFeedsByBoardId(boardId: Long): List<ArticleFeedResponse> {
이거 예~전에 Articles로 해놨다가 헷갈려서 Feed로 바꾼 부분이었는데 AllArticles도 좋네요!
전 둘다 괜찮을거같아서 이야기하고 정하면 될거같아요!

2021-06-04 07:26 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
>      fun modifyByArticle(article: Article, options: List<Option>) {
> 수정하는 함수같은경우는 비즈니스 로직 유무에 따라 update/modify 명명을 다르게 가져가야할 이유는 없는건가?

이 부분 이해가 잘 되지 않는데, 다시 설명해주실 수 있으신가요 !?!?

2021-06-04 07:27 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/response/BoardResponse.kt
> +    companion object {
맞습니다! 현재는 변경되어서 없어진것으로 보이네요 !

2021-06-04 07:31 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/domain/Semester.kt
> +    override val text: String,
현재 모든 enum class는 base enum이라는 인터페이스를 implement 하도록 구현해놓았더라구요 !
목적은 enum이 너무 많은데, id, text같은걸 일관되게 사용하도록? 하는 것이라고 생각합니다.!
그래서 base enum에서 정의한 text를 여기서 재정의해서 사용하는 것으로 보여요!

2021-06-04 12:33 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
> +    }
이건 근데 한 줄 개행하는게 나은거 같아서 밑에 방식으로 수정할게!!!

2021-06-04 12:35 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/domain/Board.kt
> +    val openingSemester: OpeningSemester = openingSemester
Professor랑 subject는 값 객체가 아니라 엔티티라서 이건 vo로 사용하는 애들에 대해서 붙이는 어노테이션. 물론 그렇다고 모든 vo에 붙이는 건 아니고 JPA 어노테이션이라 이건 공부를 해보면 될 듯?

2021-06-04 12:40 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
> +    fun showAllFeedsByBoardId(boardId: Long): List<ArticleFeedResponse> {
`showAllByBoardId`로 갈게요~~~

2021-06-04 12:45 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
>      fun modifyByArticle(article: Article, options: List<Option>) {
수정의 경우 그럴 듯? 그러니까 수정의 경우 항상 저 메서드를 사용하지 않을까? 라는 말인거 같어

2021-06-04 13:59 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +        val courses = boardCourseRepository.findAllByBoard(board)
이건 슬랙에서 말해둘게!

2021-06-06 05:52 UTC, merged