feat(environment): 클라이언트 테스트 환경 지원
dev-floor/untitled-server pull request #45
Opened 2021-06-06 16:30 UTC by lxxjn0

### 상세 내용
- @LoginUser 어노테이션 처리
  - local, dev에서는 기존에 생성된 유저 중 id가 가장 작은 유저를 반환
  - prod는 아직 기능 미구현으로 예외 발생
- 테스트 데이터 생성
  - local, dev 환경에서만 동작
- @JpaAuditing 추가
  - BaseEntity의 생성시점, 수정시점이 정상적으로 반영

closes #43

2021-06-06 16:54 UTC, JoonBro requested changes
아예 모르는 부분이라 검색하면서 공부하면서 봤는데.. 확인 및 모르는 부분 질문 위주로 리뷰 달았습니다~

2021-06-06 16:54 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
>      var content: String = content
찾아보니까 Lob을 통해 대형 문자열을 사용할 때 
```
@Lob
private CLOB lobStr;
```
CLOB 쓸 수 있다던데 요거랑 @Lob처리만 한거랑 다른건가?

2021-06-06 16:54 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/LoginUser.kt
> +@Retention(AnnotationRetention.RUNTIME)
해당 login 어노테이션(target)을 런타임 시간에 LoginUser를 사용하겠다 그런건가?

2021-06-06 16:54 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +class DefaultLoginUserArgumentResolver(
이 함수가 이제 dev에서 만든 loginUser 어노테이션이 반환하는걸 설정하는 부분 맞나?

2021-06-06 16:54 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +    override fun resolveArgument(
여기서 각 매개변수들이 보통 어노테이션에서 사용하는 디폴트 그런 건가? 여긴 잘 모르겠다 ㅜ
참조할만한 자료나 사이트 있으면 공유해줘

2021-06-06 16:54 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +    override fun resolveArgument(
아님설명도좋고 ^_^

2021-06-07 02:32 UTC, hungry-jay reviewed
고생했어 !
Application.kt파일에 궁금한점이랑, LoginUser 어노테이션 과정 한번씩만 읽어주면 될듯!!

2021-06-07 02:32 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/HongitApplication.kt
> +}
여기 코드 설명좀 해줄수 있어??

2021-06-07 02:32 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +}
@LoginUser이 어떻게 맵핑되는지 궁금해서 전반적으로 코드를 분석해보고 과정을 써봤는데, 이해한게 맞는지 확인하고싶어서 !
혹시 틀린게 있음 짚어줄수있엉???

1. LoginUser라는 곳에서 @LoginUser 어노테이션을 정의해준다.
2. LoginUserArgumentResolver 라는 곳에서 `supportsParameter` 메서드를 통해 @LoginUser 어노테이션에 대한 처리를 여기서 해줄거라고 말해줌?
  2-1. 이 인터페이스를 `DefaultLogin~~~`, `ProdLoginUser~~~~` 에서 구현해준다.
  2-2. 이 때 resolveArgument 메서드를 오버라이딩해, local,dev환경과 prod 환경에서의 @LoginUser 어노테이션이 반환해주는 user를 다르게? 가져가준다.
    * 현재 local, dev환경에서는 InitialDataConfig에서 초기화한 데이터들에서 유저중 맨앞에꺼 하나를 반환해준다.
3. application.yml에서 설정한 각 환경들을 실행하면 on-profile에 써있는 것에 따라, `LoginUserArtumentResolverConfig`의 각기 다른 환경으로 실행할 수 있게 된다.

2021-06-07 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
>      var content: String = content
아 자료형에서 CLOB이 있어? 안그래도 Lob 처리를 안했을 때는 문자열 길이가 너무 길어서 안됐는데 @Lob을 붙이면 알아서 Blob 타입으로 처리해줘서 잘 되더라고. 그래서 저걸로 해뒀어!

2021-06-07 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/LoginUser.kt
> +@Retention(AnnotationRetention.RUNTIME)
엉엉 런타임에서 동작 가능하다 이런 의미일거야

2021-06-07 03:29 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +class DefaultLoginUserArgumentResolver(
엉엉 config에서 profile이 local, dev 일 때 이 클래스를 빈으로 등록하는 거야!

2021-06-07 03:32 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +    override fun resolveArgument(
저거는 LoginUserArgumentResolver가 HandlerMethodArgumentResolver를 상속받고 있고, resolveArgument는 HandlerMethodArgumentResolver 인터페이스가 가지고 있는 메서드라서 그런거야.

2021-06-07 03:34 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/HongitApplication.kt
> +}
이거는 그 시스템 전체에서 LocalDateTime에서 사용할 Timezone을 설정해주는 작업이야. `@PostConstructor`가 해당 어플리케이션 클래스가 로딩된 후 작동하는 어노테이션인데 시스템이 다 올라가고 우리 시스템의 타임존을 세팅한다 이런 의미?
이게 없으면 우리 로컬 기준으로 시간을 잡는게 아닌 것 같아서 추가해뒀어

2021-06-07 03:41 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/common/config/auth/DefaultLoginUserArgumentResolver.kt
> +}
응응 대부분 맞는거 같아. 내가 문장에 대해서 정확하게 이해를 잘 못할 수도 있어서 일단 내가 생각하는 과정을 다시 써볼게

1. `@LoginUser`를 생성 -> annotation class
2. `HandlerMethodArgumentResolver`를 상속하는 `LoginUserArgumentResolver`를 구현
  - profile 상관없이 모두 동일하게 동작한다면 그냥 바로 인터페이스 구현체를 구현하면 됨
  - 그러나 여기서는 local, dev 환경과 prod 환경에서 각각 다르게 동작해야 함
  - 그래서 `HandlerMethodArgumentResolver`를 상속하는 `LoginUserArgumentResolver` 인터페이스를 구현하고 모든 프로파일에서 동일하게 적용되어야 할 `supportsParameter`는 인터페이스에서 재정의 진행
  - `supportsParameter` 메서드는 resolver가 동작하는 시점에 파라미터에 우리가 구현한 `@LoginUser` 어노테이션이 붙어있는지 확인
  - `resolveArgument`는 각 프로파일에 따라 다르게 동작해야 해서 일단 `UnsupportedOperationException` 처리
  - 각 프로파일에 따라 다르게 구현한 구현체 2개 생성
    - `DefaultLoginUserArgumentResolver`
    - `ProdLoginUserArgumentResolver`
3. `LoginUserArgumentResolverConfig`에서 프로파일에 따라 각각에 해당하는 Resolver를 빈으로 등록해 

대충 이런 흐름으로 생각하고 구현했어!!

2021-06-07 04:00 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
>      var content: String = content
- CLOB: 문자 대형 객체 (Character). Oracle Server는 CLOB과 VARCHAR2 사이에 암시적 변환을 수행한다.

   - BLOB: 이진 대형 객체 (Binary). 이미지, 동영상, MP3 등.

2021-06-07 04:53 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/HongitApplication.kt
> +}
그러면 `fun init()` 이라는 메소드를 사용하는 시점은 언제가 되는거야?

2021-06-07 12:51 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/HongitApplication.kt
> +}
저건 HongitApplication 클래스가 생성된 직후!

2021-06-07 13:40 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/HongitApplication.kt
> +}
그 저 메서드가 init { } 이렇게 생성한거랑 동작이 같은거야?

2021-06-13 02:08 UTC, merged