feat(articleFavorite): 게시글 좋아요 생성, 삭제 API
dev-floor/untitled-server pull request #48
Opened 2021-06-17 05:30 UTC by hungry-jay

### 상세 설명
- 게시글 좋아요 생성, 삭제 구현
  - 현재 코멘트 부분(쿼리 스트링으로 받는)과는 달리 URI를 `/articles/{articleId}/favorites` 이렇게 해놓았는데, 이유는 일단 URI가 자원의 identity를 의미하는 것이기 때문에, "article에 속해있는 좋아요"를 나타내고자 저렇게 했습니다. 계층 구조를 알기 쉽다고 생각해서요. 물론 put, delete와 같은 곳에서는 articleId가 여전히 불필요합니다. 이것에 대해서 의견이 궁금합니다 !

- 현재 URI에서 id 써놓은 부분에서 camel case로 써놓아 왔는데, `e.g) /articles/{articleId}` URI를 대쉬나 언더스코어로 사용하기를 많이들 권장하잖아요!? 이 부분 바꾸는건 어떻게 생각하시나요? -> `/articles/{article-id}`

- 그리고 comment favorite까지 싹 해버릴까 했는데 저 부분에 대한 논의가 먼저라고 생각해서, 저부분들이 정해지면 comment favorite까지 해서 머지할게요 ! 

closes #46

2021-06-17 14:33 UTC, lxxjn0 commented
리뷰 남기기 전에 의견 물어본 부분에 대해서 먼저 작성하고 리뷰 남길게!!

- 우선 URI는 comments 처럼 `/api/favorites?articleId=1` 이렇게 가는게 낫지 않을까? 사실 댓글도 유저와 게시글 간의 연관관계라 생각해서 별도의 URI를 쓰기로 한거고 좋아요도 사실 댓글이랑 거의 같은 구조인 것 같아서 동일하게 가는게 좋을 것 같아.

- URI에서는 kebab case로 사용하는 것 같은데 java에서는 camel case가 원래 컨벤션이라 그냥 articleId 그대로 가는게 좋을 것 같아. yml 파일에서는 kebab case로 작성한 값들도 java로 가져올 땐 다 camel case로 변경해서 가져오니까 같은 맥락으로 camel case 그대로 쓰는게 맞는 것 같아. 그리고 사실 이걸 kebab case로 쓰는 코드를 아직 내가 본 적이 없어서 어색하기도 하고.

2021-06-17 14:39 UTC, lxxjn0 requested changes
리뷰는 간단하게 남겼는데 한번 확인해줘!!! 👍🏼

2021-06-17 14:39 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteType.kt
> +        fun from(type: String) = values().first { it.text == type }
이거 매개변수 이름을 text로 가져가는 건 어때? 별론가?

```suggestion
        fun from(text: String) = values().first { it.text == text }
```

2021-06-17 14:39 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
> +    fun destroy(favoriteId: Long) = articleFavoriteRepository.deleteById(favoriteId)
이 부분은 생각해봤는데 아마 좋아요의 id가 관리되진 않을 것 같아.
사용자가 해당 게시글을 좋아요 눌렀는지 여부로만 확인될 것 같아서 (프론트에 보여줄 때 exists 여부만 확인해서 boolean으로 넘겨주는 느낌?) articleId랑 user 정보를 사용해서 삭제하는게 좋을 것 같아.

2021-06-17 14:39 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +        articleFavoriteService.destroy(favoriteId)
여기도 위에 내용대로 user랑 articleId를 받는 식으로 해서 수정하면 될 듯?

2021-06-18 01:45 UTC, hungry-jay reviewed
@lxxjn0 
> 우선 URI는 comments 처럼 /api/favorites?articleId=1 이렇게 가는게 낫지 않을까? 사실 댓글도 유저와 게시글 간의 연관관계라 생각해서 별도의 URI를 쓰기로 한거고 좋아요도 사실 댓글이랑 거의 같은 구조인 것 같아서 동일하게 가는게 좋을 것 같아.

일단 두 엔티티를 연결해주는 객체면 모르겠는데, 의미적으로 봐도 article에 속해있는 것 같아서 제안한거야.! 그리고 article의 favorite인지 comment의 favorite인지 구분을 해야할텐데 그걸 쿼리스트링으로 구분해서 나누는건 말이 안되는거같고 uri로 구분하는게 좋을거같아 !

> URI에서는 kebab case로 사용하는 것 같은데 java에서는 camel case가 원래 컨벤션이라 그냥 articleId 그대로 가는게 좋을 것 같아. yml 파일에서는 kebab case로 작성한 값들도 java로 가져올 땐 다 camel case로 변경해서 가져오니까 같은 맥락으로 camel case 그대로 쓰는게 맞는 것 같아. 그리고 사실 이걸 kebab case로 쓰는 코드를 아직 내가 본 적이 없어서 어색하기도 하고.

java에서는 당연히 카멜 케이스를 사용하는게 맞는데, URI는 dash로 갈수 있지 않아? URI가 camel이 아니라고해서 자바의 컨벤션을 어긴것도 아니고, 너가 말한 것처럼 java로 가져올때 camel로 변경하면 되는거잖아? 그리고 kebab으로 되어있는걸 본적이 없다는건 아직 못 본 것일것같은데, 실제로 많은 오픈소스에서 dash로 되어있기도 해 !

2021-06-18 01:45 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteType.kt
> +        fun from(type: String) = values().first { it.text == type }
반영할게 !!

2021-06-18 01:45 UTC, hungryjayy commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
> +    fun destroy(favoriteId: Long) = articleFavoriteRepository.deleteById(favoriteId)
반영할게 !

2021-06-18 02:13 UTC, lxxjn0 commented
- comment의 favorite인지 article의 favorite인지는 `/commentFavorites?articleId=1`, `/articleFavorites?articleId=1` 이렇게 가면 되지 않을라나? 어차피 두개는 전혀 다른 엔티티로 관리하니까 이렇게 하면 될 것 같은데?

- 어디서 쓰는지 혹시 링크 같은거 있어? 내가 이건 잘 몰라서, 이게 주로 url이나 yml에서 케밥 케이스를 쓰는건 아는데 yml만 하더라도 자바에서 알아서 카멜로 컨버팅해서 사용하도록 하거든. 그래서 난 카멜이 더 익숙한 것 같고 회사에서 코딩할 때 회사 코드는 전부 카멜 케이스를 사용해서 내가 다른 예시는 못봤어

2021-06-18 02:45 UTC, JoonBro approved these changes
리뷰관련해서 준영이가 남긴부분 외엔 저도 딱히 수정할게 보이진 않네요! 고생하셨습니다.

질문 관련해서
먼저 URI는 준영이가 댓글과 같은 맥락으로 보았는데, 제 생각은 댓글같은 경우는 댓글이란 객체가 존재하고, 댓글과 게시글을 매핑하지만, Favorite 같은 경우는 article에 속해있는 부분이니까 다르게 가져가도 괜찮지 않을까요? articleId도 그대로ㅡ가져가도될거같은데..

2021-06-23 06:55 UTC, lxxjn0 requested changes
한두개 간단하게 리뷰 남겼어!! 한번 확인해줘~~ ㅎㅅㅎ

2021-06-23 06:55 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +        const val ARTICLE_FAVORITE_API_URI = "$BASE_API_URI/articleFavorites"
```suggestion
        const val ARTICLE_FAVORITE_API_URI = "$BASE_API_URI/article-favorites"
```

이 부분은 저번에 형이 말한대로 하이픈으로 가져갈까?

2021-06-23 06:55 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/request/ArticleFavoriteCreateRequest.kt
> +)
이거 바로 FAVORITE_TYPE 이걸로 받아도 될거야. 프론트에서 enum id값으로 넘겨주면!!

2021-06-24 02:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/request/ArticleFavoriteCreateRequest.kt
> +)
FAVORITE_TYPE이라는게 뭐야???

2021-06-24 02:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +        const val ARTICLE_FAVORITE_API_URI = "$BASE_API_URI/articleFavorites"
이건 슬랙에서 이야기해보자!

2021-07-03 06:59 UTC, lxxjn0 approved these changes
남긴 부분들 말고는 다 좋은 것 같어!! 👍🏼 
리뷰가 넘 늦어져서 쏘리쏘리 ㅜㅡㅜ 진짜 수고 많았으 ㅎㅅㅎ

2021-07-03 06:59 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteType.kt
> +    }
이거 코드에서 안 쓰이는거 같아서 지워도 될 것 같어!!

2021-07-03 06:59 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
다른 컨트롤러에서 create의 경우 uri를 담아서 보내주는 코드가 아마 있을건데 그거만 참고해서 바꾸면 될 듯?

2021-07-03 07:41 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
반영완료 !

2021-07-03 07:42 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
아 맞다 근데 여기서는 uri 안보내줘도 되는거 아니야!? 어차피 프론트에서 +1하게 하고 나중에 게시글 조회때 그 숫자가 조회되는거니까?

2021-07-03 07:42 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/domain/ArticleFavoriteType.kt
> +    }
반영완료 !

2021-07-03 07:49 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
아 글고 방금 생각난건데, 이미 유저가 좋아요를 누른 경우면 게시글 조회시점에 boolean으로 넘겨줘야하는건가??

2021-07-03 08:25 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
Api콜이 좋아요 누를때마다 날라가는거 아니였나용????? 밖에서도??

2021-07-03 08:25 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
불리언으로 넘겨줘야할거 같네요 좋은 생각입니다.!

2021-07-03 15:50 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
아 저건 사실 사용하지 않기는 한데 CREATED 상태코드의 경우 uri에 생성 리소스의 위치를 넘겨서 보내주는게 좋다고 하더라고.
그래서 일단 뭐 담아서 보내줘도 괜찮을 듯?

2021-07-03 15:50 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/presentation/ArticleFavoriteController.kt
> +    ) = articleFavoriteService.create(request, user)
이미 유저가 좋아요 누른건 나중에 유저 구현하면서 같이 묶어서 가버리자!

2021-07-09 09:27 UTC, JoonBro approved these changes

2021-07-09 09:27 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
> +        ).let { articleFavoriteRepository.save(it) }.run { id }
여기서 articleFavorite객체를 생성하여 그 객체를 save하고 run id에 해당하는 로직은 어떻게 이해하면 될까용? 잘 모르겠어서요!

2021-07-11 04:04 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/articlefavorite/application/ArticleFavoriteService.kt
> +        ).let { articleFavoriteRepository.save(it) }.run { id }
id를 return하기 위한 로직입니다 !
save 메서드를 통해 반환받는 객체는 articleFavorite이고, 그 객체를 run에서 받아서 해당 객체의 프로퍼티 중 하나인 id를 반환하는 로직이라고 이해하심 될 것 같아요 !!

2021-07-12 08:30 UTC, merged