feat(board): 수업 게시판 목록 API
dev-floor/untitled-server pull request #55
Opened 2021-07-03 15:47 UTC by lxxjn0

closes #54

2021-07-07 02:31 UTC, hungry-jay reviewed
리뷰 확인해줘 !

2021-07-07 02:31 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +
만약 이렇게하면 URI가 게시판 목록조회랑 같은거 아닌가!?
그러면 게시판 목록조회 때에도 여기로 call이 오고, 마찬가지로 이걸 호출할 때도 게시판 목록 조회로 call이 가게 되지않아?

2021-07-07 02:31 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/course/domain/Course.kt
> +    fun matchRequiredInfo(course: Course): Boolean =
이 메서드 네이밍 이렇게 하는게 어때??
```suggestion
    fun matchesRequiredInfo(course: Course): Boolean =
```

2021-07-07 02:31 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +
흠 그리고 뭔가 "수업 게시판"과 "나머지 게시판"이 존재하기 때문에 조금 URI 맵핑하는게 복잡할수있을거같은데 이런 방식은 어떤거같아??

1. 모든 게시판 조회는 "게시판 상세정보 조회"로(`/api/boards/boardId`)
2. 만약 파라미터가 존재하면(type) `showAllBoardByBoardType` service를 호출하도록, 존재하지 않으면 `showByBoardId`를 호출하도록. -> 이때 컨트롤러 반환은 `List<BoardResponse>` 로 통일
3. 존재했던 경우(수업 게시판)에 사용자가 수업에 대한거 선택을 완료하고 확인버튼을 누르면 그때 또 `/api/boards/boardId`로 이번엔 파라미터 없이 호출하도록 -> 다시 1번으로

이렇게 하면 뭔가 controller 역할도 잘 수행하는 것 같고 URI를 복잡하게 나누지 않고도 잘 처리하는거같아서 .? 어떤거같아?

2021-07-08 06:23 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +
주원이형말대로 컨트롤러에서 나눠서 처리해도 괜찮을거같네요! 제가 리스폰스 API 프론트에 전해줄때 근데 새로만들었었는데 수정해야겠네요그럼!

2021-07-08 06:43 UTC, JoonBro requested changes
리뷰 달았습니당~

2021-07-08 06:43 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +                    .firstOrNull()
여기서 수업에 대한 데이터가 없는 경우에 Null이 나올텐데 널인 경우 BoardResponse 내 값들이 널로 전달될거같은데 전달 자체를 막는건 어때?

2021-07-08 06:43 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/response/BoardResponse.kt
> +        professor = course?.let { ProfessorResponse(it.professor) },
위에말한 내용에서 널이 들어갈 부분들인거같고!

2021-07-08 12:08 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +                    .firstOrNull()
이 경우에 선택 화면 없이, 모든 수업에 대한 게시판(전체 수업 게시판)조회를 하도록 해야하는걸까요!?
제가 기억을 못하는건지 혹은 즐겨찾기부분에 대한 이야기가 명확하게 되지 않은건지 모르겠어서 약간 헷갈리네요!!

2021-07-08 12:08 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +                    .firstOrNull()
이 경우에 선택 화면 없이, 모든 수업에 대한 게시판(전체 수업 게시판)조회를 하도록 해야하는걸까요!?
제가 기억을 못하는건지 혹은 즐겨찾기부분에 대한 이야기가 명확하게 되지 않은건지 모르겠어서 약간 헷갈리네요!!

2021-07-09 08:35 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/course/domain/Course.kt
> +    fun matchRequiredInfo(course: Course): Boolean =
이거 match랑 matches랑 어떤 차이야?? 내가 영어가 좀 부족해서...ㅋㅋㅋㅋ ㅠㅠ

2021-07-09 08:36 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +
먼저 저기 GetMapping에 params로 값을 넣어줘서 두개 각각 따로 매핑이 돼!! 그냥 목록조회면 거기로, type 파라피터가 존재한다면 여기로!!

2021-07-09 08:38 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +
아 그리고 여기서는 목록으로 조회를 해야해서 id가 안 들어오지 않어??

2021-07-09 08:40 UTC, lxxjn0 commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +                    .firstOrNull()
이게 모든 부분에서 방어 로직을 짜야하는데 그러면 예외처리랑 이런 걸 다 고려해야 해서 이건 아니면 나중에 같이 확인하는게 좋을 듯??

2021-07-09 08:56 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/board/presentation/BoardController.kt
> +
> 아 그리고 여기서는 목록으로 조회를 해야해서 id가 안 들어오지 않어??

아 내가 수업게시판에 대해 우리끼리 정한걸 잘못 이해한거같아 ! "수업 게시판 다건에 대한 선택" 이니까 저렇게 하는게 맞겠구나 !

param 유무에 따라 다른 쪽으로 각각 맵핑되는건 맞는거야!? URI가 리소스의 위치를 가리키는 거니까, URI가 같으면 뒤의 파라미터가 있건없건 둘다 날라갈줄 알았는데 아닌가보네 !!

2021-07-09 08:57 UTC, hungry-jay commented on src/main/kotlin/com/devfloor/untitled/course/domain/Course.kt
> +    fun matchRequiredInfo(course: Course): Boolean =
`match~~` 라는 네이밍이 뭔가 명령형이니까 딱 봤을때 불리언 함수가 아닌거같아서 !?
보통 불리언 함수는 `is~~` `has~~` `does~~~` 이렇게 많이 쓰니까 여기도 네이밍을 그렇게 맞추는게 좋을거같아서 !

2021-07-09 09:29 UTC, JoonBro commented on src/main/kotlin/com/devfloor/untitled/board/application/BoardService.kt
> +                    .firstOrNull()
즐겨찾기 화면 진입때 전체 조회해서 데이터받고 학년이나 수업 선택에 따라 보여지는게 달라지게 하기로 했어요!

2021-07-09 09:30 UTC, JoonBro approved these changes
고생하셨습니다.

2021-07-12 11:27 UTC, merged