#51 홈화면 조회 api
dev-floor/untitled-server pull request #66
Opened 2021-07-29 13:38 UTC by JoonBro

모듈 분리해서 다시 올립니다.

gradle 의존성 설정하는 부분을 맞게 했는지 잘 모르겠습니당.

늦어져서 죄송합니당

2021-07-31 04:35 UTC, hungry-jay reviewed
일단 queryDSL 도입하시느라 고생하셨습니다.!
커스텀 레포지토리 에러나는데 혹시 무슨 문제일까요!?

2021-07-31 04:35 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +data class ArticleHomeResponse(
저는 지금도 네이밍 나쁘진 않긴 한데요, 말씀하신것처럼 ArticleResponseInHome도 좋은거같아요 !
한번쯤 고려해보는 것도 좋을듯해요

2021-07-31 04:35 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +class ArticleRepositoryCustom(
이 레포지토리 네이밍 `ArticleCustomRepository`가 어떨까요?

2021-07-31 04:35 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +    }
간결함을 위해서 이런 코드는 어떨까요?
만약 괜찮을 것 같다면, 이 메서드 뿐 아니라 비슷한 구조를 갖는 다른 `showTopFive~~` 메서드들도 마찬가지로 간결하게 바꿔도 좋을거같아요 !

```suggestion
    fun showTopFiveByFavorite(): List<ArticleHomeResponse> =
        articleRepositoryCustom.findByFavoriteTopFive()
            .map {
                ArticleHomeResponse(
                    article = it,
                    articleFavorites = articleFavoriteRepository.findAllByArticle(it),
                )
            }
```

2021-07-31 04:35 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/application/response/HomeResponse.kt
> +}
전반적으로 lint 적용이 안되어있는 것 같아요 !

2021-07-31 04:35 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/presentation/HomeBoardController.kt
> +class HomeBoardController(
이거 있어야하는 것 아닌가요!?
```suggestion
@RestController
@RequestMapping(value = [BASE_API_URI])
class HomeBoardController(
```

2021-07-31 04:35 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +import com.devfloor.hongit.core.articleviewcount.domain.QArticleViewCount.articleViewCount
지금 인텔리제이로 확인중인데요, 현재 QArticle를 찾지 못하는 에러가 나고 있는데 이 부분 확인이 필요할거같아요 !

2021-07-31 07:02 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +data class ArticleHomeResponse(
근데 이거 Response라서 suffix를 일부러 Response로 맞춘 거 아냐??

2021-07-31 07:03 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +class ArticleRepositoryCustom(
이것도 내가 알기론 주로 저런 식으로 이름을 짓는다고 해서 저렇게 한 걸로 알고 있어. 그냥 구글에 검색하면 대부분 맨 뒤에 커스텀을 붙이더라고. 우리 회사도 주로 그러긴 하던데 이유는 몰그ㅔㅆ넹

2021-07-31 07:04 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +import com.devfloor.hongit.core.articleviewcount.domain.QArticleViewCount.articleViewCount
이거 혹시 빌드 해봤어?? Q도메인은 빌드해야지 생기는거라 빌드하고 확인해봐야 할 것 같은데

2021-07-31 07:25 UTC, lxxjn0 requested changes
리뷰 남겨봤는데 한번 확인 부탁드려용~~~ 👍🏼

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/board/domain/Board.kt
> + * @property openingSemester 개설학기
이 부분 원래대로 작성되어야 할 것 같은데 확인해봐~~

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/application/response/HomeResponse.kt
> +}
그리고 여긴 따로 프로퍼티에 어노테이션 안다는거면 굳이 안띄워나도 될 것 같은데 이건 스타일 차이니까 그냥 제안? 정도 ㅎㅎㅎ

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/application/HomeBoardService.kt
> +            )
이 부분을 그냥 이렇게 넣지말고 private 메서드로 하나 빼서 유의미한 이름을 붙여서 사용하는건 어떨까?

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +}
내가 생각해봤는데 이거 Article로 가져오지 말고 바로 Response로 만들어서 뽑는게 어떨까?? 그러면 이게 굳이 core에 있을 필요 없이 api 모듈에 둬도 될 것 같어!!!

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +}
그리고 추가적으로 얘를 interface로 추상화시키고 Impl이라는 구현체를 하나 더 만들어서 거기에 구현 로직을 두는 것도 좋을 것 같어!!

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/board/domain/BoardRepository.kt
> +    fun findByTypeNot(boardType: BoardType): List<Board>
이것도 위랑 이름 동일한 형식으로 갈꺼면 findAllByTypeNot은 어때?

2021-07-31 07:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/common/config/QuerydslConfiguration.kt
> +class QuerydslConfiguration(
이거 이름을 JpaConfig로 하는 건 어떨까?? 그리고 만약 아까 위에 CustomRepository를 api 모듈로 옮기면 그냥 WebConfig 하위에 이 설정 그대로 넣어둬도 될 것 같어!!

2021-08-01 04:48 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepositoryCustom.kt
> +import com.devfloor.hongit.core.articleviewcount.domain.QArticleViewCount.articleViewCount
헉 맞네 !! @JoonBro 해결되었습니다 제가 빌드를 안한게 문제였군요 ㅠ

2021-08-01 08:49 UTC, lxxjn0 approved these changes

2021-08-01 08:54 UTC, merged