feat(board): 즐겨찾기 추가 API
dev-floor/untitled-server pull request #69
Opened 2021-08-07 15:17 UTC by hungry-jay

closes #68

2021-08-17 14:04 UTC, lxxjn0 requested changes
구현하느라 수고많았어!! 일단 리뷰 남겨뒀는데 한번 확인해줘~~~ 👍🏼

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            .filter { !it.anonymous }
이건 로그인한 사용자에 따라 익명글이 표시되거나 표시되지 않는 로직이 추가되어야 할 것 같아!! 그 저번 회의때 논의한 부분 참고해서 수정하면 될 듯??
그리고 만약 이렇게 필터링하는 로직이 추가된다면 서비스 메서드 명을 조금 더 구체화시키면 좋을 것 같아!!

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +    val articleId: Long,
이 부분은 왜 articleId로 가기로 했는지 혹시 기억나?? 나 기억이 안나네...

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +    fun modifyAllBoardBookmarks(boardIds: List<Long>, user: User) {
이거 user를 loginUser로 명명 수정하는거 어때? 다른 것들도 차근차근 작업하면서 바꿔나가면 좋을 것 같은게 북마크 수정의 경우 로그인한 사용자 이외는 작업이 불가능하니까 이 명명으로 보여주면 로직을 이해하기가 좀 더 쉽지 않을까 싶어서!!

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/presentation/BoardController.kt
> +        @RequestBody boardIds: List<Long>,
이거 리스트로 받는거 아마 json에서 "1,2,3,4,5,6" 이렇게 콤마로 붙은 문자열로 받으면 알아서 파싱되는 걸로 알고있어!!
프론트쪽에 배열말고 이렇게 붙인 문자열로 달라고 전달해야 할 것 같아!!

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/comment/application/CommentService.kt
> +            .filter { !it.anonymous }
이것도 article이랑 동일하게 고민해보면 될 것 같아!!

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/bookmarkboard/domain/BoardBookmark.kt
> +    name = "board_bookmark",
```suggestion
    name = "board_bookmarks",
```

테이블이라 복수형으로 가야할거 같어!!

2021-08-17 14:04 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/UserRepository.kt
> +fun UserRepository.findByNicknameOrNull(nickname: String): User? = findByNickname(nickname).orElse(null)
다른데서 쓰는걸 봤는데 이걸 interface 안에 companion object로 넣어서 구현하더라고!! 그렇게 수정해보면 좋을 것 같아!! 다른 데서 사용한 건 내가 수정해둘게!!

2021-08-18 15:09 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            .filter { !it.anonymous }
사용자에 따라 - 본인이 본인의 프로필을 보는지 아닌지를 판단하는걸 말하는거지!?

2021-08-18 15:12 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +    val articleId: Long,
흠 뭐지... 나도 기억이 잘 안나는데..?
노션에는 articleId로 되어있네 왜 그랬었는지가 기억이 ㅠ

2021-08-18 15:15 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +    fun modifyAllBoardBookmarks(boardIds: List<Long>, user: User) {
반영했어 ! 근데 CommentController에서 author로 되어있는건 의미상 무방할거같긴한데
그냥 loginUser로 전부 일관성있게 가는거로할까!?

2021-08-18 15:16 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/presentation/BoardController.kt
> +        @RequestBody boardIds: List<Long>,
아그래??? 이것 전달해놓을게 !!

2021-08-18 15:20 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/UserRepository.kt
> +fun UserRepository.findByNicknameOrNull(nickname: String): User? = findByNickname(nickname).orElse(null)
반영해볼게 !!

2021-08-18 23:11 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            .filter { !it.anonymous }
엉엉 맞어!!

2021-08-18 23:11 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +    val articleId: Long,
ㅋㅋㅋ 일단 변경하는걸로 가고 나중에 다시 확인해보자 ㅋㅋㅋㅋㅋ

2021-08-18 23:12 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +    fun modifyAllBoardBookmarks(boardIds: List<Long>, user: User) {
그것도 loginUser로 가도 괜찮을듯?? 그 부분은 author로 가던 loginUser로 가든 상관없을 것 같은데 맞출거면 loginUser로 가도 될 듯?

2021-08-18 23:12 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/presentation/BoardController.kt
> +        @RequestBody boardIds: List<Long>,
이거 내가 잘못봤네 ㅠㅠ 미안
슬랙에는 내가 말해놨어!!

2021-08-19 09:06 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +    fun modifyAllBoardBookmarks(boardIds: List<Long>, user: User) {
반영했음!

2021-08-19 09:57 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            .filter { !it.anonymous }
반영헀어!

2021-08-19 09:58 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/presentation/BoardController.kt
> +        @RequestBody boardIds: List<Long>,
오키오키 ㅋㅋㅋ 괜춘

2021-08-19 09:58 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/comment/application/CommentService.kt
> +            .filter { !it.anonymous }
반영했어!

2021-08-19 09:58 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/bookmarkboard/domain/BoardBookmark.kt
> +    name = "board_bookmark",
반영했어!

2021-08-19 10:07 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/UserRepository.kt
> +fun UserRepository.findByNicknameOrNull(nickname: String): User? = findByNickname(nickname).orElse(null)
companion object가 정적메소드라 생성시점이 더 빨라서
레포지토리 내부의 다른 함수들을 참조 못하는듯한데 혹시 예시 코드 어떤거 참조한거야!?
companion 빼니까 되긴하는듯??

2021-08-19 12:02 UTC, JoonBro approved these changes
고생하셨습니당 질문한개 남겼습니다!

2021-08-19 12:02 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +    val articleId: Long,
변경하기로하고 한게아니라 내가 애초에 개발할때 id로 해놨던거같은데????

2021-08-19 12:02 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +        boardRepository.findAllById(boardIds)
여기서 findAllById 에서(jpa) id를 리스트로 받아서 쓰는거랑 in이나 contains 이런것도 있던데 혹시 차이점 아시나요..?

2021-08-19 12:58 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
> +    val articleId: Long,
그랬던거같은데, 제가 그걸 `articleId`로 변경한 이유가 궁금한듯해요.!
그냥 바꾸진 않았을텐데 그냥 노션보고 바꿨었는지 기억이 안나서요 ㅜ

2021-08-19 13:06 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +        boardRepository.findAllById(boardIds)
contains는 모르겠고 in으로 하게되면 쿼리로 변경될때 `WHERE Id IN (id1, id2, id3)` 이런식으로 변경되는거로 알고있어요 !

`findAllById`는 코드 까보니까 그냥 `findBy` 여러번 쳐주는것이네요 !

둘의 성능면에서의 차이점은 크게 어느정돈지 모르겠는데 In clause로 쳐주게되면 prepared statement? 관련 이슈가 있던거로 아는데 정확히 기억이 안나네요..

2021-08-19 13:08 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +        boardRepository.findAllById(boardIds)
아 in절에서의 아이디의 갯수에 따라 prepared statement를 준비할텐데 그 갯수가 항상 다를테니 적절히 단위를 잘라서 batch?? 할것이 아니라면 사용할때 주의해야하는 것 같아요 !

2021-08-19 13:09 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +        boardRepository.findAllById(boardIds)
그런데 정확하진 않습니다,,, 오래전에 메모해놓은거 보고 다시 이해한거라 ㅠ,,

2021-08-20 08:08 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/UserRepository.kt
> +fun UserRepository.findByNicknameOrNull(nickname: String): User? = findByNickname(nickname).orElse(null)
아 내부에서 다른 함수를 못보는구나.. 내가 이걸 어디서 봤는지 기억이 안나네.. ㅜㅡㅜ 그럼 일단 기존 그대로 두는걸로 하자 ㅎㅅㅎ

2021-08-20 12:42 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/board/application/BoardService.kt
> +        boardRepository.findAllById(boardIds)
아 감사합니다!!

2021-08-26 08:19 UTC, hungryjayy commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/UserRepository.kt
> +fun UserRepository.findByNicknameOrNull(nickname: String): User? = findByNickname(nickname).orElse(null)
반영했어!

2021-09-05 04:11 UTC, lxxjn0 approved these changes

2021-09-05 06:09 UTC, merged