feat(board): 게시글 목록 조회 API
dev-floor/untitled-server pull request #78
Opened 2021-08-19 15:16 UTC by JoonBro

스크린: 게시판 > 게시글 목록 조회

스크린: 프로필 & 마이페이지 > 작성한 게시글 목록 조회
     * 로그인 본인의 경우 익명글 포함

스크린: 프로필 & 마이페이지 > 좋아요한 게시글 목록 조회

2021-08-26 07:56 UTC, hungryjayy reviewed
고생하셨습니다 ! 바뀔거 크게 없는거같아요

2021-08-26 07:56 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +
lint 적용이 안되어있는 것 같아요!

2021-08-26 07:56 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleSortType.kt
> +    FAVORITE,
각 key에 해당하는 value값(string) 설정 해야하는 것 아닌가요!?

2021-08-26 07:56 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
여기 Favorite으로 sorting인데 혹시 `Sort.by("createdAt")` 부분도 의도하신 것인가요!?

2021-08-26 07:56 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            ?.let { articleRepository.findAllByAuthorAndAnonymousFalse(it, pageRequest) }
그냥 이거 하나의 서비스로 처리했었는데, 바꾸신 부분 보니까 나누는게 훨씬 좋아보이네요.!

2021-08-26 07:56 UTC, hungryjayy commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleControllerDocs.kt
> +                RestDocumentationRequestBuilders.get("$ARTICLE_API_URI")
이렇게 수정해도 무방하다고 나오네요 !
```suggestion
                RestDocumentationRequestBuilders.get(ARTICLE_API_URI)
```

2021-09-14 02:17 UTC, JoonBro commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleControllerDocs.kt
> +                RestDocumentationRequestBuilders.get("$ARTICLE_API_URI")
수정했습니다!

2021-09-14 02:18 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            ?.let { articleRepository.findAllByAuthorAndAnonymousFalse(it, pageRequest) }
어.. 저 형꺼보고 하나로 처리하는걸로 바꿨습니다...ㅋㅋㅋ

2021-09-14 02:20 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
좋아요 개수가 같을때 생성 기준으로 정렬될 수 있도록 선정렬시킬려고한건데 확실하지 않아서 favorite에만 해놓고 viewcount에는 안한 버전으로 올려져있습니다! 어떤게 맞는걸까요?

2021-09-14 02:21 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +
적용했습니다.

2021-09-14 02:25 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleSortType.kt
> +    FAVORITE,
수정했습니다!

2021-09-14 12:58 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
아 그런거였군요..! 저부분만 그랬어서 잘 몰랐습니다.
혹시 `findBy~~~ ` 이 부분에서 `OrderBy`와 같은 형태를 사용하지 않으신 이유가 있을까요!?

2021-09-14 13:17 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            ?.let { articleRepository.findAllByAuthorAndAnonymousFalse(it, pageRequest) }
아 그렇네요.!! 컨트롤러 분기문이 없어졌네요
근데 혹시 현재는 자기자신의 경우 "익명이 아닌" 모든 글을 보는건 없어진건가요!?

2021-09-15 07:32 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
커스텀 함수라서 일단 좋아요순으로 정렬하는거고 생성일자 기준은 뭔가 디폴트느낌이라 명명에서  제외했는데 있는게 나을까요?

2021-09-15 07:33 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            ?.let { articleRepository.findAllByAuthorAndAnonymousFalse(it, pageRequest) }
머지하면서 꼬인거같아요! 형이 닉네임으로 조회로 변경했었어서 수정하겠습니다!

2021-09-15 09:45 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
아, 제 말의 의도는 커스텀 메소드 만드신 부분에 `OrderBy` 로 쿼리 날리시는거로  querydsl로 작성하신거같은데 그 부분에 `createAt` 조건도 추가를 하면 현재의 동작과 달라서 의도하신건지, 혹은 다른 이유가 있는지였습니다!

2021-09-15 09:46 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            ?.let { articleRepository.findAllByAuthorAndAnonymousFalse(it, pageRequest) }
그렇군요.! 
develop 브랜치 참고하시고 "자기자신의 글 조회" 의 경우는 익명글도 모두 노출시켜주도록 추가되면 될 것 같습니다!

2021-09-19 10:06 UTC, lxxjn0 requested changes
일단 코드 로직 부분이랑 전체적으로 리뷰 남겼는데 코드 더 깔끔하게 수정 할 수 있을 것 같아서 다시 확인해보면 좋을 듯요!!
한번만 더 수정하고 리뷰 남길게요 ㅎㅅㅎ

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +    ): List<ArticleFeedResponse> {
```suggestion
    fun showAllByBoardId(
        boardId: Long,
        page: Int,
        listSize: Int, // 페이지에서 보여질 게시글 개수
        sort: ArticleSortType?,
        options: List<Long>?
    ): List<ArticleFeedResponse> {
```

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +        val pagination = PaginationResponse(page, range, articleRepository.countAllByBoard(board))
따로 Response 만들지 말고 ArticleFeedResponse에서 프로퍼티 값으로 page, totalArticleCount로 가져갈 수 있도록

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +    ): List<ArticleFeedResponse> =
```suggestion
    fun showAllByUserId(
        @RequestParam userId: Long,
        @RequestParam page: Int,
        @RequestParam range: Int,
    ): List<ArticleFeedResponse> =
```

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +    ): List<ArticleFeedResponse> =
```suggestion
    fun showAllByBoardId(
        @RequestParam boardId: Long,
        @RequestParam page: Int,
        @RequestParam range: Int,
        @RequestParam(required = false) sort: ArticleSortType?,
        @RequestParam(required = false) options: List<Long>?,
    ): List<ArticleFeedResponse> =
```

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
>  ) {
여기 필요없는 공백 라인 삭제 ㅎㅅㅎ

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByViewCount(board, pageRequest).map {
이거랑 바로 아래 FAVORITE에서의 메서드랑 둘 다 repository의 메서드니깐 SortBy보다 OrderBy가 좀 더 낫지 않을까?

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                val pageRequest: PageRequest = PageRequest.of(page, pageSize, Sort.by("createdAt"))
변수명으로 클래스 타입이 추측 가능해서 굳이 타입 명시 안해도 될 듯?

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                }
```suggestion
                articleRepositoryCustom.findAllByBoardSortByViewCount(board, pageRequest)
                    .map {
                        ArticleFeedResponse(
                            article = it,
                            articleOptions = articleOptionRepository.findAllByArticle(it),
                            articleFavorites = articleFavoriteRepository.findAllByArticle(it),
                            page = page,
                            totalArticleCount = articleRepository.countAllByBoard(board)
                        )
                    }
```

map을 한 라인 내리면 코드가 좀 더 보기 좋은 것 같아서 이건 추천으로 달아둘게

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
여기도 ㅎㅅㅎ

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            else -> throw IllegalArgumentException()
정렬 기준이 없이 조회할 수도 있어야 하는데 여기서 exception을 터트리면 안되지 않어?

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            .let { articleRepository.findAllByAuthor(it, pageRequest) }
```suggestion
        val articles = articleRepository.findAllByAuthor(user, pageRequest)
```

이거랑 똑같지 않나?

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            }
이거 loginUser 받고 user 본인인지 여부에 따라 익명글 필터링 해야하지 않아? 지금은 모든 글에 대해 다 필터링하는거 같은데?

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +        val user: User = userRepository.findByIdOrNull(userId)
전체적으로 변수마다 타입 선언을 해뒀는데 정말 애매한거 말곤 굳이 다 붙일 필요는 없을 것 같어 ㅎㅅㅎ

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +    fun showAllByFavoritedUserId(userId: Long, page: Int, pageSize: Int): List<ArticleFeedResponse> {
```suggestion
    fun showAllByFavoritedUserId(favoritedUserId: Long, page: Int, pageSize: Int): List<ArticleFeedResponse> {
```

변수명 이렇게 두면 좀 더 코드 읽을 때 편할 것 같어

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            }
```suggestion
        val articles = articleFavorites
            .let {
                articleRepository.findAllByIdIn(it.map { it.id }, PageRequest.of(page, pageSize))
            }
```

한 군데서만 쓰인다면 그냥 인라인처럼 바로 넣어도 괜찮은거 같어

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
>              }
```suggestion
        val articleFavoriteIds = articleFavoriteRepository.findAllByUser(user)
            .map { it.id }
        val articles = articleRepository.findAllByIdIn(articleFavoriteIds, PageRequest.of(page, pageSize))

        return articles.content
            .map {
                ArticleFeedResponse(
                    article = it,
                    articleOptions = articleOptionRepository.findAllByArticle(it),
                    articleFavorites = articleFavoriteRepository.findAllByArticle(it),
                    page = page,
                    totalArticleCount = articleRepository.countAllByIdIn(articleFavoriteIds)
                )
            }
```

이거 다시 전체적으로 보니깐 articleFavoriteIds만 사용하는 것 같은데 코드가 너무 불필요한 로컬 변수들이 많은 것 같아.
내가 한번 수정해봤는데 참고해봐바

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +            .also { log.info("boardId = $boardId, sort = $sort, options = $options") }
```suggestion
    fun showAllByBoardId(
        @RequestParam boardId: Long,
        @RequestParam page: Int,
        @RequestParam pageSize: Int,
        @RequestParam(required = false) sort: ArticleSortType?,
        @RequestParam(required = false) options: List<Long>?,
    ): List<ArticleFeedResponse> =
        articleService.showAllByBoardId(boardId, page, pageSize, sort, options)
            .also { log.info("boardId = $boardId, sort = $sort, options = $options") }
```

이것도 아래 서비스의 메서드랑 한번에 이해하기 쉽게 순서 맞춰주기만 해도 좀 더 좋을 것 같아서 추천해봄요

2021-09-19 10:06 UTC, lxxjn0 commented on hongit-api/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
> +        |===
snippet 파일 인덴트 수정되면 정상적으로 문서 생성이 안되서 이건 다시 원래대로 복구해야 할 듯

2021-09-25 12:56 UTC, JoonBro reviewed
코멘트 안보이고있었나??

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByViewCount(board, pageRequest).map {
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                val pageRequest: PageRequest = PageRequest.of(page, pageSize, Sort.by("createdAt"))
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
>  ) {
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                }
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            else -> throw IllegalArgumentException()
정렬기준이 없다는게 디폴트로 생성일자 기준이라 첫번째 케이스로 분류를 한거거든? 무조건 받는다는 얘긴데 뭐가더나을까?

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            .let { articleRepository.findAllByAuthor(it, pageRequest) }
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +    fun showAllByFavoritedUserId(userId: Long, page: Int, pageSize: Int): List<ArticleFeedResponse> {
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +        val user: User = userRepository.findByIdOrNull(userId)
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            }
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
>              }
반영완료

2021-09-25 12:56 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +            .also { log.info("boardId = $boardId, sort = $sort, options = $options") }
반영완료

2021-09-26 02:29 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +                articleRepositoryCustom.findAllByBoardSortByFavorite(board, pageRequest).map {
수정했습니다! 일단 저 부분은 두 테이블 조인이 필요한 상황이라 querydsl을 사용하는 상황이라 저 조건을 쿼리에 추가하였습니다

2021-09-30 13:02 UTC, lxxjn0 requested changes
리뷰 빠르게 남겼는데 확인해주세요~~ ㅎㅅㅎ

2021-09-30 13:02 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +            else -> throw IllegalArgumentException()
정렬기준이 없다는 말은 `sort`가 `null`로 들어온다는 건데 그 상황이 else 문으로 들어오지 않아?

컨트롤러에서도 default 값을 할당해주는 코드가 없고 여기 서비스에서도 없어서 프론트에서 디폴트로 사용할 경우 `sort`값이 `null`로 넘어오지 않을까?

2021-09-30 13:02 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
> +        }
```suggestion
        return articles.content
            .filter { loginUser.hasSameId(user) || !it.anonymous } // 내부 predicate 로직을 따로 메서드로 뽑아도 좋고
            .map {
                ArticleFeedResponse(
                    article = it,
                    articleOptions = articleOptionRepository.findAllByArticle(it),
                    articleFavorites = articleFavoriteRepository.findAllByArticle(it),
                    page = page,
                    totalArticleCount = articleRepository.countAllByAuthor(user)
                )
            }
```

이렇게 수정하면 좀 더 펀.쿨.섹시해 보이는데 어떤지여??

2021-09-30 13:02 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +            .also { log.info("boardId = $boardId, sort = $sort, options = $options") }
이렇게 로그를 찍으면 나중에 어디서 어떤 시점에 필요해서 찍은 로그인지 확인하기가 어려울 것 같어. 좀 더 추적 가능한 의미있는 로그로 남기면 좋을 듯요!!

2021-09-30 13:02 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +            .also { log.info("userId = $userId, type = $type") }
요것도 마찬가지이

2021-10-02 13:25 UTC, lxxjn0 approved these changes
마지막 리뷰일 것 같아서 추가해둔 부분만 수정해주면 따로 수정할 부분은 없을 것 같소오~~ 수고했으요 👍🏼

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
>      }
```kotlin
    @Transactional(readOnly = true)
    fun showAllByBoardId(
        boardId: Long,
        page: Int,
        pageSize: Int,
        sort: ArticleSortType?,
        options: List<Long>?,
    ): List<ArticleFeedResponse> {
        val board = boardRepository.findByIdOrNull(boardId)
            ?: EntityNotFoundException.notExistsId(Board::class, boardId)

        return when (sort) {
            ArticleSortType.VIEW_COUNT ->
                articleRepositoryCustom.findAllByBoardOrderByViewCount(board, PageRequest.of(page, pageSize))
            ArticleSortType.FAVORITE ->
                articleRepositoryCustom.findAllByBoardOrderByFavorite(board, PageRequest.of(page, pageSize))
            else ->
                articleRepository.findAllByBoard(board, PageRequest.of(page, pageSize, Sort.by("createdAt")))
                    .content
        }.map {
            ArticleFeedResponse(
                article = it,
                articleOptions = articleOptionRepository.findAllByArticle(it),
                articleFavorites = articleFavoriteRepository.findAllByArticle(it),
                page = page,
                totalArticleCount = articleRepository.countAllByBoard(board)
            )
        }
    }
```

이 코드 이렇게 짜면 좀 더 섹시한 것 같습니다. 준형님

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
>      }
이 코드들도 코드의 문맥상 아래처럼 변수 선언부랑 띄워주면 보다 코드가 가독성이 좋을 것 같아!!

![image](https://user-images.githubusercontent.com/48052622/135718039-76d95057-134e-444b-a75e-988e0319a3c8.png)

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleRepositoryCustom.kt
>  }
```suggestion
interface ArticleRepositoryCustom {
    fun findByFavoriteTopFive(): List<Article>
    
    fun findByViewCountTopFive(): List<Article>
    
    fun findAllByBoardOrderByViewCount(board: Board, pageRequest: PageRequest): List<Article>
    
    fun findAllByBoardOrderByFavorite(board: Board, pageRequest: PageRequest): List<Article>
}
```

이것도 개인적인 취향인건지 잘 모르겠는데 인터페이스이다보니 코드의 선언이 더 잘 보이게 사이에 공백을 주는게 더 좋아보이긴 하는데 어떠신지???

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleRepositoryCustomImpl.kt
> +            .orderBy(articleViewCount.count.desc())
```suggestion
    override fun findAllByBoardOrderByViewCount(board: Board, pageRequest: PageRequest): List<Article> {
        return jpaQueryFactory
            .selectFrom(article)
            .join(articleViewCount).on(article.eq(articleViewCount.article))
            .where(article.board.eq(board))
            .orderBy(articleViewCount.count.desc())
```

여기 클래스 코드들에 select 부분 한칸 내리는건 어때? 그럼 좀더 코드를 가로로 읽을 필요 없이 세로로 읽어내려가기에 한번에 잘 보이는 것 같아서!!

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
> +        .also { log.info("[ArticleController.showByArticleId] 게시글 조회 완료 - , response: $it") }
```suggestion
        .also { log.info("[ArticleController.showByArticleId] 게시글 조회 완료 - response: $it") }
```

아래 다른 로그도 그런데 이 ,는 의도한 콤마?인건가??

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepository.kt
>  }
이 부분도 메서드 선언부랑 마찬가지라서 사이에 공백이 있는게 좋을 것 같어!!

2021-10-02 13:25 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/articlefavorite/domain/ArticleFavoriteRepository.kt
> +    fun findAllByUser(favoritedUser: User): List<ArticleFavorite>
여기도오~~~

2021-10-02 14:04 UTC, merged