test(board): 게시글 좋아요, 댓글 좋아요, 홈 화면 Test
dev-floor/untitled-server pull request #81
Opened 2021-08-28 10:01 UTC by hungry-jay

close #76

2021-09-21 14:34 UTC, lxxjn0 requested changes
Service 테스트 코드에 대한 리뷰는 전부 다 동일해서 한 군데만 남겨뒀고, 추가적으로 컨트롤러 코드에 대한 수정도 필요할 것 같아서 그것도 리뷰로 남겨뒀어.
LoginUser에 대한 처리가 없어서 문서화 테스트 코드도 정상적으로 통과하지 않을 것 같은데 이 부분도 한번 확인해봐죠!! 리뷰 넘 늦어서 미안.. ㅠㅠ

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
이런 서비스 테스트를 할 때는 mocking 하지 말고 실제 데이터를 저장하고 테스트하는게 좋은 것 같아.

ArticleFavoriteService의 create 메서드를 보면 마지막에  articleFavoriteRepository.save 를 호출하고 그 id를 반환하는데 이걸 그냥 모킹해두면 해당 로직을 테스트하는 의미가 거의 없는 것 같아.

해당 서비스의 로직은 articleId에 해당하는 article이 존재할 때, 그 데이터와 로그인 유저를 기반으로 ArticleFavorite을 생성하고 생성된 id를 반환하는 거잖아. 만약 articleId에 해당하는 article이 존재하지 않을 경우는 예외가 발생하고!

그럼 테스트 해야하는 시나리오는

1. articleId로 조회를 하고 이걸 기반으로 저장했을 때, articleFavorite에 저장이 정상적으로 되었는지, 그리고 저장된 데이터의 id가 정상적인지
2. articleId로 조회했을 때 존재하지 않을 경우 예외가 발생하는지

이렇게 두 가지인거 같아. 위 테스트는 그런 부분이 다 모킹되어 있어서 서비스의 실제 내부 로직을 테스트 하긴 부족한 것 같아

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
아래에 docs 말고 대다수의 service 테스트가 이런 형식으로 보여서 여기 코멘트랑 다 동일한 관점으로 한번 확인해주면 좋을 것 같아!!

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +        val request: String = ARTICLE_FAVORITE_CREATE_REQUEST_1.toString()
이거 toString말고 내가 따로 Utils에 convertToJson 인가? 그 메서드 만들어뒀는데 그거 사용하면 될 것 같아!!

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `create - 게시글 좋아요 생성 문서화`() {
이거 테스트 통과해?? loginUser에 대한 생성 조건이 없어서 터지지 않나?
문서화에 authorization 부분 필요할 것 같아!!

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `destroy - 게시글 좋아요 삭제 문서화`() {
이거 controller 보니깐 requestParam으로 받던데 삭제 요청할 때 PathParam으로 하지 않아?
이 부분 컨트롤러 코드도 한 번 확인해보면 좋을 것 같아!!

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/CommentFavoriteControllerDocs.kt
> +internal class CommentFavoriteControllerDocs {
여기도 컨트롤러 코드 전체적으로 PathParam이 아니라 RequestParam으로 ID를 받는데 확인이 필요할 것 같아!!

2021-09-21 14:34 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/CommentFavoriteControllerDocs.kt
> +internal class CommentFavoriteControllerDocs {
또 마찬가지로 LoginUser에 대한 처리가 없어서 문서화 코드가 터질거 같은데 이것도 확인해봐야 할 것 같어!!

2021-09-21 15:00 UTC, lxxjn0 requested changes

2021-09-21 15:00 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
![image](https://user-images.githubusercontent.com/48052622/134195334-a4bf6490-579e-4d75-bf78-2fe219f9e9bf.png)

추가로 이 로직에 대한 서비스 코드를 확인해봤는데 마지막에 굳이 run { id } 를 할 필요 없이 .id로 가면 될 것 같아!!
`let { }.id` 이런 식으로!! 이거말고 다른 commentFavorite 쪽도 그런 것 같아서 한 번 확인 부탁할게!!

2021-09-21 15:02 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
아 그리고 추가적으로 우리가 테스트 코드 네이밍을 기본적으로 한글로 하고 있었는데 이건 맞추는게 좋지 않을까? 따로 영어로 써야하는 이유가 있으면 나중에 슬랙에서 공유해줘도 괜찮을 것 같어!!

2021-09-21 17:12 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
추가로 서비스 테스트에서 TestFixture 값을 가져와서 쓰는 경우가 많은데 만약 가져온 값이 테스트 중에 변경이 일어나는 경우 다른 테스트에 영향을 미칠 수 있거든.

그래서 문서화 테스트처럼 로직을 타지 않는 경우만 쓰는게 좋을 것 같고 서비스 테스트는 그냥 셋업 메서드 같은 곳에서 해당 서비스 테스트만을 위한 값을 만들어서 테스트하는게 좋은 것 같아!!
테스트는 최대한 독립적으로 운용하는게 좋은데 이런 방법은 전역변수를 테스트에 사용하는 모습과 같아서 로컬 변수를 따로 만들어 쓰는게 좋을 것 같아!!

2021-09-23 08:32 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
첫번째 >
2번 시나리오에 대한걸 추가하면 될것같다는말인거지!?
라이브러리는 jupiter을 사용하지 말자는거야!? 그러면 BeforeEach나 Test같은 것들을 대체할만한것들이 assertj에 다 있는건가!?

2021-09-23 08:35 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
두번째 > 반영했어!
세번째 > 테스트 네이밍이 한글로 되어있던거는 몰랐었긴 했는데, 혹시 따로 한글로 사용해야 하는 이유가 있어?? 테스트코드 제목정도의 영어라면 테스트코드 자체를 확인하거나 전반적인 코드 스펙을 확인하거나 하는 차원에서도 크게 혼란을 줄거같진 않다고 생각해서.!

2021-09-23 08:36 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
네번째 > 반영할게 !

2021-09-23 08:45 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `destroy - 게시글 좋아요 삭제 문서화`() {
이건 슬랙에 남겼어!

2021-09-23 08:50 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +        val request: String = ARTICLE_FAVORITE_CREATE_REQUEST_1.toString()
반영했어!

2021-09-23 08:55 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/CommentFavoriteControllerDocs.kt
> +internal class CommentFavoriteControllerDocs {
https://github.com/dev-floor/hongit-server/pull/81#discussion_r713097667
이 PR에서 이야기하자!

2021-09-23 08:57 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `create - 게시글 좋아요 생성 문서화`() {
이전에 Application 돌려놓고 에러나서 안된다고했던 떄가 저거 작성했을떄였떤거같은데, 그때 뭔가 잘못되었나 싶어서 확인을 제대로 못하고 넘어간듯 ㅜ
혹시 저 부분은 아래 이미지에 나온 부분처럼 하면 되는거야!?

![image](https://user-images.githubusercontent.com/49271821/134479949-0dc19e29-98c3-421b-bcbe-8ab6fe59f4f7.png)

2021-09-23 13:38 UTC, JoonBro commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `create - 게시글 좋아요 생성 문서화`() {
네네 저도 아래처럼 했습니다!

2021-09-23 13:39 UTC, JoonBro approved these changes
제가 테스트코드 관련해서 잘 몰라서 저도 리뷰받으면서 공부해야되는 상황이라... ㅜ 제가 드릴 의견은 없을거같습니다! 준영이 리뷰 보면서 저도 계속 보고있겠습니다!

2021-09-24 09:04 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `create - 게시글 좋아요 생성 문서화`() {
참고하겠습니다!

2021-09-25 11:07 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
아 첫번째에서 BeforeEach 이런거 말구 assertion 부분에서!! 아마 assertj가 jupiter보다 assertion 부분 코드가 더 다양해서 쓰는 걸로 알고 있거든. 그래서 assertion 부분만 사용하지 말잔거였어!!

세번째는 그냥 다 한국인이고 한글이 파악하긴 더 편리해서 제안한거긴 한데 이건 뭐 팀에서 같이 이야기해보고 한번 정리하면 좋을 것 같아!! 테스트 코드가 뭘 하는지 알아보려고 했는데 영어다 보니 한글보단 한눈에 잘 안 들어와서 제안한 이야기였어!! ㅎㅅㅎ

2021-09-25 11:08 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleFavoriteControllerDocs.kt
> +    internal fun `destroy - 게시글 좋아요 삭제 문서화`() {
확인완료!

2021-09-25 11:08 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/CommentFavoriteControllerDocs.kt
> +internal class CommentFavoriteControllerDocs {
확인완료!

2021-09-25 11:13 UTC, lxxjn0 requested changes
이거 리뷰 봤는데 아직 다 반영이 안된 부분들이 있는 것 같아서 그거 반영하고 말해주면 다시 리뷰 달아둘게!!

2021-09-25 11:13 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +        ?.let { commentFavoriteRepository.save(CommentFavorite(it, user)) }?.id
```suggestion
        ?.let { commentFavoriteRepository.save(CommentFavorite(it, user)) }
        ?.id
```

이건 어때? let 뒤에 붙어있으니깐 한눈에 잘 안 들어오는것 같아서!!

2021-09-25 11:13 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/board/domain/Board.kt
>  ) : BaseEntity() {
이거 entity에 id는 젤 아래로 내리자!! 기존에 named argument로 생성 안한 객체들(예로 Board(title, type)과 같은)이 에러가 발생할 수 있어서 전체적으로 id를 젤 마지막 위치로 내가 다 옮겨뒀어!!

2021-09-25 11:15 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
오키 반영하겠슴!

2021-09-26 13:36 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
> 추가로 서비스 테스트에서 TestFixture 값을 가져와서 쓰는 경우가 많은데 만약 가져온 값이 테스트 중에 변경이 일어나는 경우 다른 테스트에 영향을 미칠 수 있거든.

> 그래서 문서화 테스트처럼 로직을 타지 않는 경우만 쓰는게 좋을 것 같고 서비스 테스트는 그냥 셋업 메서드 같은 곳에서 해당 서비스 테스트만을 위한 값을 만들어서 테스트하는게 좋은 것 같아!!
테스트는 최대한 독립적으로 운용하는게 좋은데 이런 방법은 전역변수를 테스트에 사용하는 모습과 같아서 로컬 변수를 따로 만들어 쓰는게 좋을 것 같아!!


홈화면 조회 바꿔보려하니까 수십개를 다시 구현해야해서, 사이드이펙트없는 조회성 메소드 테스트에는 그냥 사용하도록 정하는건어떨까?

2021-09-26 13:38 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +        ?.let { commentFavoriteRepository.save(CommentFavorite(it, user)) }?.id
반영했어!

2021-09-26 13:43 UTC, hungry-jay commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/board/domain/Board.kt
>  ) : BaseEntity() {
반영했어~

2021-09-30 16:30 UTC, lxxjn0 requested changes
리뷰 추가로 남겼는데 이거 한번만 더 확인해보고 코드 반영하면 좋을 것 같아서 request change로 해둘게!!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
이거 AlreadyExistsException은 이번에 새로 추가한거야??
커스텀 exception을 너무 케이스마다 만들면 오히려 추적하기 힘들고 과한 것 같아서 그냥 IllegalArgumentException으로 처리하는게 어때? 메시지에 중복에 대한 메시지를 담고!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/AlreadyExistsException.kt
> +            throw AlreadyExistsException("해당 ${clazz.simpleName}이(가) 이미 존재합니다.")
추가적으로 Already 예외는 없는게 좋을 것 같은데 이 코드만 보자면 해당 예외 메시지는 어떤 id에 대한 엔티티가 이미 존재했는지를 알 수가 없는 것 같아.

만약 출력된다면 `해당 Article이(가) 이미 존재합니다.` 이렇게 예외가 발생할건데 정보가 너무 적고 정확히 예외 상황에 대한 명확한 에러 메시지는 아닌 것 같아. 조금 모호한 느낌?
만약 이걸 쓸거면 로깅이라도 더 많은 정보로 남겨줘야 하는데 그것도 안되있는거 같아서 만약 쓸 거라면 좀 더 구체적인 정보가 담기면 좋을 것 같아.

물론 나의 전체적인 의견은 해당 익셉션은 굳이 커스텀으로 뽑을 필요는 없을 것 같고 Illegal로 처리하는게 좀 더 편하고 관리하기 용이할 거 같아!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
이건 위에 어노테이션으로 @InjectMocks 인가? 그걸로 처리하면 여기서 안해줘도 될 것 같아!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        )
이거 보니깐 board는 article을 생성할 때만 쓰이고 articleFavorite은 하나의 테스트 메서드에서만 쓰이고 있어서 이 두 변수는 클래스 프로퍼티가 아니라 각각 위치에 해당하는 로컬 변수로 처리하는게 좀 더 나은 코드일 것 같아!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        board = Board(id = 0, title = "course", type = BoardType.COURSE_BOARD)
이건 뭐 크게 중요한 건 아니지만 DB에 id가 0으로 저장되는 일은 없으니깐 1로 처리하는게 좀 더 테스트 상황에 적절하지 않을까? 하는 생각 ㅎㅎㅎ

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
이거 예외 발생 테스트의 경우에는 assertJ에서 assertThatIsThrownBy 인가? 그 메서드 쓰면 될거야!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/commentfavorite/CommentFavoriteServiceTest.kt
> +        commentFavoriteService = CommentFavoriteService(commentRepository, commentFavoriteRepository)
이것도 이전 리뷰랑 동일!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/commentfavorite/CommentFavoriteServiceTest.kt
> +        commentFavorite = CommentFavorite(comment, user)
이것도 이전 리뷰랑 동일!!

2021-09-30 16:30 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/TestFixtures.kt
> +        )
이건 뭐 굳이 개행하지 않아도 될 것 같아보여서 글만 남겨둘게 ㅋㅋㅋ

2021-10-01 01:43 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
추적하기 힘들고 과하다는게 혹시 무슨 의미야??

`IllegalArgumentException` 라고 물론 표현할 수 있지만, 만약 그런 맥락에서 보면 모든 exception을 세분화할 필요 없이 Illegal로 퉁치면 되는거 아니야?

 `AlreadyExistsException` 라고 세분화해서 정해놓으면 추후에 중복요청에 대해 처리할때 재사용성도 생각해볼 수 있을거같고, 재사용성 문제가 아니더라도 손해될게 없을거라고 생각되는데 어떤 부분에서 안좋을지 궁금해.

2021-10-01 01:44 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/AlreadyExistsException.kt
> +            throw AlreadyExistsException("해당 ${clazz.simpleName}이(가) 이미 존재합니다.")
"중복이 불가능함"에 대한 메시지를 남기는거니까 충분하다고 생각했는데, 혹시 어떻게 더 많은 정보를 남겨줄 수 있을까??

2021-10-01 01:47 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
@lxxjn0 여기도 확인해주면 좋을거같아~

2021-10-01 01:50 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
내가 아직 스프링을 잘 몰라서 그러는데! 정확하게 설명해줄수있어?

2021-10-01 01:52 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        )
articleFavorite은 로컬 변수로 처리가 가능한데 board는 어떻게 할 수 있는거야?
article 변수가 모든 메소드에서 필요하니까 board도 여기에 선언해야 하지 않아??

2021-10-01 01:52 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        board = Board(id = 0, title = "course", type = BoardType.COURSE_BOARD)
반영할게~

2021-10-01 01:54 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
찾아보니까 없던데 어떤건지 정확하게 말해줄수있을까??
변경하면서 얻는 이점에 대해서도 설명해주면 좋을것같아!

2021-10-01 01:54 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/commentfavorite/CommentFavoriteServiceTest.kt
> +        commentFavoriteService = CommentFavoriteService(commentRepository, commentFavoriteRepository)
확인했어!

2021-10-01 01:54 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/commentfavorite/CommentFavoriteServiceTest.kt
> +        commentFavorite = CommentFavorite(comment, user)
확인했어!

2021-10-01 01:55 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/TestFixtures.kt
> +        )
반영할게

2021-10-01 12:38 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
이것도 아마 내가 짠 테스트 코드에 있을거야!
따로 이점에 대해서는 잘 모르겠는데 저번에 assertion 관련 테스트 코드는 assertj 라이브러리로 통합하자는 이야기랑 내가 제안한 걸 사용하면 저렇게 따로 코드가 분리되는 일 없이 한 번에 처리가 가능하거든!!

나는 개인적으로 그러긴 했는데 이건 내가 말한 테스트 코드를 보면 좀 더 직관적이라고 느껴질 것 같아!!

2021-10-01 12:39 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        )
그니깐 board를 클래스 변수가 아니라 setUp 내에서의 로컬 변수로!! 그럼 상관없지 않아??

2021-10-01 12:39 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
그거 내가 작성한 코드들 보면 저 어노테이션 쓴 게 있을건데 한번 참고해바바!! 아마 문서화 테스트에서도 썼던 것 같어

2021-10-01 12:42 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/AlreadyExistsException.kt
> +            throw AlreadyExistsException("해당 ${clazz.simpleName}이(가) 이미 존재합니다.")
해당 코드가 사용된 지점을 보면 어떤 파라미터가 넘어왔고 그 파라미터에 해당하는 특정한 인스턴스(데이터)가 없다는 말인데 위의 메시지만 남겨두면 우리가 나중에 추적이 불가능하잖아.
추후 해당 익셉션이 어떠한 파라미터를 받아서 발생했는지 파악하기 쉽도록 메시지가 작성되야 한다는 말이었어!!

위에 리뷰단 코드를 예로 들면 특정한 comment와 user를 넘겨서 commentFavorite이 존재하는 지 검색했는데 존재하지 않았다는 거잖아. 그럼 만약 이 상황이 비즈니스적으로 문제가 될 만한 상황이라면 예외를 추적하면서 파악을 해야하는데 어떠한 comment였는지, user였는지에 대한 정보가 없다는 말이었어!!

2021-10-01 12:42 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
지금 AlreadyExistsException이라는 커스텀 익셉션을 발생시켜서 내부에서 어떤 처리가 일어나?
코드를 보기론 예외 메시지를 담아서 그냥 예외를 발생하고 그걸 AdviceController에서 처리하는 것 말곤 다른 로직을 안타지 않어?
이런 처리는 기존에 익셉션으로도 충분히 처리 가능한 로직이라서 그렇게 생각했어.

만약 여기서 AlreadyExistsException이 발생해서 상위에서 이걸 catch해서 뭐 디비에 추가적인 처리를 한다거나 다른 서비스에 메시지를 보낸다거나 그런 추가적인 로직이 필요하면 커스텀 익셉션이 적절하다고 생각하는데 여기선 그런 용도가 아닌 것 같아서!
이런 상황에서도 커스텀 예외를 만든다면 우리가 지금 추가로 만들어야 하는 커스텀 익셈션이 훨씬 더 많을 것 같아.

뭔가 말이 구구절절이 됐는데 요약하자면 내가 생각하는 커스텀 익셉션을 사용해야 하는게 적절할 것 같은 상황은 해당 커스텀 익셉션만을 인식해서 그에 해당하는 다른 처리(로직)을 태워야 하는 상황일 경우 더 유의미하게 사용할 수 있을 것 같다는 이야기였어!!

2021-10-01 15:05 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
> 그냥 예외를 발생하고 그걸 AdviceController에서 처리하는 것 말곤 다른 로직을 안타지 않어?

이건 어디에서나 그렇지 않아? 지금의 서비스 상황에서는 그냥 모든 예외에서 예외를 발생시키고 끝 아닌가??

> 만약 여기서 AlreadyExistsException이 발생해서 상위에서 이걸 catch해서 뭐 디비에 추가적인 처리를 한다거나 다른 서비스에 메시지를 보낸다거나 그런 추가적인 로직이 필요하면 커스텀 익셉션이 적절하다고 생각하는데 여기선 그런 용도가 아닌 것 같아서!
이런 상황에서도 커스텀 예외를 만든다면 우리가 지금 추가로 만들어야 하는 커스텀 익셈션이 훨씬 더 많을 것 같아.

상위에서 catch할수가 있어? 에러 throw는 항상 다운스트림 아니야??
내가 작성한 용도는 그냥 단순하게 exception 파악을 용이하게하기 위해서였던거야.

덧붙여서 내가 궁금한건, 해당 익셉션을 세분화함으로써 추적이 어떻게 힘들어지고 과해지는지가 궁금했어. 내가 작성한 코드로 인해서 안 좋을 점이 뭔지가 명확하게 이해가 안돼

2021-10-01 15:06 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/AlreadyExistsException.kt
> +            throw AlreadyExistsException("해당 ${clazz.simpleName}이(가) 이미 존재합니다.")
이건 위에서 이야기하면 좋을거같아 !

2021-10-01 15:08 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
당연히 나도 참고를 해보긴 했는데 에러가 나더라고 !

그래서 어떤 점에서 리뷰를 단건지 명확하게 이야기해주면 나도 반영할때 참고가 가능할거같아서 !

2021-10-01 15:13 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        )
아 그걸 말한거면 그건 되지 ! 반영할게~

2021-10-01 15:17 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
> 이것도 아마 내가 짠 테스트 코드에 있을거야!

리뷰를 할때는 리뷰를 남긴 이유가 무엇인지, 뭘 참고해야하는지를 명확하게 말해주면 좋을 것 같아.

> assertion 관련 테스트 코드는 assertj 라이브러리로 통합하자

이것도 나는 그냥 넘어가긴 한건데, 이거는 무슨 이유에서야?
찾아보니까 지원해주는게 더 많다 정도로만 나오던데, 혹시 더 명확한 이유가 있을까?

2021-10-01 15:18 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
이런 부분도, 리뷰를 해주는 입장이면 조금 더 명확하게 해주면 좋을 것 같아 !

2021-10-01 15:30 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
> 커스텀 익셉션만을 인식해서 그에 해당하는 다른 처리(로직)을 태워야 하는 상황일 경우 

이해가 잘 안되어서 궁금한건데, 혹시 너가 언급한 이 경우는 내가 작성한 경우랑 어떻게 다른 경우인거야??

2021-10-01 15:51 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
이건 저번에 남긴 리뷰에서 말했던 이야기라서 저렇게만 간단하게 이야기한거였어. 똑같은 리뷰 내용이였어가지구. 그리고 찾아보니깐 `assertThatThrownBy`인데 잘못 말해주긴 했네.. 근데 이건 구글에 그냥 assertThatIsThrownBy라고 저대로 쳐도 검색은 되는데..

일단 먼저 assertj가 상위호환인데 굳이 jupiter를 사용할 이유가 없다는 것이 assertj를 쓰자는 이유였고

두번째로 테스트 코드에서 어디선 mockito를, 어디선 BDDMockito를, 어디선 kotlin-mockito를, 어디선 Mockk를. 이렇게 한 프로젝트에서 서로 다른 라이브러리로 테스트 코드를 작성하면 작성하는 사람의 입장에서도, 그리고 코드를 읽는 사람의 입장에서도 가독성이 떨어질만한 요소라고 생각해. assertion 쪽 코드도 마찬가지로 한 라이브러리로 통일해서 가져갈 수 있다면 그 부분이 충분히 더 좋을 것 같아서 제안한거였어!!

2021-10-01 15:55 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
`@Mock`이 붙은 mock 객체를 `@InjectMocks` 어노테이션이 붙은 객체에 주입해줄 수 있고, 그렇다면 저기 setUp에서 따로 선언할 필요없이 제공되는 어노테이션을 사용해서 코드를 좀 더 간략하게 정리할 수 있어서 제안한 거 였어.

이 리뷰 방식이 내가 우테코에서 그냥 이런 식으로만 받아서 그런지 모르겠는데 특정한 키워드를 제공해주면 그걸 어떤 상황에서 어떻게 사용하면 장점이 있고 단점이 있는지 직접 공부하고 적용했거든. 그래서 뭔가 리뷰가 불친절하게 느껴졌던 거 같어..

사실 InjectMocks라는 단어로만 구글에 검색해도 어떤 상황에서 어떻게 사용하는지, 그리고 적용한다면 코드상에는 어떤 변화가 있는지. 그럼 이전에 작성한 코드와 비교했을 때 어떻게 다른지 등을 직접 느낄 수 있을 것 같다고 생각해서 키워드만 전달해줬던 건데 그럼 앞으로는 좀 더 상세하게 리뷰 남겨두도록 할게

2021-10-01 16:11 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
일단 앞서 말한거에서 상위가 아니라 하위라고 생각하면 될 것 같어.

> 지금의 서비스 상황에서는 그냥 모든 예외에서 예외를 발생시키고 끝 아닌가??

그래서 처음에 EntityNotFoundException에 대해서도 난 반대한거였어. 해당 Exception이 발생해도 추가적인 처리가 없다보니 굳이 이걸 커스텀 익셉션으로 처리해야 하는건가? 하는 의문이 들긴 했어.
지금은 그래서 추가로 해당 예외를 처리하기 쉽도록 메서드를 구현해두면서 그나마 의의를 가지고 있다고 생각하고 있고.

첫번째는 기존에 존재하는 예외를 사용하여 메시지를 상세하게 처리할 수 있다면 위 커스텀 익셉션이 하는 역할을 충분히 수행할 수 있다.
두번째는 만약 해당 특별 예외에 대해서 추가적인 처리가 필요하다면 커스텀 익셉션이 필요하다고 생각하는데 그런 부분이 없는 것 같다.

두번째는 예를 들어 우리가 S3를 연동하고 있는데 이때 File 생성하는 부분이 달라서 File 관련 예외가 터질 수 있고 AWS 연결이 실패해서 AWS 관련 예외가 발생할 수 있어. 그럼 우린 이걸 catch 문에서 각각 다르게 catch해서 전자의 경우는 File에 대한 상세한 정보를 전달하고 관련 추가 작업을 처리하는 작업을 할 것이고 후자는 AWS 커넥션이 문제라는 메시지를 전달하고 작업을 마치거나 할 수 있고.

이는 두 가지 서로 다른 예외를 다르게 catch 해야하기 때문에 커스텀 익셉션이 유의미한데 지금 위 예외나 EntityNotFound 예외는 둘 다 에러메시지를 상세하게 전달하기 위한 용도 말고는 추가적인 용도가 없는 것 같아서 그렇게 말한거였어.

아래 내가 첨부한 링크에서 커스텀 익셉션의 장점에 대해서 설명하는 부분도 있는데 우리는 log를 작성하기 때문에 동일한 IllegalArgumentException이 발생하더라도 어디서 발생했는지 추적이 가능해서 굳이 커스텀 익셉션을 여기서 만들 필요가 없을 것 같고, 에러메시지의 경우 일반 예외에서도 사용하기 위해서 따로 Message만 묶어서 관리하기 때문에 커스텀 익셉션으로의 응집도에 대한 부분도 장점이 없는 것 같아.

물론 커스텀 익셉션을 만드는게 나쁘다 이런건 아닌데 여기서 꼭 커스텀 익셉션으로 처리해야 하나? 그러기엔 정보의 상세한 전달 하나뿐인데 그 목적이라면 우리가 예외를 발생하는 모든 상황에서 커스텀 익셉션을 만들어야 한다는 말과 동일하다고 생각해. 그래서 지금 상황에서는 꼭 필요한 예외가 아니라고 생각해서 말한거였어!!

이건 내가 생각하고 말하고자 하는 부분이랑 많이 유사한 것 같아서 링크 걸어둘게
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

2021-10-01 16:18 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
![image](https://user-images.githubusercontent.com/48052622/135654006-98eae81f-a9c2-4d06-932e-a69cd65b7214.png)

이건 우리 회사 코드에서 일부 가져온거긴 한데 난 이 코드처럼 특정 예외에 따라서 서비스 적으로 다른 처리가 필요할 때 Custom Exception이 적절하다고 생각해

2021-10-02 02:54 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
당연히 지금은 내가 말했듯 로직상 추가적인 처리가 없는게 맞고, 그냥 에러 throw하고 끝인건 맞지만
일단 에러 메시지만해도 에러마다 다르잖아. 근데 이게 의미가 없는거라고 생각해?? 나는 이것만해도 충분히 의미가 있고, 그런 차이점을 떠나서 확장성을 고려한 부분이라고 생각해.

너가 준 링크에서도 표준 에러로만 처리하는 경우 어디서 에러가 발생한지 파악이 힘들다는 단점이 생긴다고도 말하는데, 그런 면에서도 커스텀 익셉션이 충분히 좋다고 봐.

너의 의견이 exception을 세분화해서 나누는게 '굳이 커스텀해서 사용해야하는가?' 인거같은데 사실 그런 의견이라면 우리가 작성한 모든 부분이 "굳이"가 될 수 있을 것 같은데?? 그럼 내가 위에 물었듯 어떤 부분에서 이게 손해가 될지 그걸 말해주면 좋을거같아.

2021-10-02 02:56 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
나도 당연히 구글링하고 찾아보기는 하지.
그런데 내가 리뷰를 통해 뭘 깨닫고 뭘 배우고를 떠나서 항상 리뷰에서 느낀 점 중 하나가, 이 리뷰의 의도가 무엇인지, 그래서 어떻게 해야하는지 명확하게 파악하기 어려운점이 많았어.
잘 생각해보면, 내가 리뷰 중에 "이건 왜 ~~하는거야?" 라는 식의 질문을 한게 많을거야. 내가 찾아보지 않은게 아니고, 명확하게 받아들이지를 못할때가 많았어

2021-10-02 03:06 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
> 근데 이건 구글에 그냥 assertThatIsThrownBy라고 저대로 쳐도 검색은 되는데..

너가 이렇게 말하면, 틀린 내용이 있는 리뷰를 받은 내 입장에서도 충분히 이렇게 말 할 수 있는 것 같은데.?

> 일단 먼저 assertj가 상위호환인데 굳이 jupiter를 사용할 이유가 없다는 것이 assertj를 쓰자는 이유였고

내가 원했던건 이런 내용이었어! 내가 spring 자체를 접하는 부분이 이 스터디에서밖에 없다보니까 정말 잘 몰라서, 실제로는 jupiter를 사용하지 않는다는 것을 몰랐고 상위호환인 것도 몰랐어. 라이브러리 import하는 부분에서도 봐도 `@BeforeEach` 라던지 `@Test` 에서도 Jupiter를 사용하고 있는데, 왜 assertion에서는 사용하지 말라는거지?를 처음 받은 리뷰만으로는 알 수가 없었으니까 !

2021-10-02 03:27 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
이건 앞서 말한 것처럼 내가 교육받았던 기간동안 많은 리뷰어들에게 받은 리뷰가 이런 식이여서 그런거 같아.

나도 당연히 처음에 스프링을 다 알고 있었던 건 아닐거였잖아. 교육받는 동안 항상 리뷰어는 '이런 상황에서는 assertj를 써보는건 어떨까요?' 라는 식으로 리뷰만 남겨줬어.
그럼 난 왜 이걸 써라고 하는거지? 이건 jupiter랑 뭐가 다르지? 이걸 쓰면 어떤 이득이 있는거지? 이런건 다 직접 구글링해보고 찾아보고 정리해서 다시 리뷰어에게 물어보고 했거든. 물론 이 내용들에 대해서 형이 다 알고있는 상태였다면 나도 바로 상세하게 이야기를 나누면 되겠지만 형 스스로 공부가 필요한 상황이라고 해서 키워드를 남겨뒀었던거야..

물론 형이 추가적으로 항상 더 공부한다는건 알고 있는데 이렇게 '상위호환이다' 라고만 내가 말해주면 내가 전달해주는 내용에 대해서만 이해하고 넘어갈 수 있지만 이건 순전히 나의 생각이고 assertj에 대한 형의 생각은 다를 수 있는 거잖아.
그래서 그 지식에 대한 습득과 판단, 그리고 본인의 생각과 리뷰어의 생각이 다르면 그 내용에 대한 논의를 그 이후에 진행하는 거라고 생각해서 키워드만 던져주는 식의 리뷰가 좀 더 학습방향에 맞다고 생각해서 그랬던거였어.

그리고 throw 관련 잘못 전달해준 것도 내가 다 검색해보고 정확히 맞는지 확인하고 이야기 못해준 것도 있지만 개인적으론 assertj랑 assertThatIsThrownBy라고 구글에 잘못 검색하더라도 충분히 내가 의도한 검색 결과는 나오던데 내가 느낀 기분은 구글에도 검색해보지 않고 그냥 ide에서 찾아봤는데 없다고 판단하고 바로 리뷰를 남긴 것 같아서 그렇게 말한거였어. 
물론 잘못 전달해 준 잘못도 있지만 100퍼센트 다 확실하게 이야기 해주긴 힘들 수도 있으니깐 한번쯤은 찾아보고 이걸 말하는게 맞는지 정돈 물어볼 수 있는거 아닌가 싶다고 생각하긴 했어.

2021-10-02 03:27 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        articleFavoriteService = ArticleFavoriteService(articleFavoriteRepository, articleRepository)
리뷰에 대한 생각은 아래에서 적어뒀어

2021-10-02 03:36 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
> 당연히 지금은 내가 말했듯 로직상 추가적인 처리가 없는게 맞고, 그냥 에러 throw하고 끝인건 맞지만
일단 에러 메시지만해도 에러마다 다르잖아. 근데 이게 의미가 없는거라고 생각해?? 나는 이것만해도 충분히 의미가 있고, 그런 차이점을 떠나서 확장성을 고려한 부분이라고 생각해.

이건 앞서 말했듯이 우리가 ErrorMessage라는 다른 파일에서 에러메시지를 관리하려고 하다보니 현재 크게 의미가 있는건 아닌 것 같다라고 말한 거였어. 해당 커스텀 익셉션에 대한 에러메시지 종류가 여러 개라면 모를까 지금은 전혀 아닌 상황이니깐.

> 너가 준 링크에서도 표준 에러로만 처리하는 경우 어디서 에러가 발생한지 파악이 힘들다는 단점이 생긴다고도 말하는데, 그런 면에서도 커스텀 익셉션이 충분히 좋다고 봐.

이것도 위에서 똑같이 말했는데 표준 에러로 처리하더라도 지금 우리는 로깅을 포인트마다 적용해두고 있으니깐 충분히 추적 가능하다고 봐. 그리고 해당 예외를 모든 엔티티들에 공통적으로 쓰는거면 어차피 사용되는 부분이 분산돼서 Article에서 발생해도 어떤 메서드에서 발생한건지 찾기 힘든건 마찬가지고. ArticleService의 a, b, c메서드에서 해당 에러가 발생한다면 결국 셋 중 하나란 소린데 정확히 어딘지는 모르잖아.

> 너의 의견이 exception을 세분화해서 나누는게 '굳이 커스텀해서 사용해야하는가?' 인거같은데 사실 그런 의견이라면 우리가 작성한 모든 부분이 "굳이"가 될 수 있을 것 같은데?? 그럼 내가 위에 물었듯 어떤 부분에서 이게 손해가 될지 그걸 말해주면 좋을거같아.

이건 일단 우리가 커스텀한 부분은 EntityNotFound 밖에 없는데 모든 부분은 어딜 말한거야? 그리고 이건 ResponseStatus가 404로 보내주기위한 의도가 있다고 해서 유의미하다고 위에 적어뒀어. 그런데 이번에 리뷰하는 부분은 어차피 IllegalArgumentException이랑 동일하게 400으로 처리할 거니깐 크게 의미가 없는 것 같다고 했고.


지금 리뷰가 도돌이푠데 난 형이 에러메시지가 에러에 대한 정보를 더 많이 전달해주는 부분이 이득이라는 의견에 대해서 위에서 다 의견을 전달했잖아. 추적에 대한 부분은 로깅을 활용하고 있기 때문에 일반적으로 제공되는 예외를 사용해도 전혀 지장있는 부분이 아니다. 그리고 커스텀 메시지를 따로 ErrorMessage라는 곳에서 일괄적으로 정리해두고 있기 때문에 이 또한 크게 장점이라 보기 어렵다. 그리고 이미 존재하는 인스턴스라는 이유 하나로 만들기엔 그러한 내용은 충분히 에러메시지로 전달이 가능하다.

말 그대로 예외에 대한 상세한 메시지 전달이 커스텀 익셉션의 의도라면 우린 모든 상황에서 그렇게 커스텀 익셉션을 적어야 하지않아? 만약 로그인 시 잘못된 패스워드를 입력할 경우 IllegalPasswordException, 만약 게시글의 사용자가 달라서 수정이 불가능한 경우 ArticleAuthorNotCorrectException 등등. 난 이런 경우랑 전혀 다르지 않다고 느껴서 그럼 어떤 상황에서 커스텀 익셉션을 쓰는게 적절한가를 위에 적어둔거야.

2021-10-02 03:54 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +    }
아 엉엉 저런거 다른 테스트에 영향을 안미치는(사이드 이펙트가 없는) 그런 거에 대해선 쓰면 되고 서비스 테스트처럼 영향을 미칠만한 부분만 직접 만들어서 쓰면 될 것 같어!!

2021-10-02 04:12 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
이거 내가 혹시나 싶어서 내가 이전에 작성한 리뷰랑 다시 읽어봤는데 형이 말한 의견에 대해서 난 어떻게 생각이 다른지에 대해 말했는데 결국 답변은 다시 형의 생각이 충분히 의미있다고 말하니깐 어떻게 말을 해야할지 잘 모르겠네..

내 생각을 다시 차례로 말해보자면 첫번째, 에러메시지에 대한 구체화가 가능하다는 내용은 해당 커스텀 익셉션으로 던지는 메시지가 한 종류밖에 없는데 이걸 위한 커스텀 익셉션 구현은 지나친거 같다. 응집도는 해당 커스텀 익셉션에서 관리해야 하는 메시지의 종류가 많아진다면 의미있는데 지금 구현된 AlreadyExistsException이 던질만한 메시지는 지금 작성된 메시지 하나 정도일 것 같다. 만약 이후 관련된 메시지가 더 많이 생기고 익셉션을 묶는게 의미가 있는 상황이 생긴다면 그때 논의해도 충분할 것 같고 현재 하나의 메시지로만 쓰는데 아직 고려되지 않은(아직 추가될 예정이 없는 예외 메시지) 부분을 염두하고 지금 구현하는건 불필요한 확장성을 고려한 느낌이 든다.
두번째로 커스텀 익셉션을 사용해 추적한다는 장점은 해당 익셉션을 사용하는 부분이 늘어날수록 장점이기 힘들고 로깅을 통해서 이미 이런 장점은 커버가 가능하다고 본다(오히려 로깅이 더 유용한 도구라 생각이 든다). 그리고 실제로 회사에서 서비스 운용시에도 에러메시지를 검색해서 로그 트랜잭션 넘버를 확인하고 그를 통해 에러를 추적하지 익셉션 클래스로 검색해서 에러 추적은 거의 하지 않는다. 그래서 해당 장점은 로그라는 도구를 도입하는 순간 충분히 커버된다고 생각한다.

이게 다시 내 생각 정리해봤어.
만약 형이 주장하는 에러 메시지의 구체화가 가능하다면 어떤 상황에서 의미를 가지고 기존 제공 예외에서 메시지를 구체화시켜서 전달하는 것에 비해서 어떤 장단점이 있는지. 추적 부분은 그럼 로그를 적용한 것에 비해 커스텀 익셉션이 어떤 추가적인 장점이 있는지. 위에서 내가 이야기한 것처럼 작은 사례나 케이스라고 작성해서 이야기를 해주면 좋을 것 같은데 내가 앞서 형이 말한 이야기에 대한 의견을 예시 사례도 제안하면서 의견을 제시했는데 다시 댓글 달린 느낌은 그건 그런데 이 의견이 충분히 장점이 있는 것 아냐? 이런 느낌이었어. 어떤 상황에서 어떤 부분에 이런 커스텀 익셉션을 적용하면 이점이 있는지. 내가 말한 부분이 어디가 단점이고 어떤 부분이 커스텀 익셉션을 사용함으로서 더 장점을 가지는 지 말을 해주면 나도 생각을 해보고 그 부분에 대해 의견을 제시할건데 지금 달린 답글은 그런 논의가 어려운 느낌이라 추가로 다시 댓글 달았어!!

2021-10-02 09:13 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
내 말은, "지금은 전혀 아닌 상황이니깐" 이라는 의견이라면 모든 부분에 있어서 지금 당장 필요하지 않을 수도 있는거 아니냐는 의도였어.

모든 부분이라는건 에러에 대해 말한게 아니고 정말 프로젝트의 모든 부분을 이야기하는거야. 모든 부분에서도 "지금 당장 굳이?"라고 물어보면 확장성을 고려해서 이렇게 구현했다고 말할 수 있을텐데 이 부분에는 어떤 기준으로 일어나지 않을 확장이라고 판단할지가 궁금해.

내가 익셉션을 분리한 이유가 "같은 에러"에 대해서는 같게 처리하고 "다른 에러"에 대해서는 다르게 처리할 수 있게, 또 한 에러에 대해서는 언제든 바뀌어도 해당 에러가 발생할 수 있는 모든 곳에서도 적용될 수 있도록 확장성을 고려했다고 말하면, 너는 지금 당장 굳이 필요하지 않다고 말할텐데 계속 위에 언급했듯 그 말 자체가 납득이 되지 않아서 **커스텀 익셉션으로 인해 발생하는 단점에 대해 물어본거였고.**

![image](https://user-images.githubusercontent.com/49271821/135710237-d30c2725-539e-4f1f-865b-ac0f2a63957e.png)

찾아보니까 custom exception의 네가지 Best practice 중에 이런 구절이 있네. 내가 계속 궁금해했던 점 처럼, 어떤 점에서 안좋을지를 명확하게 이야기해주고 있는데 딱 저렇게 **커스텀익셉션을 사용하지 않음으로 인해서 얻는 이점**이 궁금했어. **커스텀익셉션이 왜 굳이 필요없는지**가 아니라. 너가 자바 개발자니까 그런 부분에 대해 잘 인지하고 있을거라고 생각해서 물어본거야 그래야 충분히 납득이 갈거라고 생각해서. 어쨌든 저 글을 읽었을 때 이 부분에서 커스텀 익셉션을 사용하지 않으면 얻을 장점이 명확해보이는거같으니까 이제 납득이 되네 리뷰 반영할게 !

2021-10-02 09:28 UTC, hungry-jay commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
> 이건 앞서 말한 것처럼 내가 교육받았던 기간동안 많은 리뷰어들에게 받은 리뷰가 이런 식이여서 그런거 같아.

이건 교육 프로세스의 과정으로 멘토-멘티 관계에서 리뷰를 받아왔으니 그런거 아닐까? 우린 동등한 위치에서 코드에 대해 이야기를 하는건데 그런 방식보다는 명확한 메시지 전달이 더 중요할거같아. 위에 이야기했듯, 내가 "이건 왜 ~~이렇게 리뷰를 한거야?" 의 형태의 질문을 많이 했었는데 혹시 기억 나?

아래 캡쳐는 best practice for code review 에 대해 이야기한 아티클이야. 저기서도 **리뷰의 목표를 명확하게 할 것**에 대해 이야기하는데, 난 저기에 동의해. 생각보다 내가 너의 리뷰의 의도를 파악하는데 드는 리소스가 꽤 있다고 생각들었고, 그걸 줄이면 좋을 것 같아서 이야기한거였어. 리뷰받은 점에 대해 고민하고 공부하는 것은 당연히 나의 몫이며 필연적으로 검색도 하고 이것저것 해보겠지만, 리뷰어로서 저런 점들을 지향하면서 리뷰한다면 그 시간을 좀더 단축가능할 것 같은데 어떨까?

![image](https://user-images.githubusercontent.com/49271821/135710616-e1eeaf53-d157-4cb4-abfc-2c9afdd8b416.png)
https://www.perforce.com/blog/qac/9-best-practices-for-code-review

2021-10-02 13:03 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/commentfavorite/application/CommentFavoriteService.kt
> +            AlreadyExistsException.throwAlreadyExists(CommentFavorite::class)
내가 말한 부분에서 custom exception을 사용하는 것에 대한 구체적인 단점은 없었던 것 같아.

사실 a와 b중에 꼭 b가 단점이 있어서 a를 선택해야 하는건 아니라고 생각해. 그런 관점에서 나는 custom exception을 쓰면 정말 너무 단점이 많다 라는 관점보단 여기서 custom exception을 따로 구현해서 얼마나 많은 장점을 얻을 수 있지? 에 대한 의견 제시에 더 가까웠던 것 같아.

그러고 확장성에 대한 부분은 사실 형이랑 나의 가치관 차이인 것 같아. 난 예고되지 않은 확장성에 대한 고려는 오버엔지니어링이라는 이야기를 많이 듣기도 했고 그렇게 생각해서 그럴 수 있어.

지금 익셉션이 사용하는 부분은 instance가 존재하지 않는 부분에서만 사용되는 예외잖아. 그럼 정말 해당 예외의 이름을 바꿀 일이 있을까? 라는 부분에서 의문이 들었고, 지금 당장은 메시지를 한가지로만 사용하고 다른 메시지로 처리할 계획이나 그림이 없는 상태에서는 custom exception을 써서 얻을 수 있는 장점인 응집도라는 장점을 얻을 수 없다고 생각이 들어서 내 의견을 제시한거야.

물론 custom exception을 구현해서 쓰면 좋은 점이 있고 그건 나도 동의해. 그런데 지금 상황과 같이 custom exception을 생성하면 그 기준이 너무 모호하고 이렇게 메시지를 구체적으로 전달 가능하다는 장점을 기준으로 가져가면 우리가 기존에 exception으로 처리한 많은 코드들이 충분히 그 기준을 충족하는 대상이 된다고 생각했어. AlreadyExistException은 커스텀으로 쓰는데 로그인 시 패스워드가 일치하지 않는 부분은 custom exception으로 뽑으면 안되나? 라는 느낌이 들었거든.

말이 좀 길어지긴 했는데 결국 내가 주장한 건 지금의 기준으로 custom exception을 가져가기엔 그 기준이 너무 방대하고 해당하는 케이스가 많아서 custom exception을 구현할 포인트가 많아질 것 같다. 그러니 이 기준을 조금 더 명확히 가져가면 좋을 것 같다.
그 기준이 내가 생각하기엔 response status를 다르게 가져가야 할 경우 exception에 대한 구분이 필요하니 custom exception을 사용하기 적절하다고 생각했고, 만약 exception의 종류에 따라서 추가로 서비스 로직을 태워야 하는 경우에도 exception을 구분할 수 있어야 하니깐 이런 경우에 custom exception을 적용하는게 좋을 것 같다. 라는 의견이였어.

따로 custom exception을 쓰는게 나쁘단건 절대 아니고 과연 지금 우리가 이걸 써서 얻을 수 있는 장점이 많은가? 그렇다면 이걸 적용해야 하는 범위는 어디까지인가? 그렇게 되는 경우 지금 코드에 비해서 충분히 좋은 장점을 가져갈 수 있는가? 라는 생각을 해봤을 때 난 특별히 뛰어난 장점이 없다고 생각해서 의견을 제시한거야.

혹시나 내가 답변을 달아둔게 기분이 상하거나 조금 직설적이었다면 사과할게.. ㅠㅠ 단지 난 해당 부분에 대해 토의를 한다면 내가 말한 의견에 비해 형이 말한 부분이 어떤 장점이 있고 어떤 부분에서 더 좋으니깐 이걸 쓰는게 맞다. 이렇게 이야기를 해주면 나도 고민하고 이야기를 진행할 수 있을 것 같은데 형이 말한 장점에서 어떤 케이스에 확장성이 좋고 그럼 이게 지금 코드에 비해 얼마나 더 장점이 되는가. 추후 정말 확장성을 많이 가지게 되는 부분인 이유는? 단순히 에러 메시지를 구체화하는 것에 비해 custom exception으로 구현하면 어떤 장점이 있는가? 추적에 대한 부분은 log를 쓰는 것과 달리 다른 장점을 가져갈 수 있는가?? 이런 다양한 부분에 대한 주장을 해줬으면 나도 좀 더 고민해보고 이야기를 달았을 것 같어. 물론 그런 의도였는데 내가 또 잘못 이해했을 수도 있으니깐..

일단 앞으로 나도 내가 다는 리뷰에 대한 의도를 조금 더 명확하게 달아두도록 신경쓸게!! ㅜ,ㅡㅜ

2021-10-02 13:05 UTC, lxxjn0 commented on hongit-api/src/test/kotlin/com/devfloor/hongit/api/articlefavorite/ArticleFavoriteServiceTest.kt
> +        assertThat(thrownException.message).isEqualTo(errorMessage)
그러게 내가 단순히 형이 이런 부분에 대해서 잘 모른다고 이야기를 해서 알려준다는 느낌으로 리뷰를 단건 분명히 있는 것 같아.

지금 그런 관계는 아니고 같이 프로덕트를 만드는 관계에선 충분히 불친절한 리뷰라는 생각이 들긴 하네. 내가 저런 스타일을 리뷰를 받았을 때 best case를 알려주는 리뷰에 비해서 훨씬 배우는 내용도 많고 더 좋은 경험이 있었다보니 그렇게 나도 리뷰를 진행하긴 했는데 이 부분은 나도 좀 더 신경쓰도록 할게!!!

링크 달아둔 글은 나도 한번 읽어볼게!!

2021-10-15 06:41 UTC, lxxjn0 approved these changes
테스트 코드 assertion 부분에 저번에 리뷰 남긴 `assertThatThrownBy` 같은거 따로 적용은 안돼있던데 아직 안한거야??

남은 부분이 다 테스트 코드 쪽이라 수정하거나 반영할 부분 반영하고 머지해도 될 것 같어!!! 수고많았어 👍🏼

2021-10-17 13:36 UTC, merged