feat(auth) 회원가입 유효성 검증 추가
dev-floor/untitled-server pull request #86
Opened 2021-09-12 14:05 UTC by hungry-jay

closes #85

2021-09-21 14:41 UTC, lxxjn0 requested changes
이거 API URL 관련해서 코멘트 남겼는데 한번 확인 부탁할게!!
리뷰 넘 늦어서 미안.. ㅜㅠ

2021-09-21 14:41 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
>  ) {
안 그래도 이 부분 내 코드에서 수정을 해뒀는데 AuthController에는 정말 유효성 검증, 인증 관련된 로직이 있는게 좋을 것 같아서 join 코드를 UserController로 옮겼거든.
그래서 RequestMapping 주소는 그대로 BASE_API_URI로 가면 될 것 같아!!

2021-09-21 14:41 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
이 부분의 url도 통일하면 좋을 것 같은데 지금 내가 작업하는 코드에서

- 인증메일 발송 : POST /api/auth
- 인증토큰 검증 : GET /api/auth/tokens/{tokenId}

이렇게 갈 꺼라서 여기 코드들도 그냥

- GET /api/auth/users?username={username}
- GET /api/auth/users?nickname={nickname}
- GET /api/auth/users?classOf={classOf}

이렇게 가는게 좋을 것 같아!!!

2021-09-23 08:59 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
>  ) {
반영할게!

2021-09-23 09:00 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
반영할게!

2021-09-23 09:04 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
>  ) {
반영했음!

2021-09-23 09:04 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
반영했음!

2021-09-23 13:45 UTC, JoonBro approved these changes
수정사항 딱히 없어보입니다! 고생하셨습니다!

2021-09-25 11:17 UTC, lxxjn0 approved these changes
남긴 코멘트 하나 말곤 다 잘 작성된 것 같아!! 수고많았어!!

2021-09-25 11:17 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
>      }
이 로직은 기존대로 유지해야 할 것 같아!!
아이디, 닉네임, 학번에 대한 유효성 검증은 웹에서 검증이 되는거고 회원을 생성할 때는 추가로 진행되지 않잖아. 한 트랜잭션에서 이 모든 유효성 검증이 묶이는 게 아니라서 충분히 위조된 데이터가 들어올 수 있기 때문에 회원가입 시 한번 더 체크하는건 당연할 것 같아!!
이건 기존 코드 그대로 두자

2021-09-30 16:44 UTC, lxxjn0 requested changes
이것도 다시 추가적인 의견이 좀 있어서 리뷰 남겨뒀어.. ㅎㅎㅎ ㅜㅡㅜ

2021-09-30 16:44 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
이거 다시 보니깐 Boolean 반환이라 existsUserName 이런 식으로 작성하는게 어떨까?

validate는 Boolean을 반환한다는 느낌이 잘 들지가 않아서. 아래 내가 짠 것도 exception만 발생하고 따로 반환타입이 없어서 validate라고 이름 지었거든.

2021-09-30 16:44 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
이거 코드를 다시 좀 봐 봤는데 이런 방식은 어때?
이거 차라리 service에 메서드는 validate로 두고 서비스 로직 내에서 exception을 발생시키도록!!

```kotlin
fun validateUsername(username: String) {
    if (userRepository.existsByUsername(username)) throw IllegalArgumentException("이미 존재하는 username 입니다")
}
```

이렇게 하고 그냥 Controller에서는 반환타입 Unit으로 두고 @HttpStatus(HttpStatus.OK) 이걸로 처리하고!!
그럼 어차피 adviceController에서 캐치해서 오류 response 보낼꺼니깐!!

모든 메서드마다 이렇게 분기로 서로 다른 상태코드를 처리하는게 좀 좋은 방법은 아닌 것 같아서!! 차라리 의도적인 예외를 터트리고 adviceController에서 이걸 잡아서 다른 400대 코드랑 마찬가지로 처리해주면 더 깔끔할 것 같어!!

2021-10-01 02:04 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
컨트롤러에서 호출하는 서비스의 로직이고, 현재 서비스가 수행하는 일이 '존재하는지 아닌지'만 판별하는 것 뿐이지 결국 이 서비스가 수행해야 하는 일은 validate인게 맞으니까 저 네이밍이 맞지 않을까?

2021-10-01 02:06 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
아 그러고보니까 이것도 에러 컨트롤러에서 잡으면 되는거네. 반영할게 !

2021-10-01 02:06 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
>      }
반영했어!

2021-10-01 12:43 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
아 보통 boolean을 반환하는 명명을 일반적으론 has, is, exists 등등을 많이 쓰는데 그런 이름으로 표현이 가능한 코드라면 다른 사람들이 대중적으로 생각하는 명명을 짓는게 좀 더 좋을 것 같아서!!

2021-10-01 15:22 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
그건 물론 알고 있지만, 결국 서비스 로직이잖아 내가 제시한 의견에 대해서는 어떻게 생각해?

2021-10-02 02:40 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
다시 말하면 결국 서비스가 수행할 로직은 validate인거고, 그 로직 내부에 exist가 있는것 뿐이지 서비스 로직 자체가 exist한지 아닌지만을 판별하기 위한게 아니니까 말한거였어 !

2021-10-02 03:13 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
아 그렇다면 isValid.. 이런식으로 가는건 어떤가?? validate... 으로 이름이 가면 함수명을 읽었을때 Boolean 타입인지 명확하게 느껴지지 않는 것 같아서

2021-10-02 09:32 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
> +    fun validateClassOf(classOf: String) = !userRepository.existsByClassOf(classOf)
`isValid` 이게 좋을거같다. 이거로 반영할게 !

2021-10-09 05:49 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
이거 다시봤는데 IllegalArgumentException으로 처리하게되면 무조건 400 코드로만 보내게 되는거 아니야??

2021-10-10 02:49 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
아 저건 422 에러코드네. 나 저런 에러코드는 처음 보는데 저런 에러코드도 자주 써??

2021-10-17 13:37 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
이 부분 더 논의할부분 있을까요??

2021-10-24 01:20 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
> +        }
이거 일단 422로 처리하구 익셉션은 상태코드랑 동일하게 이름 가져가는 건 어때?

2021-10-24 03:15 UTC, lxxjn0 approved these changes

2021-10-26 09:38 UTC, merged