feature(user): 프로필 수정 API
dev-floor/untitled-server pull request #91
Opened 2021-10-02 14:33 UTC by JoonBro

프로필 수정 API

2021-10-03 03:10 UTC, lxxjn0 requested changes
리뷰 남겼는데 추가로 수정해야 할 부분들이 있을 것 같아서 이 부분 확인해서 적용해줘!!

2021-10-03 03:10 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/UserController.kt
> +    ) = userService.modifyByNickname(nickname, request)
나중에 프로필 정보가 아닌 개인정보를 수정하는 코드도 생겨야 할 수 있으니깐 modifyProfileByNickname이 이름이 좀 더 적절할 듯?

2021-10-03 03:10 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +    fun modifyByNickname(nickname: String, request: ProfileModifyRequest) {
이거 ProfileModifyRequest 코드는 왜 나한테는 안보이지? 이전에 만들어졌던 코드인건가??

2021-10-03 03:10 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +            ?: EntityNotFoundException.notExistsNickname(User::class, nickname)
이거 로직이 조금 부족한 것 같아.
우선 넘어온 닉네임으로 유저를 조회하고, 변경을 원하는 닉네임이 존재하지 않을 경우는 수정을 하는데 존재할 경우는 아무런 작업도 안하고 exception도 발생 안하네.

그리고 이번 수정 부분에서 nickname은 없지 않았어? 내 기억으론 image, github, blog, description만 수정 가능하고 나머진 추후 개인정보 수정에서 들어가는게 나을 것 같아. 슬랙보면 아마 정리되어 있는거 같어

그래서 아마 여기서 nickname을 빼면 따로 유효성 검증해야 하는 로직이 필요없어서 그냥 바로 수정하는 코드 적용하면 될 듯?

2021-10-03 03:10 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
> +    }
이것도 위에 말한 부분 적용하고 수정하면 될 것 같아!!

2021-10-07 00:58 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +            ?: EntityNotFoundException.notExistsNickname(User::class, nickname)
이거 저번주 회의전에 했던거라 그럼 ㅋㅋ 수정중~~

2021-10-08 08:18 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +    fun modifyByNickname(nickname: String, request: ProfileModifyRequest) {
안보인단게 무슨말이야?? 이번에 준형님이 만드신거 아닌가!??

2021-10-08 08:24 UTC, hungryjayy reviewed
고생하셨습니다. 수정 후에 다시 봐볼게요!

2021-10-08 08:24 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/UserController.kt
> +        @RequestParam nickname: String,
nickname이 URI에 붙어있는거라 @PathVariable로 가져와야하지 않나요?

2021-10-08 08:24 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +            ?: EntityNotFoundException.notExistsNickname(User::class, nickname)
수정하시고 계신거같아서 수정 이후에 다시 봐보겠습니다!

2021-10-09 16:49 UTC, hungry-jay reviewed
내일 파트 회의때 더 이야기 해보면 좋을 것 같습니다 !

2021-10-09 16:49 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/EntityAlreadyExistException.kt
> +    }
일단 custom Exception에 대한 이야기가 있었는데요!

해당 이력에 대해 말씀 드리자면 아래 링크의 부분입니다.!
https://github.com/dev-floor/hongit-server/pull/81#pullrequestreview-768079873

한번 읽어보시고, 의견이 있으시다면 공유 해주셔도 좋을 것 같습니다.
혹은 자유롭게 의견을 말씀해주셔도 좋습니다.!

2021-10-09 16:49 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +    fun modifyUserByNickname(loginUser: User, request: UserModifyRequest) {
혹시 이 부분에 password를 검증하는 로직이 없어도 괜찮을까요?
기억하기에 기획상 딱히 필요 없을 것 같긴 했었는데 없는게 맞는건가요!?

2021-10-09 16:49 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/UserController.kt
> +    @PutMapping(value = ["$USER_API_URI/myprofile"])
이 부분에 대해 논의를 드리고 싶은 점이 있습니다.!
그런데 어차피 내일 API의 URI 정할 때 이야기하면 좋을 것 같아서 그때 이야기하고, 그 결과에 따라서 이 부분도 일관성 있게 적용되면 될 것 같아요.

2021-10-10 03:34 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/UserController.kt
> +    @PutMapping(value = ["$USER_API_URI/my"])
```suggestion
    @PutMapping(value = ["/me"])
```

2021-10-12 02:31 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +    fun modifyUserByNickname(loginUser: User, request: UserModifyRequest) {
기획상 닉네임 변경에는 검증 없었습니다!

2021-10-12 02:35 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/EntityAlreadyExistException.kt
> +    }
네 저도 읽어봤는데 두 방법 중에 뚜렷한 장점이 있는게 아니라서 애매하네요... 일단 추후 여러가지 에러에 대해서 공통된(문자열 리턴 역할) 처리를 하지만 도메인이나 특징을 가지고 분류해놓고 관리하기엔 형의견이 좋은거같구욥.. 준영이 말대로 예외처리로 인한 로직이 따로 존재하지 않는데 굳이 커스터마이징을 할 필요가 없다는 말도 맞아서.... 저는 따라가겠습니다... ㅋㅋㅋ

2021-10-15 06:49 UTC, lxxjn0 requested changes
한 두가지 부분만 추가로 코멘트 남겼는데 확인 부탁드림요~~ ㅎㅅㅎ

2021-10-15 06:49 UTC, lxxjn0 commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
> +    }
이거 둘 다 이름을 match 쪽으로 가져가는건 어때? `matchId`, `matchNickname` 이런 식으로?
내가 다른 로직에서 matchPassword 같은 형식으로 쓰고 있어서 메서드 명을 맞추면 좋을 것 같아서!!

2021-10-15 06:49 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +                if (!userRepository.existsByNickname(request.nickname) && !loginUser.isSameNickname(request.nickname)) {
if문 조건을 따로 메서드로 추출해도 좋을 것 같아. 해당 조건이 request로 들어온 닉네임이 사용 가능한가? 유효한가? 를 판별하는 로직이니깐 따로 메서드로 추출할 만 하지 않을까 싶어. 

아니면 아예 if / else 문 전체를 따로 메서드로 뽑아버리는 것도 좋고. 조건 여부에 따라서 수정을 하는 로직이니깐 하나의 메서드로 추출해도 괜찮을 것 같아

2021-10-15 14:00 UTC, JoonBro commented on hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
> +    }
넹~

2021-10-17 14:14 UTC, hungry-jay reviewed
리뷰입니다!

2021-10-17 14:14 UTC, hungryjayy commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +        userRepository.findByNicknameOrNull(loginUser.nickname)
더티채킹 통해서 변경사항 반영시키려면 Transactional 붙여야할거같아요!

2021-10-17 14:14 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +    }
`validateNickname`으로 바꾸고 유효하지 않은 경우에 익셉션 throw하도록 하는 방법은 어떨까요?

혹은 만약 이대로 사용한다면 네이밍을 boolean임이 유추 가능하도록 `is~~` 의 형태가 좋을거같아요

2021-10-17 14:14 UTC, hungry-jay commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/request/ProfileModifyRequest.kt
> +data class ProfileModifyRequest(
이 data class 아무데서도 사용되지 않는 것 같은데, 혹시 만드신 의도가 무엇인가요?

2021-10-24 03:14 UTC, JoonBro commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/request/ProfileModifyRequest.kt
> +data class ProfileModifyRequest(
삭제했습니당!

2021-10-30 03:26 UTC, lxxjn0 approved these changes

2021-10-30 03:26 UTC, lxxjn0 commented on hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
> +        if(!userRepository.existsByNickname(requestNickname) && nickname != (requestNickname)){
이거 조건이 너무 긴 거 같은데 이거만 따로 함수로 뽑거나 하고 코드 머지해도 될 듯?

2021-11-06 15:45 UTC, merged